import type { CanonicalStrategyIrV1 } from '../../types/canonical-strategy-ir'
import type { StrategyAstV1 } from '../../types/canonical-strategy-ast'
import { createHash } from 'node:crypto'
import { canonicalSerialize } from '@ai/shared/script-engine/compiled-runtime'
import { CompiledPublicationGateService } from '../compiled-publication-gate.service'

function newGate(): CompiledPublicationGateService {
  return new CompiledPublicationGateService(
    { create: jest.fn() } as never,
    { withTransaction: (cb: () => Promise<unknown>) => cb() } as never,
  )
}

function hashCanonical(value: unknown): string {
  return createHash('sha256').update(canonicalSerialize(value)).digest('hex')
}

function linkFixtureHashes(input: {
  rules: unknown[]
  canonicalSpec: Record<string, unknown>
  ir: CanonicalStrategyIrV1
  ast: StrategyAstV1
}): {
  canonicalSpecHash: string
  irHash: string
  astHash: string
} {
  const rulesHash = hashCanonical(input.rules)
  input.canonicalSpec.metadata = { rulesHash }
  const canonicalSpecHash = hashCanonical(input.canonicalSpec)
  input.ir.source.graphDigest = `sha256:${canonicalSpecHash}`
  input.ir.source.specHash = `sha256:${canonicalSpecHash}`
  const irHash = hashCanonical(input.ir)
  input.ast.manifest.irHash = `sha256:${irHash}`
  input.ast.manifest.specHash = `sha256:${canonicalSpecHash}`
  const astHash = hashCanonical({
    astVersion: input.ast.astVersion,
    executionModel: input.ast.executionModel,
    dataRequirements: input.ast.dataRequirements,
    runtimeRequirements: input.ast.runtimeRequirements,
    exprPool: input.ast.exprPool,
    guards: input.ast.guards,
    riskPredicates: input.ast.riskPredicates,
    decisionPrograms: input.ast.decisionPrograms,
    orderPrograms: input.ast.orderPrograms,
    topology: input.ast.topology,
  })
  input.ast.manifest.structuralDigest = `sha256:${astHash}`
  return { canonicalSpecHash, irHash, astHash }
}

function scriptForHashes(hashes: { canonicalSpecHash: string, irHash: string, astHash: string }): string {
  return [
    '/* @generated by compiler.v1 */',
    `/* irHash: sha256:${hashes.irHash} */`,
    `/* specHash: sha256:${hashes.canonicalSpecHash} */`,
    `/* astDigest: sha256:${hashes.astHash} */`,
    `/* structuralDigest: sha256:${hashes.astHash} */`,
    '',
    'const DECISION_PROGRAMS = [{"sourceRef":"semantic-entry-rule-entry"}] as const',
  ].join('\n')
}

function fixture(): {
  rules: unknown[]
  canonicalSpec: Record<string, unknown>
  ir: CanonicalStrategyIrV1
  ast: StrategyAstV1
  script: string
} {
  const zeroHash = `sha256:${'0'.repeat(64)}` as const
  const rules = [{
    id: 'rule-entry',
    phase: 'entry',
    condition: { kind: 'atom', key: 'price.above' },
    effects: {
      actions: [{ kind: 'atom', key: 'action.open_long' }],
    },
  }]
  const canonicalSpec = {
    schemaVersion: 2,
    rules: [{
      id: 'semantic-entry-rule-entry',
      phase: 'entry',
      priority: 100,
      condition: { kind: 'atom', key: 'price.above' },
      actions: [{ type: 'OPEN_LONG', sourcePath: 'rules[0].effects.actions[0]' }],
      metadata: { sourcePath: 'rules[0]' },
    }],
  }
  const ir = {
    irVersion: 'csi.v1',
    source: {
      graphVersion: 1,
      graphDigest: zeroHash,
      specHash: zeroHash,
    },
    market: {
      venue: 'binance',
      instrumentType: 'perpetual',
      symbol: 'BTCUSDT',
      timeframes: ['15m'],
      priceFeed: 'close',
    },
    portfolio: {
      positionMode: 'long_only',
      sizing: { mode: 'pct_equity', value: 10 },
      maxConcurrentPositions: 1,
      allowPyramiding: false,
      maxPyramidingLayers: 1,
    },
    dataRequirements: {
      warmupBars: 1,
      maxLookback: 1,
      requiredTimeframes: ['15m'],
    },
    signalCatalog: {
      series: [],
      levelSets: [],
      predicates: [{ id: 'semantic-entry-rule-entry_predicate', kind: 'GT', args: [] }],
    },
    ruleBlocks: [{
      id: 'semantic-entry-rule-entry',
      phase: 'entry',
      when: 'semantic-entry-rule-entry_predicate',
      priority: 100,
      actions: [{ kind: 'OPEN_LONG', quantity: { mode: 'pct_equity', value: 10 } }],
      metadata: { sourcePath: 'rules[0]' },
    }],
    orderPrograms: [],
    riskPolicy: { guards: [] },
    executionPolicy: {
      signalEvaluation: 'bar_close',
      fillPolicy: 'next_bar_open',
      timeframeAlignment: 'strict',
      orderTypeDefault: 'market',
      timeInForce: 'gtc',
      allowPartialFill: false,
    },
  } satisfies CanonicalStrategyIrV1
  const ast = {
    astVersion: 'csa.v1',
    manifest: {
      irVersion: 'csi.v1',
      irHash: zeroHash,
      specHash: zeroHash,
      compileVersion: 'compiler.v1',
      structuralDigest: zeroHash,
    },
    executionModel: {
      venue: 'binance',
      instrumentType: 'perpetual',
      symbol: 'BTCUSDT',
      primaryTimeframe: '15m',
      timeframeAlignment: 'strict',
      signalEvaluation: 'bar_close',
      fillPolicy: 'next_bar_open',
      defaultOrderType: 'market',
      allowPartialFill: false,
    },
    dataRequirements: ir.dataRequirements,
    exprPool: [{
      id: 'expr_01_semantic-entry-rule-entry_predicate',
      sourceRef: 'semantic-entry-rule-entry_predicate',
      nodeType: 'predicate',
      payload: { id: 'semantic-entry-rule-entry_predicate', kind: 'GT', args: [] },
      deps: [],
    }],
    guards: [],
    decisionPrograms: [{
      id: 'decision_01_semantic-entry-rule-entry',
      sourceRef: 'semantic-entry-rule-entry',
      phase: 'entry',
      when: 'expr_01_semantic-entry-rule-entry_predicate',
      priority: 100,
      actions: [{ kind: 'OPEN_LONG', quantity: { mode: 'pct_equity', value: 10 } }],
      metadata: { sourcePath: 'rules[0]' },
    }],
    orderPrograms: [],
    topology: {
      exprOrder: ['expr_01_semantic-entry-rule-entry_predicate'],
      guardOrder: [],
      decisionOrder: ['decision_01_semantic-entry-rule-entry'],
      orderProgramOrder: [],
    },
  } satisfies StrategyAstV1
  const linked = linkFixtureHashes({ rules, canonicalSpec, ir, ast })
  const script = scriptForHashes(linked)

  return { rules, canonicalSpec, ir, ast, script }
}

describe('publication gate rules-only hash chain', () => {
  it('passes when canonical, ir, ast, and script trace to rules hash', () => {
    const result = newGate().validateRulesOnlyHashChain(fixture())

    expect(result).toEqual(expect.objectContaining({
      passed: true,
      blocked: false,
      hashes: expect.objectContaining({
        rulesHash: expect.stringMatching(/^[a-f0-9]{64}$/),
        canonicalSpecHash: expect.stringMatching(/^[a-f0-9]{64}$/),
        irHash: expect.stringMatching(/^[a-f0-9]{64}$/),
        astHash: expect.stringMatching(/^[a-f0-9]{64}$/),
        scriptHash: expect.stringMatching(/^[a-f0-9]{64}$/),
      }),
    }))
    expect(result.checks).toEqual(expect.arrayContaining([
      expect.objectContaining({ key: 'trace.canonical', passed: true }),
      expect.objectContaining({ key: 'trace.ir', passed: true }),
      expect.objectContaining({ key: 'trace.ast', passed: true }),
      expect.objectContaining({ key: 'trace.script', passed: true }),
    ]))
  })

  it('blocks when IR omits source path trace', () => {
    const input = fixture()
    delete input.ir.ruleBlocks[0].metadata
    const linked = linkFixtureHashes(input)
    input.script = scriptForHashes(linked)

    const result = newGate().validateRulesOnlyHashChain(input)

    expect(result.passed).toBe(false)
    expect(result.blocked).toBe(true)
    expect(result.reason).toBe('rules_only_trace_missing')
    expect(result.checks).toEqual(expect.arrayContaining([
      expect.objectContaining({ key: 'trace.ir', passed: false }),
    ]))
  })

  it('blocks when IR and AST source paths are outside canonical trace set', () => {
    const input = fixture()
    input.ir.ruleBlocks[0].metadata = { sourcePath: 'rules[999]' }
    input.ast.decisionPrograms[0].metadata = { sourcePath: 'rules[999]' }
    const linked = linkFixtureHashes(input)
    input.script = scriptForHashes(linked)

    const result = newGate().validateRulesOnlyHashChain(input)

    expect(result.passed).toBe(false)
    expect(result.blocked).toBe(true)
    expect(result.reason).toBe('rules_only_trace_missing')
    expect(result.checks).toEqual(expect.arrayContaining([
      expect.objectContaining({ key: 'trace.ir', passed: false }),
      expect.objectContaining({ key: 'trace.ast', passed: false }),
    ]))
  })

  it('blocks when canonical rulesHash is missing', () => {
    const input = fixture()
    delete input.canonicalSpec.metadata
    const canonicalSpecHash = hashCanonical(input.canonicalSpec)
    input.ir.source.graphDigest = `sha256:${canonicalSpecHash}`
    input.ir.source.specHash = `sha256:${canonicalSpecHash}`
    const irHash = hashCanonical(input.ir)
    input.ast.manifest.irHash = `sha256:${irHash}`
    input.ast.manifest.specHash = `sha256:${canonicalSpecHash}`
    const astHash = hashCanonical({
      astVersion: input.ast.astVersion,
      executionModel: input.ast.executionModel,
      dataRequirements: input.ast.dataRequirements,
      runtimeRequirements: input.ast.runtimeRequirements,
      exprPool: input.ast.exprPool,
      guards: input.ast.guards,
      riskPredicates: input.ast.riskPredicates,
      decisionPrograms: input.ast.decisionPrograms,
      orderPrograms: input.ast.orderPrograms,
      topology: input.ast.topology,
    })
    input.script = scriptForHashes({ canonicalSpecHash, irHash, astHash })

    const result = newGate().validateRulesOnlyHashChain(input)

    expect(result.passed).toBe(false)
    expect(result.blocked).toBe(true)
    expect(result.reason).toBe('rules_only_hash_mismatch')
    expect(result.checks).toEqual(expect.arrayContaining([
      expect.objectContaining({ key: 'hash.canonical.rulesHash', passed: false }),
    ]))
  })

  it('blocks when IR hash linkage mismatches AST manifest', () => {
    const input = fixture()
    input.ast.manifest.irHash = `sha256:${'1'.repeat(64)}`

    const result = newGate().validateRulesOnlyHashChain(input)

    expect(result.passed).toBe(false)
    expect(result.blocked).toBe(true)
    expect(result.reason).toBe('rules_only_hash_mismatch')
    expect(result.checks).toEqual(expect.arrayContaining([
      expect.objectContaining({ key: 'hash.ast.irHash', passed: false }),
    ]))
  })

  it('blocks when script only mentions rules path string but manifest hash mismatches', () => {
    const input = fixture()
    input.script = [
      '/* @generated by compiler.v1 */',
      `/* irHash: sha256:${'2'.repeat(64)} */`,
      `/* specHash: sha256:${'3'.repeat(64)} */`,
      `/* astDigest: sha256:${'4'.repeat(64)} */`,
      `/* structuralDigest: sha256:${'5'.repeat(64)} */`,
      '',
      '// rules[0]',
    ].join('\n')

    const result = newGate().validateRulesOnlyHashChain(input)

    expect(result.passed).toBe(false)
    expect(result.blocked).toBe(true)
    expect(result.reason).toBe('rules_only_hash_mismatch')
    expect(result.checks).toEqual(expect.arrayContaining([
      expect.objectContaining({ key: 'hash.script.irHash', passed: false }),
      expect.objectContaining({ key: 'hash.script.specHash', passed: false }),
      expect.objectContaining({ key: 'trace.script', passed: false }),
    ]))
  })
})
