import type { CanonicalStrategyIrV1 } from '../../types/canonical-strategy-ir'
import type { StrategyAstV1 } from '../../types/canonical-strategy-ast'
import { CompiledPublicationGateService } from '../compiled-publication-gate.service'

const hash64 = '0'.repeat(64)
const specHash = `sha256:${hash64}` as const

function newGate(): CompiledPublicationGateService {
  return new CompiledPublicationGateService(
    { create: jest.fn() } as never,
    { withTransaction: (cb: () => Promise<unknown>) => cb() } as never,
  )
}

function fixture(): {
  rules: unknown[]
  canonicalSpec: Record<string, unknown>
  ir: CanonicalStrategyIrV1
  ast: StrategyAstV1
  script: string
} {
  const rules = [{
    id: 'rule-entry',
    phase: 'entry',
    condition: { kind: 'atom', key: 'price.above' },
    effects: {
      actions: [{ kind: 'atom', key: 'action.open_long' }],
    },
  }]
  const canonicalSpec = {
    schemaVersion: 2,
    rules: [{
      id: 'semantic-entry-rule-entry',
      phase: 'entry',
      priority: 100,
      condition: { kind: 'atom', key: 'price.above' },
      actions: [{ type: 'OPEN_LONG', sourcePath: 'rules[0].effects.actions[0]' }],
      metadata: { sourcePath: 'rules[0]' },
    }],
  }
  const ir = {
    irVersion: 'csi.v1',
    source: {
      graphVersion: 1,
      graphDigest: specHash,
      specHash,
    },
    market: {
      venue: 'binance',
      instrumentType: 'perpetual',
      symbol: 'BTCUSDT',
      timeframes: ['15m'],
      priceFeed: 'close',
    },
    portfolio: {
      positionMode: 'long_only',
      sizing: { mode: 'pct_equity', value: 10 },
      maxConcurrentPositions: 1,
      allowPyramiding: false,
      maxPyramidingLayers: 1,
    },
    dataRequirements: {
      warmupBars: 1,
      maxLookback: 1,
      requiredTimeframes: ['15m'],
    },
    signalCatalog: {
      series: [],
      levelSets: [],
      predicates: [{ id: 'semantic-entry-rule-entry_predicate', kind: 'GT', args: [] }],
    },
    ruleBlocks: [{
      id: 'semantic-entry-rule-entry',
      phase: 'entry',
      when: 'semantic-entry-rule-entry_predicate',
      priority: 100,
      actions: [{ kind: 'OPEN_LONG', quantity: { mode: 'pct_equity', value: 10 } }],
    }],
    orderPrograms: [],
    riskPolicy: { guards: [] },
    executionPolicy: {
      signalEvaluation: 'bar_close',
      fillPolicy: 'next_bar_open',
      timeframeAlignment: 'strict',
      orderTypeDefault: 'market',
      timeInForce: 'gtc',
      allowPartialFill: false,
    },
  } satisfies CanonicalStrategyIrV1
  const ast = {
    astVersion: 'csa.v1',
    manifest: {
      irVersion: 'csi.v1',
      irHash: specHash,
      specHash,
      compileVersion: 'compiler.v1',
      structuralDigest: specHash,
    },
    executionModel: {
      venue: 'binance',
      instrumentType: 'perpetual',
      symbol: 'BTCUSDT',
      primaryTimeframe: '15m',
      timeframeAlignment: 'strict',
      signalEvaluation: 'bar_close',
      fillPolicy: 'next_bar_open',
      defaultOrderType: 'market',
      allowPartialFill: false,
    },
    dataRequirements: ir.dataRequirements,
    exprPool: [{
      id: 'expr_01_semantic-entry-rule-entry_predicate',
      sourceRef: 'semantic-entry-rule-entry_predicate',
      nodeType: 'predicate',
      payload: { id: 'semantic-entry-rule-entry_predicate', kind: 'GT', args: [] },
      deps: [],
    }],
    guards: [],
    decisionPrograms: [{
      id: 'decision_01_semantic-entry-rule-entry',
      sourceRef: 'semantic-entry-rule-entry',
      phase: 'entry',
      when: 'expr_01_semantic-entry-rule-entry_predicate',
      priority: 100,
      actions: [{ kind: 'OPEN_LONG', quantity: { mode: 'pct_equity', value: 10 } }],
    }],
    orderPrograms: [],
    topology: {
      exprOrder: ['expr_01_semantic-entry-rule-entry_predicate'],
      guardOrder: [],
      decisionOrder: ['decision_01_semantic-entry-rule-entry'],
      orderProgramOrder: [],
    },
  } satisfies StrategyAstV1
  const script = [
    '/* @generated by compiler.v1 */',
    `/* irHash: ${specHash} */`,
    `/* specHash: ${specHash} */`,
    `/* astDigest: ${specHash} */`,
    `/* structuralDigest: ${specHash} */`,
    '',
    'const DECISION_PROGRAMS = [{"sourceRef":"semantic-entry-rule-entry"}] as const',
  ].join('\n')

  return { rules, canonicalSpec, ir, ast, script }
}

describe('publication gate rules-only hash chain', () => {
  it('passes when canonical, ir, ast, and script trace to rules hash', () => {
    const result = newGate().validateRulesOnlyHashChain(fixture())

    expect(result).toEqual(expect.objectContaining({
      passed: true,
      blocked: false,
      hashes: expect.objectContaining({
        rulesHash: expect.stringMatching(/^[a-f0-9]{64}$/),
        canonicalSpecHash: expect.stringMatching(/^[a-f0-9]{64}$/),
        irHash: expect.stringMatching(/^[a-f0-9]{64}$/),
        astHash: expect.stringMatching(/^[a-f0-9]{64}$/),
        scriptHash: expect.stringMatching(/^[a-f0-9]{64}$/),
      }),
    }))
    expect(result.checks).toEqual(expect.arrayContaining([
      expect.objectContaining({ key: 'trace.canonical', passed: true }),
      expect.objectContaining({ key: 'trace.ir', passed: true }),
      expect.objectContaining({ key: 'trace.ast', passed: true }),
      expect.objectContaining({ key: 'trace.script', passed: true }),
    ]))
  })

  it('blocks when IR omits source path trace', () => {
    const input = fixture()
    input.ir.ruleBlocks = []

    const result = newGate().validateRulesOnlyHashChain(input)

    expect(result.passed).toBe(false)
    expect(result.blocked).toBe(true)
    expect(result.reason).toBe('rules_only_trace_missing')
    expect(result.checks).toEqual(expect.arrayContaining([
      expect.objectContaining({ key: 'trace.ir', passed: false }),
    ]))
  })
})
