import type { DisplayToken } from './display-token.types'

export const DISPLAY_TOKENS = [
  { token: 'atom.execution.on_start.name', kind: 'atom', zh: '启动后执行' },
  { token: 'atom.condition.expression.name', kind: 'atom', zh: '表达式条件' },
  { token: 'atom.condition.expression.display', kind: 'atom', zh: '{label}' },
  { token: 'atom.semantic.missing_entry_atom.name', kind: 'atom', zh: '缺少入场条件' },
  { token: 'atom.semantic.missing_exit_atom.name', kind: 'atom', zh: '缺少出场条件' },
  { token: 'atom.price.percent_change.name', kind: 'atom', zh: '价格百分比变化' },
  { token: 'atom.price.breakout_up.name', kind: 'atom', zh: '向上突破' },
  { token: 'atom.price.breakout_down.name', kind: 'atom', zh: '向下跌破' },
  { token: 'atom.price.rolling_extrema_breakout.name', kind: 'atom', zh: '滚动高低点突破' },
  { token: 'atom.price.range_position_lte.name', kind: 'atom', zh: '区间低位' },
  { token: 'atom.price.range_position_gte.name', kind: 'atom', zh: '区间高位' },
  { token: 'atom.price.detect.indicator_boundary.name', kind: 'atom', zh: '价格触及指标边界' },
  { token: 'atom.condition.sequence.name', kind: 'atom', zh: '顺序条件' },
  { token: 'atom.confirmation.rebound.name', kind: 'atom', zh: '反弹确认' },
  { token: 'atom.logical.any_of.name', kind: 'atom', zh: '任一条件满足' },
  { token: 'atom.volume.relative_average.name', kind: 'atom', zh: '相对均量' },
  { token: 'atom.indicator.boundary_touch.name', kind: 'atom', zh: '指标边界触及' },
  { token: 'atom.indicator.cross_over.name', kind: 'atom', zh: '指标上穿' },
  { token: 'atom.indicator.cross_under.name', kind: 'atom', zh: '指标下穿' },
  { token: 'atom.indicator.threshold_gte.name', kind: 'atom', zh: '指标高于阈值' },
  { token: 'atom.indicator.threshold_lte.name', kind: 'atom', zh: '指标低于阈值' },
  { token: 'atom.indicator.boundary_cross.name', kind: 'atom', zh: '指标边界穿越' },
  { token: 'atom.bollinger.touch_upper.name', kind: 'atom', zh: '触及布林上轨' },
  { token: 'atom.bollinger.touch_lower.name', kind: 'atom', zh: '触及布林下轨' },
  { token: 'atom.bollinger.touch_middle.name', kind: 'atom', zh: '触及布林中轨' },
  { token: 'atom.oscillator.rsi_gte.name', kind: 'atom', zh: 'RSI 高于阈值' },
  { token: 'atom.oscillator.rsi_lte.name', kind: 'atom', zh: 'RSI 低于阈值' },
  { token: 'atom.trend.direction.name', kind: 'atom', zh: '趋势方向' },
  { token: 'atom.indicator_boundary_touch.display', kind: 'atom', zh: '触及 {indicator} {boundaryRole}{settings}' },
  { token: 'atom.volume.threshold.name', kind: 'atom', zh: '成交量阈值' },
  { token: 'atom.volume.threshold.display', kind: 'atom', zh: '{metric} {operator} {value}' },
  { token: 'atom.volatility.atr_threshold.name', kind: 'atom', zh: 'ATR 波动率阈值' },
  { token: 'atom.volatility.atr_threshold.display', kind: 'atom', zh: '{indicator} {operator} {threshold}' },
  { token: 'atom.strategy.time_window.name', kind: 'atom', zh: '交易时间窗口' },
  { token: 'atom.strategy.time_window.display', kind: 'atom', zh: '时间窗口 {windows} ({timezone})' },
  { token: 'atom.strategy.time_window.display.empty', kind: 'atom', zh: '时间窗口 ({timezone})' },
  { token: 'atom.position.has_position.name', kind: 'atom', zh: '已有仓位卫语句' },
  { token: 'atom.position.has_position.display', kind: 'atom', zh: '已有{side}仓位 → 阻止新开仓' },
  { token: 'atom.position.no_position.name', kind: 'atom', zh: '无仓位卫语句' },
  { token: 'atom.position.no_position.display', kind: 'atom', zh: '无{side}仓位 → 允许新开仓' },
  { token: 'atom.gate.regime.name', kind: 'atom', zh: '趋势/状态过滤' },
  { token: 'atom.gate.regime.long.display', kind: 'atom', zh: '只在价格高于 {indicator} 时允许做多' },
  { token: 'atom.gate.regime.short.display', kind: 'atom', zh: '只在价格低于 {indicator} 时允许做空' },
  { token: 'atom.gate.regime.both.display', kind: 'atom', zh: '{longLine}；{shortLine}' },
  { token: 'atom.portfolioRisk.drawdown_block.name', kind: 'atom', zh: '组合回撤护栏' },
  { token: 'atom.portfolioRisk.drawdown_block.display.enforce', kind: 'atom', zh: '账户回撤超过 {thresholdPct}% 时阻止开新仓' },
  { token: 'atom.portfolioRisk.drawdown_block.display.observe', kind: 'atom', zh: '账户回撤超过 {thresholdPct}% 时仅记录' },
  { token: 'atom.program.fixed_grid_gated.name', kind: 'atom', zh: '门控固定网格' },
  { token: 'atom.program.fixed_grid_gated.display', kind: 'atom', zh: '{range}挂 {levels} 档网格（步长 {step}%），失活时{onDeactivate}' },
  { token: 'atom.market.regime.name', kind: 'atom', zh: '市场状态' },
  { token: 'atom.volatility.state.name', kind: 'atom', zh: '波动率状态' },
  { token: 'atom.market.volatility_state.name', kind: 'atom', zh: '市场波动状态' },
  { token: 'atom.grid.price_levels.name', kind: 'atom', zh: '网格价位' },
  { token: 'atom.grid.fixed_range.name', kind: 'atom', zh: '固定区间网格' },
  { token: 'atom.grid.range_rebalance.name', kind: 'atom', zh: '网格区间再平衡' },
  { token: 'atom.open_long.name', kind: 'atom', zh: '开多' },
  { token: 'atom.open_short.name', kind: 'atom', zh: '开空' },
  { token: 'atom.close_long.name', kind: 'atom', zh: '平多' },
  { token: 'atom.close_short.name', kind: 'atom', zh: '平空' },
  { token: 'atom.close_position.name', kind: 'atom', zh: '平仓' },
  { token: 'atom.action.reduce_position.name', kind: 'atom', zh: '减仓' },
  { token: 'atom.reduce_long.name', kind: 'atom', zh: '减少多仓' },
  { token: 'atom.reduce_short.name', kind: 'atom', zh: '减少空仓' },
  { token: 'atom.action.add_position.name', kind: 'atom', zh: '加仓' },
  { token: 'atom.action.reverse_position.name', kind: 'atom', zh: '反手' },
  { token: 'atom.action.grid_ladder.name', kind: 'atom', zh: '网格阶梯下单' },
  { token: 'atom.place_limit_grid.name', kind: 'atom', zh: '挂限价网格' },
  { token: 'atom.risk.condition_expression.name', kind: 'atom', zh: '风控表达式' },
  { token: 'atom.risk.boundary_guard.name', kind: 'atom', zh: '边界风控' },
  { token: 'atom.risk.protective_exit.name', kind: 'atom', zh: '保护性退出' },
  { token: 'atom.risk.stop_loss.name', kind: 'atom', zh: '止损' },
  { token: 'atom.risk.take_profit.name', kind: 'atom', zh: '止盈' },
  { token: 'atom.risk.stop_loss_pct.name', kind: 'atom', zh: '百分比止损' },
  { token: 'atom.risk.stop_loss_pct.display', kind: 'atom', zh: '亏损 {valuePct}% 止损' },
  { token: 'atom.risk.take_profit_pct.name', kind: 'atom', zh: '百分比止盈' },
  { token: 'atom.risk.atr_multiple_stop.name', kind: 'atom', zh: 'ATR 倍数止损' },
  { token: 'atom.risk.atr_multiple_take_profit.name', kind: 'atom', zh: 'ATR 倍数止盈' },
  { token: 'atom.risk.remembered_level_stop.name', kind: 'atom', zh: '记忆价位止损' },
  { token: 'atom.risk.falling_knife_guard.name', kind: 'atom', zh: '不接急跌保护' },
  { token: 'atom.risk.trailing_stop_pct.name', kind: 'atom', zh: '百分比移动止损' },
  { token: 'atom.risk.max_drawdown_pct.name', kind: 'atom', zh: '最大回撤限制' },
  { token: 'atom.risk.max_single_loss_pct.name', kind: 'atom', zh: '单笔最大亏损' },
  { token: 'atom.risk.cooldown_bars.name', kind: 'atom', zh: '冷却 K 线数' },
  { token: 'atom.position.fixed_pct.name', kind: 'atom', zh: '固定比例仓位' },
  { token: 'atom.position.fixed_pct.display', kind: 'atom', zh: '单笔 {value}% 仓位' },
  { token: 'atom.position.fixed_notional.name', kind: 'atom', zh: '固定名义金额' },
  { token: 'atom.position.fixed_notional.display', kind: 'atom', zh: '单笔 {value} {asset}' },
  { token: 'atom.position.fixed_quantity.name', kind: 'atom', zh: '固定数量仓位' },
  { token: 'atom.position.fixed_quantity.display', kind: 'atom', zh: '单笔 {value} {asset}' },
  { token: 'atom.position.pyramiding_limit.name', kind: 'atom', zh: '金字塔加仓限制' },
  { token: 'atom.position.max_exposure_pct.name', kind: 'atom', zh: '最大敞口比例' },
  { token: 'atom.risk.partial_take_profit.name', kind: 'atom', zh: '分批止盈' },
  { token: 'atom.risk.partial_take_profit.display', kind: 'atom', zh: '分批止盈：{tiers}' },
  { token: 'atom.risk.partial_take_profit.display.empty', kind: 'atom', zh: '分批止盈' },
  { token: 'atom.position.dca_schedule.name', kind: 'atom', zh: 'DCA 补仓计划' },
  { token: 'atom.position.dca_schedule.display', kind: 'atom', zh: 'DCA 补仓计划：{parts}' },
  { token: 'atom.position.dca_schedule.display.empty', kind: 'atom', zh: 'DCA 补仓计划' },
  { token: 'atom.price.candle_pattern.name', kind: 'atom', zh: 'K 线形态' },
  { token: 'atom.price.candle_pattern.display', kind: 'atom', zh: '{direction}{pattern}形态{minBars}' },
  { token: 'atom.price.chart_pattern.name', kind: 'atom', zh: '图形形态' },
  { token: 'atom.price.chart_pattern.display', kind: 'atom', zh: '{direction}{pattern}形态' },
  { token: 'atom.liquidity.sweep.name', kind: 'atom', zh: '流动性扫荡' },
  { token: 'atom.liquidity.sweep.display', kind: 'atom', zh: '{direction}流动性扫荡 {reference}{reclaimBars}' },
  { token: 'atom.indicator.divergence.name', kind: 'atom', zh: '指标背离' },
  { token: 'atom.indicator.divergence.display', kind: 'atom', zh: '{indicator} {direction}（窗口 {pivotWindow}，确认 {confirmationBars} 根）' },
  { token: 'atom.external.signal.name', kind: 'atom', zh: '外部喊单 / Webhook 信号' },
  { token: 'atom.external.signal.display', kind: 'atom', zh: '{provider} 喊单信号' },
  { token: 'atom.price.previous_extrema.name', kind: 'atom', zh: '前高/前低（极值参考）' },
  { token: 'atom.strategy.multi_timeframe.name', kind: 'atom', zh: '多周期过滤' },
  { token: 'atom.risk.time_stop_bars.name', kind: 'atom', zh: '时间止损（K 线数）' },

  { token: 'param.label', kind: 'param', zh: '标签' },
  { token: 'param.indicator', kind: 'param', zh: '指标' },
  { token: 'param.boundaryRole', kind: 'param', zh: '边界角色' },
  { token: 'param.metric', kind: 'param', zh: '量能类型' },
  { token: 'param.operator', kind: 'param', zh: '比较方向' },
  { token: 'param.value', kind: 'param', zh: '数值' },
  { token: 'param.period', kind: 'param', zh: '周期' },
  { token: 'param.threshold', kind: 'param', zh: '阈值' },
  { token: 'param.thresholdUnit', kind: 'param', zh: '阈值单位' },
  { token: 'param.timezone', kind: 'param', zh: '时区' },
  { token: 'param.windows', kind: 'param', zh: '时间窗口' },
  { token: 'param.sideScope', kind: 'param', zh: '仓位方向范围' },
  { token: 'param.thresholdPct', kind: 'param', zh: '回撤阈值' },
  { token: 'param.mode', kind: 'param', zh: '模式' },
  { token: 'param.lowerBound', kind: 'param', zh: '下边界' },
  { token: 'param.upperBound', kind: 'param', zh: '上边界' },
  { token: 'param.anchorPrice', kind: 'param', zh: '锚定价格' },
  { token: 'param.levelCount', kind: 'param', zh: '网格档数' },
  { token: 'param.stepPct', kind: 'param', zh: '步长百分比' },
  { token: 'param.onDeactivate', kind: 'param', zh: '失活动作' },
  { token: 'param.valuePct', kind: 'param', zh: '百分比数值' },
  { token: 'param.asset', kind: 'param', zh: '资产' },
  { token: 'param.tiers', kind: 'param', zh: '止盈档位' },
  { token: 'param.maxCount', kind: 'param', zh: '最多次数' },
  { token: 'param.triggerMode', kind: 'param', zh: '触发方式' },
  { token: 'param.pattern', kind: 'param', zh: '形态' },
  { token: 'param.direction', kind: 'param', zh: '方向' },
  { token: 'param.minBars', kind: 'param', zh: '最少 K 线数' },
  { token: 'param.reference', kind: 'param', zh: '参考位' },
  { token: 'param.reclaimBars', kind: 'param', zh: '收复确认根数' },
  { token: 'param.pivotWindow', kind: 'param', zh: '枢轴窗口' },
  { token: 'param.confirmationBars', kind: 'param', zh: '确认 K 线数' },
  { token: 'param.provider', kind: 'param', zh: '信号来源' },
  { token: 'param.signalId', kind: 'param', zh: '信号订阅 ID' },
  { token: 'param.secret', kind: 'param', zh: '校验密钥' },
  { token: 'param.kind', kind: 'param', zh: '类型' },
  { token: 'param.lookback', kind: 'param', zh: '回看窗口' },
  { token: 'param.memoryKey', kind: 'param', zh: '记忆键' },

  { token: 'enum.boundaryRole.lower', kind: 'enum', zh: '下轨' },
  { token: 'enum.boundaryRole.middle', kind: 'enum', zh: '中轨' },
  { token: 'enum.boundaryRole.upper', kind: 'enum', zh: '上轨' },
  { token: 'enum.boundaryRole.boundary', kind: 'enum', zh: '边界' },
  { token: 'enum.operator.GT', kind: 'enum', zh: '大于' },
  { token: 'enum.operator.GTE', kind: 'enum', zh: '不低于' },
  { token: 'enum.operator.LT', kind: 'enum', zh: '小于' },
  { token: 'enum.operator.LTE', kind: 'enum', zh: '不高于' },
  { token: 'enum.volume.metric.base_volume', kind: 'enum', zh: '成交量' },
  { token: 'enum.volume.metric.quote_volume', kind: 'enum', zh: '成交额' },
  { token: 'enum.side.long', kind: 'enum', zh: '多头' },
  { token: 'enum.side.short', kind: 'enum', zh: '空头' },
  { token: 'enum.side.both', kind: 'enum', zh: '任意方向' },
  { token: 'enum.drawdownMode.enforce', kind: 'enum', zh: '阻止开新仓' },
  { token: 'enum.drawdownMode.observe', kind: 'enum', zh: '仅记录' },
  { token: 'enum.onDeactivate.cancel', kind: 'enum', zh: '撤单' },
  { token: 'enum.onDeactivate.keep', kind: 'enum', zh: '保留挂单' },
  { token: 'enum.onDeactivate.close', kind: 'enum', zh: '平仓' },
  { token: 'enum.indicator.ema', kind: 'enum', zh: 'EMA' },
  { token: 'enum.indicator.sma', kind: 'enum', zh: 'SMA' },
  { token: 'enum.indicator.ma', kind: 'enum', zh: 'MA' },
  { token: 'enum.dca.triggerMode.price_interval', kind: 'enum', zh: '价格间隔触发' },
  { token: 'enum.dca.triggerMode.time_interval', kind: 'enum', zh: '时间间隔触发' },
  { token: 'enum.dca.triggerMode.signal', kind: 'enum', zh: '信号触发' },
  { token: 'enum.pattern.candle.engulfing', kind: 'enum', zh: '吞没' },
  { token: 'enum.pattern.candle.hammer', kind: 'enum', zh: '锤子线' },
  { token: 'enum.pattern.candle.doji', kind: 'enum', zh: '十字星' },
  { token: 'enum.pattern.candle.consecutive_body', kind: 'enum', zh: '连续实体' },
  { token: 'enum.pattern.chart.head_and_shoulders', kind: 'enum', zh: '头肩' },
  { token: 'enum.pattern.chart.double_top', kind: 'enum', zh: '双顶' },
  { token: 'enum.pattern.chart.double_bottom', kind: 'enum', zh: '双底' },
  { token: 'enum.pattern.chart.triangle', kind: 'enum', zh: '三角形' },
  { token: 'enum.direction.bullish', kind: 'enum', zh: '看涨' },
  { token: 'enum.direction.bearish', kind: 'enum', zh: '看跌' },
  { token: 'enum.reference.prev_low', kind: 'enum', zh: '前低' },
  { token: 'enum.reference.prev_high', kind: 'enum', zh: '前高' },
  { token: 'enum.reference.session_low', kind: 'enum', zh: '日内低' },
  { token: 'enum.reference.session_high', kind: 'enum', zh: '日内高' },
  { token: 'enum.divergence.bullish', kind: 'enum', zh: '底背离' },
  { token: 'enum.divergence.bearish', kind: 'enum', zh: '顶背离' },
  { token: 'enum.provider.tradingview', kind: 'enum', zh: 'TradingView' },
  { token: 'enum.provider.discord', kind: 'enum', zh: 'Discord' },
  { token: 'enum.provider.telegram', kind: 'enum', zh: 'Telegram' },
  { token: 'enum.provider.webhook', kind: 'enum', zh: 'Webhook' },

  { token: 'slot.volume.threshold.value', kind: 'slot', zh: '成交量阈值' },
  { token: 'slot.volume.threshold.operator', kind: 'slot', zh: '成交量比较方向' },
  { token: 'slot.volume.threshold.metric', kind: 'slot', zh: '成交量类型' },
  { token: 'slot.volatility.atr_threshold.period', kind: 'slot', zh: 'ATR 计算周期' },
  { token: 'slot.volatility.atr_threshold.threshold', kind: 'slot', zh: 'ATR 阈值' },
  { token: 'slot.volatility.atr_threshold.thresholdUnit', kind: 'slot', zh: 'ATR 阈值单位' },
  { token: 'slot.volatility.atr_threshold.operator', kind: 'slot', zh: 'ATR 比较方向' },
  { token: 'slot.strategy.time_window.timezone', kind: 'slot', zh: '交易时区' },
  { token: 'slot.strategy.time_window.windows', kind: 'slot', zh: '允许交易时间段' },
  { token: 'slot.position.has_position.sideScope', kind: 'slot', zh: '已有仓位方向' },
  { token: 'slot.position.no_position.sideScope', kind: 'slot', zh: '无仓位方向' },
  { token: 'slot.position.dca_schedule.max_count', kind: 'slot', zh: 'DCA 最多执行次数' },
  { token: 'slot.position.dca_schedule.capital_cap', kind: 'slot', zh: 'DCA 总资金上限' },
  { token: 'slot.position.dca_schedule.per_order_sizing', kind: 'slot', zh: 'DCA 每次补仓大小' },
  { token: 'slot.position.dca_schedule.trigger_mode', kind: 'slot', zh: 'DCA 触发方式' },
  { token: 'slot.position.dca_schedule.exit_rule', kind: 'slot', zh: 'DCA 停止规则' },
  { token: 'slot.price.candle_pattern.pattern', kind: 'slot', zh: 'K 线形态类型' },
  { token: 'slot.price.candle_pattern.direction', kind: 'slot', zh: 'K 线形态方向' },
  { token: 'slot.price.candle_pattern.minBars', kind: 'slot', zh: '连续实体最少根数' },
  { token: 'slot.price.chart_pattern.pattern', kind: 'slot', zh: '图形形态类型' },
  { token: 'slot.price.chart_pattern.direction', kind: 'slot', zh: '图形形态方向' },
  { token: 'slot.liquidity.sweep.direction', kind: 'slot', zh: '扫荡反转方向' },
  { token: 'slot.liquidity.sweep.reference', kind: 'slot', zh: '被扫荡关键位' },
  { token: 'slot.liquidity.sweep.reclaimBars', kind: 'slot', zh: '收复确认根数' },
  { token: 'slot.indicator.divergence.indicator', kind: 'slot', zh: '背离指标' },
  { token: 'slot.indicator.divergence.direction', kind: 'slot', zh: '背离方向' },
  { token: 'slot.indicator.divergence.pivotWindow', kind: 'slot', zh: '背离滚动窗口' },
  { token: 'slot.indicator.divergence.confirmationBars', kind: 'slot', zh: '背离确认 K 线数' },
  { token: 'slot.external.signal.provider', kind: 'slot', zh: '外部信号来源' },
  { token: 'slot.external.signal.signalId', kind: 'slot', zh: '外部信号订阅 ID' },
  { token: 'slot.external.signal.secret', kind: 'slot', zh: '外部信号校验密钥' },
  { token: 'slot.orchestration.gate.regime.active_when', kind: 'slot', zh: '趋势过滤启用条件' },
  { token: 'slot.orchestration.portfolio_drawdown.threshold_pct', kind: 'slot', zh: '组合回撤百分比阈值' },
  { token: 'slot.orchestration.program.fixed_grid_gated.gridParams', kind: 'slot', zh: '网格区间、档数、步长' },
  { token: 'slot.orchestration.program.fixed_grid_gated.activeWhenRef', kind: 'slot', zh: '网格启用/失活条件引用' },
  { token: 'slot.orchestration.program.fixed_grid_gated.sizing', kind: 'slot', zh: '每档下单数量' },

  // Phase 5 S2 (#1104): scope.symbol substrate
  { token: 'atom.scope.symbol.name', kind: 'atom', zh: '标的范围' },
  { token: 'atom.scope.symbol.display.with_primary', kind: 'atom', zh: '标的范围：{symbols}（主：{primarySymbol}）' },
  { token: 'atom.scope.symbol.display.no_primary', kind: 'atom', zh: '标的范围：{symbols}' },
  { token: 'param.symbols', kind: 'param', zh: '标的列表' },
  { token: 'param.primarySymbol', kind: 'param', zh: '主标的' },
  { token: 'slot.orchestration.scope.symbol.symbols', kind: 'slot', zh: '请确认要绑定的标的列表' },
  { token: 'slot.orchestration.scope.symbol.primary_symbol', kind: 'slot', zh: '主标的必须在标的列表中' },
  { token: 'slot.orchestration.scope.symbol.symbols_overlap', kind: 'slot', zh: '多 scope 之间标的不能重叠' },
  { token: 'slot.orchestration.scope.symbol.primary_symbol_collision', kind: 'slot', zh: '多 scope 主标的必须各自唯一' },
  { token: 'slot.orchestration.scope.symbol.missing_binding', kind: 'slot', zh: '请确认该规则绑定到哪个 symbol scope' },
  { token: 'slot.orchestration.scope.unsupported_kind', kind: 'slot', zh: '当前仅支持 scope.symbol 与 scope.dataSource' },

  // Phase 5 S11 (#1112): scope.leg substrate
  { token: 'atom.scope.leg.name', kind: 'atom', zh: '策略腿' },
  { token: 'atom.scope.leg.display.long', kind: 'atom', zh: '多头腿（{instrument}）' },
  { token: 'atom.scope.leg.display.short', kind: 'atom', zh: '空头腿（{instrument}）' },
  { token: 'atom.scope.leg.display.hedge', kind: 'atom', zh: '对冲组合：{legs}' },
  { token: 'param.legId', kind: 'param', zh: '腿标识' },
  { token: 'param.direction', kind: 'param', zh: '腿方向' },
  { token: 'slot.orchestration.scope.leg.unsupported_kind', kind: 'slot', zh: '当前仅支持 scope.leg 子类型' },
  { token: 'slot.orchestration.scope.leg.leg_scope_kind', kind: 'slot', zh: '请确认 legScopeKind 为 leg' },
  { token: 'slot.orchestration.scope.leg.leg_id', kind: 'slot', zh: '请确认腿 id（字母开头、字母数字下划线点、长度 ≤ 64）' },
  { token: 'slot.orchestration.scope.leg.direction', kind: 'slot', zh: '请确认腿方向（long/short）' },
  { token: 'slot.orchestration.scope.leg.instrument_ref', kind: 'slot', zh: '该腿引用的 scope.symbol 节点必须已存在且 readiness 已通过' },
  { token: 'slot.orchestration.scope.leg.leg_sizing.mode', kind: 'slot', zh: '请确认 legSizing.mode（fixed_pct/fixed_quote/fixed_ratio）' },
  { token: 'slot.orchestration.scope.leg.leg_sizing.value', kind: 'slot', zh: '请确认 legSizing.value（>0 有限数）' },
  { token: 'slot.orchestration.scope.leg.paired_leg_id', kind: 'slot', zh: 'fixed_ratio 模式必须指定 pairedLegId' },
  { token: 'slot.orchestration.scope.leg.direction_collision', kind: 'slot', zh: 'paired leg 必须方向相反（对冲腿）' },
  { token: 'slot.orchestration.scope.leg.missing_binding', kind: 'slot', zh: '请确认该规则绑定到哪个策略腿' },
  { token: 'slot.orchestration.scope.unsupported_kind', kind: 'slot', zh: '当前仅支持 scope.symbol / scope.leg / scope.timeframe / scope.dataSource' },

  // Phase 5 S3 (#1109): scope.timeframe substrate
  { token: 'atom.scope.timeframe.name', kind: 'atom', zh: '周期范围' },
  { token: 'atom.scope.timeframe.display.with_required', kind: 'atom', zh: '周期范围：主 {primaryTimeframe}，依赖 {requiredTimeframes}（{alignmentPolicy}）' },
  { token: 'param.primaryTimeframe', kind: 'param', zh: '执行周期（主周期）' },
  { token: 'param.requiredTimeframes', kind: 'param', zh: '依赖周期列表' },
  { token: 'param.alignmentPolicy', kind: 'param', zh: '对齐严格度' },
  { token: 'slot.orchestration.scope.timeframe.primary_timeframe', kind: 'slot', zh: '请确认执行周期（主周期）' },
  { token: 'slot.orchestration.scope.timeframe.required_timeframes', kind: 'slot', zh: '请确认依赖周期列表（≥1 个，且与主周期不同）' },
  { token: 'slot.orchestration.scope.timeframe.required_length', kind: 'slot', zh: '依赖周期数量必须在 1..8 之间' },
  { token: 'slot.orchestration.scope.timeframe.primary_granularity', kind: 'slot', zh: '主周期粒度必须严格细于所有依赖周期' },
  { token: 'slot.orchestration.scope.timeframe.alignment_policy', kind: 'slot', zh: '请确认对齐严格度（strict / tolerant）' },
  { token: 'slot.orchestration.scope.timeframe.duplicate_definition', kind: 'slot', zh: '多 scope.timeframe 之间 (主周期, 依赖周期集合) 不能完全相同' },
  { token: 'slot.orchestration.scope.timeframe.missing_binding', kind: 'slot', zh: '请确认该规则绑定到哪个 timeframe scope（必须显式声明）' },
  { token: 'slot.orchestration.scope.timeframe.unsupported_key', kind: 'slot', zh: '当前仅支持 scope.timeframe' },
  { token: 'slot.orchestration.scope.timeframe.scope_kind', kind: 'slot', zh: '请确认 scopeKind 为 timeframe' },

  // Phase 5 S9 (#1110): scope.dataSource substrate
  { token: 'atom.scope.dataSource.name', kind: 'atom', zh: '数据源' },
  { token: 'atom.scope.dataSource.display', kind: 'atom', zh: '数据源：{role}（{feedId} / {schema}）' },
  { token: 'param.role', kind: 'param', zh: '数据源角色' },
  { token: 'param.feedId', kind: 'param', zh: '数据源 feedId' },
  { token: 'param.schema', kind: 'param', zh: '数据源 schema' },
  { token: 'slot.orchestration.scope.dataSource.role', kind: 'slot', zh: '请确认数据源角色（primary/confirmation/event）' },
  { token: 'slot.orchestration.scope.dataSource.feed_id', kind: 'slot', zh: '请确认数据源 feedId（如 binance.spot.btcusdt）' },
  { token: 'slot.orchestration.scope.dataSource.schema_ref', kind: 'slot', zh: '请确认数据源 schema（ohlcv/orderbook/liquidation/webhook_event）' },
  { token: 'slot.orchestration.scope.dataSource.feed_id_overlap', kind: 'slot', zh: '多 scope 间 feedId 不能重复' },
  { token: 'slot.orchestration.scope.dataSource.primary_collision', kind: 'slot', zh: 'primary 数据源最多一个' },
  { token: 'slot.orchestration.scope.dataSource.missing_binding', kind: 'slot', zh: '请确认该规则绑定到哪个 dataSource scope' },
  { token: 'slot.orchestration.scope.dataSource.scope_kind', kind: 'slot', zh: '请确认 scopeKind 为 dataSource' },
] as const satisfies readonly DisplayToken[]
