import type { DisplayToken } from './display-token.types'

export const DISPLAY_TOKENS = [
  { token: 'atom.condition.expression.name', kind: 'atom', zh: '表达式条件' },
  { token: 'atom.condition.expression.display', kind: 'atom', zh: '{label}' },
  { token: 'atom.price.detect.indicator_boundary.name', kind: 'atom', zh: '价格触及指标边界' },
  { token: 'atom.indicator.boundary_touch.name', kind: 'atom', zh: '指标边界触及' },
  { token: 'atom.indicator_boundary_touch.display', kind: 'atom', zh: '触及 {indicator} {boundaryRole}{settings}' },
  { token: 'atom.volume.threshold.name', kind: 'atom', zh: '成交量阈值' },
  { token: 'atom.volume.threshold.display', kind: 'atom', zh: '{metric} {operator} {value}' },
  { token: 'atom.volatility.atr_threshold.name', kind: 'atom', zh: 'ATR 波动率阈值' },
  { token: 'atom.volatility.atr_threshold.display', kind: 'atom', zh: '{indicator} {operator} {threshold}' },
  { token: 'atom.strategy.time_window.name', kind: 'atom', zh: '交易时间窗口' },
  { token: 'atom.strategy.time_window.display', kind: 'atom', zh: '时间窗口 {windows} ({timezone})' },
  { token: 'atom.strategy.time_window.display.empty', kind: 'atom', zh: '时间窗口 ({timezone})' },
  { token: 'atom.position.has_position.name', kind: 'atom', zh: '已有仓位卫语句' },
  { token: 'atom.position.has_position.display', kind: 'atom', zh: '已有{side}仓位 → 阻止新开仓' },
  { token: 'atom.position.no_position.name', kind: 'atom', zh: '无仓位卫语句' },
  { token: 'atom.position.no_position.display', kind: 'atom', zh: '无{side}仓位 → 允许新开仓' },
  { token: 'atom.gate.regime.name', kind: 'atom', zh: '趋势/状态过滤' },
  { token: 'atom.gate.regime.long.display', kind: 'atom', zh: '只在价格高于 {indicator} 时允许做多' },
  { token: 'atom.gate.regime.short.display', kind: 'atom', zh: '只在价格低于 {indicator} 时允许做空' },
  { token: 'atom.gate.regime.both.display', kind: 'atom', zh: '{longLine}；{shortLine}' },
  { token: 'atom.portfolioRisk.drawdown_block.name', kind: 'atom', zh: '组合回撤护栏' },
  { token: 'atom.portfolioRisk.drawdown_block.display.enforce', kind: 'atom', zh: '账户回撤超过 {thresholdPct}% 时阻止开新仓' },
  { token: 'atom.portfolioRisk.drawdown_block.display.observe', kind: 'atom', zh: '账户回撤超过 {thresholdPct}% 时仅记录' },
  { token: 'atom.program.fixed_grid_gated.name', kind: 'atom', zh: '门控固定网格' },
  { token: 'atom.program.fixed_grid_gated.display', kind: 'atom', zh: '{range}挂 {levels} 档网格（步长 {step}%），失活时{onDeactivate}' },
  { token: 'atom.open_long.name', kind: 'atom', zh: '开多' },
  { token: 'atom.open_short.name', kind: 'atom', zh: '开空' },
  { token: 'atom.risk.stop_loss_pct.name', kind: 'atom', zh: '百分比止损' },
  { token: 'atom.risk.stop_loss_pct.display', kind: 'atom', zh: '亏损 {valuePct}% 止损' },
  { token: 'atom.position.fixed_pct.name', kind: 'atom', zh: '固定比例仓位' },
  { token: 'atom.position.fixed_pct.display', kind: 'atom', zh: '单笔 {value}% 仓位' },
  { token: 'atom.position.fixed_notional.name', kind: 'atom', zh: '固定名义金额' },
  { token: 'atom.position.fixed_notional.display', kind: 'atom', zh: '单笔 {value} {asset}' },
  { token: 'atom.position.fixed_quantity.name', kind: 'atom', zh: '固定数量仓位' },
  { token: 'atom.position.fixed_quantity.display', kind: 'atom', zh: '单笔 {value} {asset}' },
  { token: 'atom.risk.partial_take_profit.name', kind: 'atom', zh: '分批止盈' },
  { token: 'atom.risk.partial_take_profit.display', kind: 'atom', zh: '分批止盈：{tiers}' },
  { token: 'atom.risk.partial_take_profit.display.empty', kind: 'atom', zh: '分批止盈' },
  { token: 'atom.position.dca_schedule.name', kind: 'atom', zh: 'DCA 补仓计划' },
  { token: 'atom.position.dca_schedule.display', kind: 'atom', zh: 'DCA 补仓计划：{parts}' },
  { token: 'atom.position.dca_schedule.display.empty', kind: 'atom', zh: 'DCA 补仓计划' },
  { token: 'atom.price.candle_pattern.name', kind: 'atom', zh: 'K 线形态' },
  { token: 'atom.price.candle_pattern.display', kind: 'atom', zh: '{direction}{pattern}形态{minBars}' },
  { token: 'atom.price.chart_pattern.name', kind: 'atom', zh: '图形形态' },
  { token: 'atom.price.chart_pattern.display', kind: 'atom', zh: '{direction}{pattern}形态' },
  { token: 'atom.liquidity.sweep.name', kind: 'atom', zh: '流动性扫荡' },
  { token: 'atom.liquidity.sweep.display', kind: 'atom', zh: '{direction}流动性扫荡 {reference}{reclaimBars}' },
  { token: 'atom.indicator.divergence.name', kind: 'atom', zh: '指标背离' },
  { token: 'atom.indicator.divergence.display', kind: 'atom', zh: '{indicator} {direction}（窗口 {pivotWindow}，确认 {confirmationBars} 根）' },
  { token: 'atom.external.signal.name', kind: 'atom', zh: '外部喊单 / Webhook 信号' },
  { token: 'atom.external.signal.display', kind: 'atom', zh: '{provider} 喊单信号' },
  { token: 'atom.price.previous_extrema.name', kind: 'atom', zh: '前高/前低（极值参考）' },
  { token: 'atom.strategy.multi_timeframe.name', kind: 'atom', zh: '多周期过滤' },
  { token: 'atom.risk.time_stop_bars.name', kind: 'atom', zh: '时间止损（K 线数）' },

  { token: 'param.label', kind: 'param', zh: '标签' },
  { token: 'param.indicator', kind: 'param', zh: '指标' },
  { token: 'param.boundaryRole', kind: 'param', zh: '边界角色' },
  { token: 'param.metric', kind: 'param', zh: '量能类型' },
  { token: 'param.operator', kind: 'param', zh: '比较方向' },
  { token: 'param.value', kind: 'param', zh: '数值' },
  { token: 'param.period', kind: 'param', zh: '周期' },
  { token: 'param.threshold', kind: 'param', zh: '阈值' },
  { token: 'param.thresholdUnit', kind: 'param', zh: '阈值单位' },
  { token: 'param.timezone', kind: 'param', zh: '时区' },
  { token: 'param.windows', kind: 'param', zh: '时间窗口' },
  { token: 'param.sideScope', kind: 'param', zh: '仓位方向范围' },
  { token: 'param.thresholdPct', kind: 'param', zh: '回撤阈值' },
  { token: 'param.mode', kind: 'param', zh: '模式' },
  { token: 'param.lowerBound', kind: 'param', zh: '下边界' },
  { token: 'param.upperBound', kind: 'param', zh: '上边界' },
  { token: 'param.anchorPrice', kind: 'param', zh: '锚定价格' },
  { token: 'param.levelCount', kind: 'param', zh: '网格档数' },
  { token: 'param.stepPct', kind: 'param', zh: '步长百分比' },
  { token: 'param.onDeactivate', kind: 'param', zh: '失活动作' },
  { token: 'param.valuePct', kind: 'param', zh: '百分比数值' },
  { token: 'param.asset', kind: 'param', zh: '资产' },
  { token: 'param.tiers', kind: 'param', zh: '止盈档位' },
  { token: 'param.maxCount', kind: 'param', zh: '最多次数' },
  { token: 'param.triggerMode', kind: 'param', zh: '触发方式' },
  { token: 'param.pattern', kind: 'param', zh: '形态' },
  { token: 'param.direction', kind: 'param', zh: '方向' },
  { token: 'param.minBars', kind: 'param', zh: '最少 K 线数' },
  { token: 'param.reference', kind: 'param', zh: '参考位' },
  { token: 'param.reclaimBars', kind: 'param', zh: '收复确认根数' },
  { token: 'param.pivotWindow', kind: 'param', zh: '枢轴窗口' },
  { token: 'param.confirmationBars', kind: 'param', zh: '确认 K 线数' },
  { token: 'param.provider', kind: 'param', zh: '信号来源' },
  { token: 'param.signalId', kind: 'param', zh: '信号订阅 ID' },
  { token: 'param.secret', kind: 'param', zh: '校验密钥' },
  { token: 'param.kind', kind: 'param', zh: '类型' },
  { token: 'param.lookback', kind: 'param', zh: '回看窗口' },
  { token: 'param.memoryKey', kind: 'param', zh: '记忆键' },

  { token: 'enum.boundaryRole.lower', kind: 'enum', zh: '下轨' },
  { token: 'enum.boundaryRole.middle', kind: 'enum', zh: '中轨' },
  { token: 'enum.boundaryRole.upper', kind: 'enum', zh: '上轨' },
  { token: 'enum.boundaryRole.boundary', kind: 'enum', zh: '边界' },
  { token: 'enum.operator.GT', kind: 'enum', zh: '大于' },
  { token: 'enum.operator.GTE', kind: 'enum', zh: '不低于' },
  { token: 'enum.operator.LT', kind: 'enum', zh: '小于' },
  { token: 'enum.operator.LTE', kind: 'enum', zh: '不高于' },
  { token: 'enum.volume.metric.base_volume', kind: 'enum', zh: '成交量' },
  { token: 'enum.volume.metric.quote_volume', kind: 'enum', zh: '成交额' },
  { token: 'enum.side.long', kind: 'enum', zh: '多头' },
  { token: 'enum.side.short', kind: 'enum', zh: '空头' },
  { token: 'enum.side.both', kind: 'enum', zh: '任意方向' },
  { token: 'enum.drawdownMode.enforce', kind: 'enum', zh: '阻止开新仓' },
  { token: 'enum.drawdownMode.observe', kind: 'enum', zh: '仅记录' },
  { token: 'enum.onDeactivate.cancel', kind: 'enum', zh: '撤单' },
  { token: 'enum.onDeactivate.keep', kind: 'enum', zh: '保留挂单' },
  { token: 'enum.onDeactivate.close', kind: 'enum', zh: '平仓' },
  { token: 'enum.indicator.ema', kind: 'enum', zh: 'EMA' },
  { token: 'enum.indicator.sma', kind: 'enum', zh: 'SMA' },
  { token: 'enum.indicator.ma', kind: 'enum', zh: 'MA' },
  { token: 'enum.dca.triggerMode.price_interval', kind: 'enum', zh: '价格间隔触发' },
  { token: 'enum.dca.triggerMode.time_interval', kind: 'enum', zh: '时间间隔触发' },
  { token: 'enum.dca.triggerMode.signal', kind: 'enum', zh: '信号触发' },
  { token: 'enum.pattern.candle.engulfing', kind: 'enum', zh: '吞没' },
  { token: 'enum.pattern.candle.hammer', kind: 'enum', zh: '锤子线' },
  { token: 'enum.pattern.candle.doji', kind: 'enum', zh: '十字星' },
  { token: 'enum.pattern.candle.consecutive_body', kind: 'enum', zh: '连续实体' },
  { token: 'enum.pattern.chart.head_and_shoulders', kind: 'enum', zh: '头肩' },
  { token: 'enum.pattern.chart.double_top', kind: 'enum', zh: '双顶' },
  { token: 'enum.pattern.chart.double_bottom', kind: 'enum', zh: '双底' },
  { token: 'enum.pattern.chart.triangle', kind: 'enum', zh: '三角形' },
  { token: 'enum.direction.bullish', kind: 'enum', zh: '看涨' },
  { token: 'enum.direction.bearish', kind: 'enum', zh: '看跌' },
  { token: 'enum.reference.prev_low', kind: 'enum', zh: '前低' },
  { token: 'enum.reference.prev_high', kind: 'enum', zh: '前高' },
  { token: 'enum.reference.session_low', kind: 'enum', zh: '日内低' },
  { token: 'enum.reference.session_high', kind: 'enum', zh: '日内高' },
  { token: 'enum.divergence.bullish', kind: 'enum', zh: '底背离' },
  { token: 'enum.divergence.bearish', kind: 'enum', zh: '顶背离' },
  { token: 'enum.provider.tradingview', kind: 'enum', zh: 'TradingView' },
  { token: 'enum.provider.discord', kind: 'enum', zh: 'Discord' },
  { token: 'enum.provider.telegram', kind: 'enum', zh: 'Telegram' },
  { token: 'enum.provider.webhook', kind: 'enum', zh: 'Webhook' },

  { token: 'slot.volume.threshold.value', kind: 'slot', zh: '成交量阈值' },
  { token: 'slot.volume.threshold.operator', kind: 'slot', zh: '成交量比较方向' },
  { token: 'slot.volume.threshold.metric', kind: 'slot', zh: '成交量类型' },
  { token: 'slot.volatility.atr_threshold.period', kind: 'slot', zh: 'ATR 计算周期' },
  { token: 'slot.volatility.atr_threshold.threshold', kind: 'slot', zh: 'ATR 阈值' },
  { token: 'slot.volatility.atr_threshold.thresholdUnit', kind: 'slot', zh: 'ATR 阈值单位' },
  { token: 'slot.volatility.atr_threshold.operator', kind: 'slot', zh: 'ATR 比较方向' },
  { token: 'slot.strategy.time_window.timezone', kind: 'slot', zh: '交易时区' },
  { token: 'slot.strategy.time_window.windows', kind: 'slot', zh: '允许交易时间段' },
  { token: 'slot.position.has_position.sideScope', kind: 'slot', zh: '已有仓位方向' },
  { token: 'slot.position.no_position.sideScope', kind: 'slot', zh: '无仓位方向' },
  { token: 'slot.position.dca_schedule.max_count', kind: 'slot', zh: 'DCA 最多执行次数' },
  { token: 'slot.position.dca_schedule.capital_cap', kind: 'slot', zh: 'DCA 总资金上限' },
  { token: 'slot.position.dca_schedule.per_order_sizing', kind: 'slot', zh: 'DCA 每次补仓大小' },
  { token: 'slot.position.dca_schedule.trigger_mode', kind: 'slot', zh: 'DCA 触发方式' },
  { token: 'slot.position.dca_schedule.exit_rule', kind: 'slot', zh: 'DCA 停止规则' },
  { token: 'slot.price.candle_pattern.pattern', kind: 'slot', zh: 'K 线形态类型' },
  { token: 'slot.price.candle_pattern.direction', kind: 'slot', zh: 'K 线形态方向' },
  { token: 'slot.price.candle_pattern.minBars', kind: 'slot', zh: '连续实体最少根数' },
  { token: 'slot.price.chart_pattern.pattern', kind: 'slot', zh: '图形形态类型' },
  { token: 'slot.price.chart_pattern.direction', kind: 'slot', zh: '图形形态方向' },
  { token: 'slot.liquidity.sweep.direction', kind: 'slot', zh: '扫荡反转方向' },
  { token: 'slot.liquidity.sweep.reference', kind: 'slot', zh: '被扫荡关键位' },
  { token: 'slot.liquidity.sweep.reclaimBars', kind: 'slot', zh: '收复确认根数' },
  { token: 'slot.indicator.divergence.indicator', kind: 'slot', zh: '背离指标' },
  { token: 'slot.indicator.divergence.direction', kind: 'slot', zh: '背离方向' },
  { token: 'slot.indicator.divergence.pivotWindow', kind: 'slot', zh: '背离滚动窗口' },
  { token: 'slot.indicator.divergence.confirmationBars', kind: 'slot', zh: '背离确认 K 线数' },
  { token: 'slot.external.signal.provider', kind: 'slot', zh: '外部信号来源' },
  { token: 'slot.external.signal.signalId', kind: 'slot', zh: '外部信号订阅 ID' },
  { token: 'slot.external.signal.secret', kind: 'slot', zh: '外部信号校验密钥' },
  { token: 'slot.orchestration.gate.regime.active_when', kind: 'slot', zh: '趋势过滤启用条件' },
  { token: 'slot.orchestration.portfolio_drawdown.threshold_pct', kind: 'slot', zh: '组合回撤百分比阈值' },
  { token: 'slot.orchestration.program.fixed_grid_gated.gridParams', kind: 'slot', zh: '网格区间、档数、步长' },
  { token: 'slot.orchestration.program.fixed_grid_gated.activeWhenRef', kind: 'slot', zh: '网格启用/失活条件引用' },
  { token: 'slot.orchestration.program.fixed_grid_gated.sizing', kind: 'slot', zh: '每档下单数量' },
] as const satisfies readonly DisplayToken[]
