import type { Staging30RulesOnlyCase } from './staging30-rules-only-mainflow-cases'
import { STAGING30_RULES_ONLY_CASES } from './staging30-rules-only-mainflow-cases'

export interface Staging30EvidenceHashes {
  rulesHash: string
  canonicalSpecHash: string
  irHash: string
  astHash: string
  scriptHash: string
  runtimeEvaluatorVersion: string
}

export interface Staging30CaseEvidence {
  caseId: string
  status: 'passed' | 'failed'
  hashes: Staging30EvidenceHashes | null
  usedFlatFallback: boolean
  steps: string[]
  failureReason: string | null
}

export interface Staging30EvidenceSummary {
  passed: boolean
  total: number
  passedCount: number
  failedCaseIds: string[]
  failures: string[]
}

function hasCompleteHashes(hashes: Staging30EvidenceHashes | null): hashes is Staging30EvidenceHashes {
  if (!hashes) return false
  return [
    hashes.rulesHash,
    hashes.canonicalSpecHash,
    hashes.irHash,
    hashes.astHash,
    hashes.scriptHash,
    hashes.runtimeEvaluatorVersion,
  ].every(value => typeof value === 'string' && value.trim().length > 0)
}

function failureForEvidence(item: Staging30CaseEvidence): string | null {
  if (item.status !== 'passed') return item.failureReason ?? 'case failed'
  if (item.usedFlatFallback) return item.failureReason ?? 'flat fallback observed'
  if (!hasCompleteHashes(item.hashes)) return item.failureReason ?? 'hashes incomplete'
  return null
}

export function buildStaging30EvidenceSummary(cases: readonly Staging30CaseEvidence[]): Staging30EvidenceSummary {
  const failed = cases
    .map(item => ({ item, reason: failureForEvidence(item) }))
    .filter((entry): entry is { item: Staging30CaseEvidence, reason: string } => entry.reason !== null)

  return {
    passed: failed.length === 0 && cases.length === STAGING30_RULES_ONLY_CASES.length,
    total: cases.length,
    passedCount: cases.length - failed.length,
    failedCaseIds: failed.map(entry => entry.item.caseId),
    failures: failed.map(entry => `${entry.item.caseId}: ${entry.reason}`),
  }
}

async function postJson<T>(apiBaseUrl: string, authToken: string, path: string, body: unknown): Promise<T> {
  const response = await fetch(`${apiBaseUrl}${path}`, {
    method: 'POST',
    headers: {
      authorization: `Bearer ${authToken}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify(body),
  })

  if (!response.ok) {
    throw new Error(`HTTP ${response.status} ${path}: ${await response.text()}`)
  }

  return await response.json() as T
}

async function getJson<T>(apiBaseUrl: string, authToken: string, path: string): Promise<T> {
  const response = await fetch(`${apiBaseUrl}${path}`, {
    method: 'GET',
    headers: { authorization: `Bearer ${authToken}` },
  })

  if (!response.ok) {
    throw new Error(`HTTP ${response.status} ${path}: ${await response.text()}`)
  }

  return await response.json() as T
}

async function sleep(ms: number): Promise<void> {
  await new Promise(resolve => setTimeout(resolve, ms))
}

function readRecord(value: unknown): Record<string, unknown> | null {
  if (!value || typeof value !== 'object') return null
  if (Array.isArray(value)) return null
  return value as Record<string, unknown>
}

function readRuntimeEvaluatorVersion(response: Record<string, unknown>): string {
  const scriptCode = typeof response.scriptCode === 'string'
    ? response.scriptCode
    : typeof response.script === 'string'
      ? response.script
      : ''
  const header = /^\/\* @generated by (?<version>[^*]+) \*\//u.exec(scriptCode)
  return header?.groups?.version.trim() ?? ''
}

function readHashes(value: unknown, runtimeEvaluatorVersion: string): Staging30EvidenceHashes | null {
  const record = readRecord(value)
  if (!record) return null
  const hashes = record.hashes && typeof record.hashes === 'object'
    ? record.hashes as Record<string, unknown>
    : record
  const result = {
    rulesHash: typeof hashes.rulesHash === 'string' ? hashes.rulesHash : '',
    canonicalSpecHash: typeof hashes.canonicalSpecHash === 'string' ? hashes.canonicalSpecHash : '',
    irHash: typeof hashes.irHash === 'string' ? hashes.irHash : '',
    astHash: typeof hashes.astHash === 'string' ? hashes.astHash : '',
    scriptHash: typeof hashes.scriptHash === 'string' ? hashes.scriptHash : '',
    runtimeEvaluatorVersion,
  }
  return hasCompleteHashes(result) ? result : null
}

export function extractStaging30HashesFromResponse(response: Record<string, unknown>): Staging30EvidenceHashes | null {
  const runtimeEvaluatorVersion = readRuntimeEvaluatorVersion(response)
  const specDesc = readRecord(response.specDesc)
  const candidates = [
    specDesc?.rulesOnlyHashChain,
  ]

  for (const candidate of candidates) {
    const hashes = readHashes(candidate, runtimeEvaluatorVersion)
    if (hashes) return hashes
  }

  return null
}

async function pollPublishedSession(apiBaseUrl: string, authToken: string, sessionId: string): Promise<Record<string, unknown>> {
  const maxAttempts = 90
  const intervalMs = 2000
  const terminalFailureStatuses = new Set(['CONSISTENCY_FAILED', 'REJECTED'])

  for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
    const session = await getJson<Record<string, unknown>>(apiBaseUrl, authToken, `/llm-strategy-codegen/sessions/${sessionId}`)
    const status = typeof session.status === 'string' ? session.status : 'UNKNOWN'
    if (status === 'PUBLISHED') return session
    if (terminalFailureStatuses.has(status)) {
      throw new Error(`session terminal status: ${status}`)
    }
    await sleep(intervalMs)
  }

  throw new Error('session publish polling timed out')
}

async function runCase(apiBaseUrl: string, authToken: string, item: Staging30RulesOnlyCase): Promise<Staging30CaseEvidence> {
  const session = await postJson<{ id: string }>(apiBaseUrl, authToken, '/llm-strategy-codegen/sessions', {
    initialMessage: item.prompt,
    locale: 'zh',
  })
  await postJson<Record<string, unknown>>(
    apiBaseUrl,
    authToken,
    `/llm-strategy-codegen/sessions/${session.id}/messages`,
    { message: '确认，生成脚本并发布。', confirmGenerate: true, locale: 'zh' },
  )
  const publishedSession = await pollPublishedSession(apiBaseUrl, authToken, session.id)
  const hashes = extractStaging30HashesFromResponse(publishedSession)
  const usedFlatFallback = JSON.stringify(publishedSession).includes('flatFallback')

  return {
    caseId: item.id,
    status: hashes && !usedFlatFallback ? 'passed' : 'failed',
    hashes,
    usedFlatFallback,
    steps: ['session', 'confirmGenerate', 'pollPublishedSession', 'publish'],
    failureReason: hashes ? null : 'rulesOnlyHashChain missing',
  }
}

async function runAllCases(apiBaseUrl: string, authToken: string): Promise<Staging30EvidenceSummary> {
  const evidence: Staging30CaseEvidence[] = []
  for (const item of STAGING30_RULES_ONLY_CASES) {
    try {
      evidence.push(await runCase(apiBaseUrl, authToken, item))
    } catch (error) {
      evidence.push({
        caseId: item.id,
        status: 'failed',
        hashes: null,
        usedFlatFallback: false,
        steps: ['session'],
        failureReason: error instanceof Error ? error.message : String(error),
      })
    }
  }
  return buildStaging30EvidenceSummary(evidence)
}

async function main(): Promise<void> {
  const apiBaseUrl = process.env.QUANTIFY_STAGING_API_BASE_URL?.trim()
  const authToken = process.env.QUANTIFY_STAGING_AUTH_TOKEN?.trim()
  if (!apiBaseUrl || !authToken) {
    console.error(JSON.stringify({
      passed: false,
      reason: 'staging_env_missing',
      requiredEnv: ['QUANTIFY_STAGING_API_BASE_URL', 'QUANTIFY_STAGING_AUTH_TOKEN'],
    }, null, 2))
    process.exitCode = 1
    return
  }

  const summary = await runAllCases(apiBaseUrl.replace(/\/+$/u, ''), authToken)
  console.log(JSON.stringify(summary, null, 2))
  process.exitCode = summary.passed ? 0 : 1
}

if (require.main === module) {
  void main().catch((error) => {
    console.error(JSON.stringify({
      passed: false,
      reason: error instanceof Error ? error.message : String(error),
    }, null, 2))
    process.exitCode = 1
  })
}
