/**
 * 统一错误码枚举
 * 前后端共用
 */
export enum ErrorCode {
  // ===== Settings 模块 (10000-10099) =====
  SETTINGS_INVALID_JSON = 'SETTINGS_INVALID_JSON',
  SETTINGS_TYPE_MISMATCH = 'SETTINGS_TYPE_MISMATCH',
  SETTINGS_JSON_EXPECTED_OBJECT_OR_ARRAY = 'SETTINGS_JSON_EXPECTED_OBJECT_OR_ARRAY',
  SETTINGS_NOT_FOUND = 'SETTINGS_NOT_FOUND',

  // ===== 通用错误 =====
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  DATA_CONSISTENCY_ERROR = 'DATA_CONSISTENCY_ERROR',

  // ===== 邮件/通知 =====
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',

  // ===== Auth 模块 =====
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_TAKEN = 'AUTH_EMAIL_ALREADY_TAKEN',
  AUTH_VERIFICATION_CODE_INVALID = 'AUTH_VERIFICATION_CODE_INVALID',
  AUTH_VERIFICATION_CODE_EXPIRED = 'AUTH_VERIFICATION_CODE_EXPIRED',
  AUTH_PASSWORD_RESET_INVALID = 'AUTH_PASSWORD_RESET_INVALID',

  // ===== Market Data 模块 =====
  MARKET_SYMBOL_NOT_FOUND = 'MARKET_SYMBOL_NOT_FOUND',
  MARKET_INVALID_TIMEFRAME = 'MARKET_INVALID_TIMEFRAME',
  MARKET_DATA_PROVIDER_ERROR = 'MARKET_DATA_PROVIDER_ERROR',

  // ===== Indicators 模块 =====
  INDICATOR_CONFIG_NOT_FOUND = 'INDICATOR_CONFIG_NOT_FOUND',
  INDICATOR_CONFIG_INVALID_PARAMS = 'INDICATOR_CONFIG_INVALID_PARAMS',
  INDICATOR_UNSUPPORTED_TIMEFRAME = 'INDICATOR_UNSUPPORTED_TIMEFRAME',

  // ===== Trading 模块 (11000-11099) =====
  TRADING_ACCOUNT_NOT_FOUND = 'TRADING_ACCOUNT_NOT_FOUND',
  TRADING_UNSUPPORTED_EXCHANGE = 'TRADING_UNSUPPORTED_EXCHANGE',
  TRADING_UNSUPPORTED_MARKET_TYPE = 'TRADING_UNSUPPORTED_MARKET_TYPE',
  TRADING_EXCHANGE_INIT_FAILED = 'TRADING_EXCHANGE_INIT_FAILED',
  TRADING_EXCHANGE_OPERATION_FAILED = 'TRADING_EXCHANGE_OPERATION_FAILED',
  TRADING_ORDER_CREATION_FAILED = 'TRADING_ORDER_CREATION_FAILED',
  TRADING_INVALID_CREDENTIALS = 'TRADING_INVALID_CREDENTIALS',

  // ===== 组合/仓位/盈亏 (12000-12099) =====
  EXCHANGE_ACCOUNT_NOT_FOUND = 'EXCHANGE_ACCOUNT_NOT_FOUND',
  EXCHANGE_ACCOUNT_INVALID_CONFIG = 'EXCHANGE_ACCOUNT_INVALID_CONFIG',
  PORTFOLIO_ACCOUNT_NOT_FOUND = 'PORTFOLIO_ACCOUNT_NOT_FOUND',
  PORTFOLIO_ACCOUNT_CONFLICT = 'PORTFOLIO_ACCOUNT_CONFLICT',
  PORTFOLIO_POSITION_NOT_FOUND = 'PORTFOLIO_POSITION_NOT_FOUND',
  PORTFOLIO_POSITION_INSUFFICIENT_QUANTITY = 'PORTFOLIO_POSITION_INSUFFICIENT_QUANTITY',
  PORTFOLIO_TRADE_CONFLICT = 'PORTFOLIO_TRADE_CONFLICT',
  PORTFOLIO_LEDGER_CONFLICT = 'PORTFOLIO_LEDGER_CONFLICT',
  PORTFOLIO_INSUFFICIENT_BALANCE = 'PORTFOLIO_INSUFFICIENT_BALANCE',

  // ===== Strategy Template 模块 (12000-12099) =====
  STRATEGY_TEMPLATE_NOT_FOUND = 'STRATEGY_TEMPLATE_NOT_FOUND',
  STRATEGY_TEMPLATE_INVALID_LEGS = 'STRATEGY_TEMPLATE_INVALID_LEGS',
  STRATEGY_TEMPLATE_INVALID_FIELDS = 'STRATEGY_TEMPLATE_INVALID_FIELDS',
  STRATEGY_TEMPLATE_INVALID_EXECUTION = 'STRATEGY_TEMPLATE_INVALID_EXECUTION',
  STRATEGY_TEMPLATE_INVALID_DATA_REQUIREMENTS = 'STRATEGY_TEMPLATE_INVALID_DATA_REQUIREMENTS',
  STRATEGY_TEMPLATE_VALIDATION_FAILED = 'STRATEGY_TEMPLATE_VALIDATION_FAILED',
  STRATEGY_TEMPLATE_NAME_CONFLICT = 'STRATEGY_TEMPLATE_NAME_CONFLICT',

  // ===== Strategy Subscription 模块 (12100-12199) =====
  SUBSCRIPTION_ALREADY_EXISTS = 'SUBSCRIPTION_ALREADY_EXISTS',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  STRATEGY_NOT_AVAILABLE = 'STRATEGY_NOT_AVAILABLE',
  SUBSCRIPTION_INVALID_PARAMS = 'SUBSCRIPTION_INVALID_PARAMS',

  // ===== Strategy Instance 模块 (12200-12299) =====
  STRATEGY_INSTANCE_NOT_FOUND = 'STRATEGY_INSTANCE_NOT_FOUND',
  STRATEGY_INSTANCE_NAME_CONFLICT = 'STRATEGY_INSTANCE_NAME_CONFLICT',
  INVALID_INSTANCE_STATUS_TRANSITION = 'INVALID_INSTANCE_STATUS_TRANSITION',
  STRATEGY_INSTANCE_INVALID_MODE_TRANSITION = 'STRATEGY_INSTANCE_INVALID_MODE_TRANSITION',

  // ===== AI / LLM 模块 (13000-13099) =====
  AI_PROVIDER_NOT_FOUND = 'AI_PROVIDER_NOT_FOUND',
  AI_NO_ACTIVE_KEY = 'AI_NO_ACTIVE_KEY',
  AI_PROVIDER_ERROR = 'AI_PROVIDER_ERROR',

  // ===== LLM Strategy 模块 (13100-13199) =====
  LLM_STRATEGY_NOT_FOUND = 'LLM_STRATEGY_NOT_FOUND',
  LLM_STRATEGY_NAME_CONFLICT = 'LLM_STRATEGY_NAME_CONFLICT',
  LLM_STRATEGY_NOT_LIVE = 'LLM_STRATEGY_NOT_LIVE',
  LLM_STRATEGY_INSTANCE_NOT_FOUND = 'LLM_STRATEGY_INSTANCE_NOT_FOUND',
  LLM_STRATEGY_INSTANCE_NAME_CONFLICT = 'LLM_STRATEGY_INSTANCE_NAME_CONFLICT',
  LLM_STRATEGY_RUN_NOT_FOUND = 'LLM_STRATEGY_RUN_NOT_FOUND',
}
