/**
 * 统一错误码枚举
 * 前后端共用
 */
export enum ErrorCode {
  // ===== Settings 模块 (10000-10099) =====
  SETTINGS_INVALID_JSON = 'SETTINGS_INVALID_JSON',
  SETTINGS_TYPE_MISMATCH = 'SETTINGS_TYPE_MISMATCH',
  SETTINGS_JSON_EXPECTED_OBJECT_OR_ARRAY = 'SETTINGS_JSON_EXPECTED_OBJECT_OR_ARRAY',
  SETTINGS_NOT_FOUND = 'SETTINGS_NOT_FOUND',

  // ===== 通用错误 =====
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_TEMPORARILY_UNAVAILABLE = 'SERVICE_TEMPORARILY_UNAVAILABLE',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  DATA_CONSISTENCY_ERROR = 'DATA_CONSISTENCY_ERROR',

  // ===== 邮件/通知 =====
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',

  // ===== Auth 模块 =====
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_TAKEN = 'AUTH_EMAIL_ALREADY_TAKEN',
  AUTH_VERIFICATION_CODE_INVALID = 'AUTH_VERIFICATION_CODE_INVALID',
  AUTH_VERIFICATION_CODE_EXPIRED = 'AUTH_VERIFICATION_CODE_EXPIRED',
  AUTH_PASSWORD_RESET_INVALID = 'AUTH_PASSWORD_RESET_INVALID',
  BETA_CODE_REQUIRED = 'BETA_CODE_REQUIRED',
  BETA_CODE_INVALID = 'BETA_CODE_INVALID',
  BETA_CODE_EXHAUSTED = 'BETA_CODE_EXHAUSTED',
  BETA_CODE_DISABLED = 'BETA_CODE_DISABLED',

  // ===== Market Data 模块 =====
  MARKET_SYMBOL_NOT_FOUND = 'MARKET_SYMBOL_NOT_FOUND',
  MARKET_INVALID_SYMBOL = 'MARKET_INVALID_SYMBOL',
  MARKET_INVALID_TIMEFRAME = 'MARKET_INVALID_TIMEFRAME',
  MARKET_DATA_PROVIDER_ERROR = 'MARKET_DATA_PROVIDER_ERROR',

  // ===== Indicators 模块 =====
  INDICATOR_CONFIG_NOT_FOUND = 'INDICATOR_CONFIG_NOT_FOUND',
  INDICATOR_CONFIG_INVALID_PARAMS = 'INDICATOR_CONFIG_INVALID_PARAMS',
  INDICATOR_UNSUPPORTED_TIMEFRAME = 'INDICATOR_UNSUPPORTED_TIMEFRAME',

  // ===== Trading 模块 (11000-11099) =====
  TRADING_ACCOUNT_NOT_FOUND = 'TRADING_ACCOUNT_NOT_FOUND',
  TRADING_UNSUPPORTED_EXCHANGE = 'TRADING_UNSUPPORTED_EXCHANGE',
  TRADING_UNSUPPORTED_MARKET_TYPE = 'TRADING_UNSUPPORTED_MARKET_TYPE',
  TRADING_EXCHANGE_INIT_FAILED = 'TRADING_EXCHANGE_INIT_FAILED',
  TRADING_EXCHANGE_OPERATION_FAILED = 'TRADING_EXCHANGE_OPERATION_FAILED',
  TRADING_ORDER_CREATION_FAILED = 'TRADING_ORDER_CREATION_FAILED',
  TRADING_INVALID_CREDENTIALS = 'TRADING_INVALID_CREDENTIALS',

  // ===== 组合/仓位/盈亏 (12000-12099) =====
  EXCHANGE_ACCOUNT_NOT_FOUND = 'EXCHANGE_ACCOUNT_NOT_FOUND',
  EXCHANGE_ACCOUNT_INVALID_CONFIG = 'EXCHANGE_ACCOUNT_INVALID_CONFIG',
  PORTFOLIO_ACCOUNT_NOT_FOUND = 'PORTFOLIO_ACCOUNT_NOT_FOUND',
  PORTFOLIO_ACCOUNT_CONFLICT = 'PORTFOLIO_ACCOUNT_CONFLICT',
  PORTFOLIO_POSITION_NOT_FOUND = 'PORTFOLIO_POSITION_NOT_FOUND',
  PORTFOLIO_POSITION_INSUFFICIENT_QUANTITY = 'PORTFOLIO_POSITION_INSUFFICIENT_QUANTITY',
  PORTFOLIO_TRADE_CONFLICT = 'PORTFOLIO_TRADE_CONFLICT',
  PORTFOLIO_LEDGER_CONFLICT = 'PORTFOLIO_LEDGER_CONFLICT',
  PORTFOLIO_INSUFFICIENT_BALANCE = 'PORTFOLIO_INSUFFICIENT_BALANCE',

  // ===== Strategy Template 模块 (12000-12099) =====
  STRATEGY_TEMPLATE_NOT_FOUND = 'STRATEGY_TEMPLATE_NOT_FOUND',
  STRATEGY_TEMPLATE_INVALID_LEGS = 'STRATEGY_TEMPLATE_INVALID_LEGS',
  STRATEGY_TEMPLATE_INVALID_FIELDS = 'STRATEGY_TEMPLATE_INVALID_FIELDS',
  STRATEGY_TEMPLATE_INVALID_EXECUTION = 'STRATEGY_TEMPLATE_INVALID_EXECUTION',
  STRATEGY_CONSISTENCY_TIMEFRAME_MISMATCH = 'STRATEGY_CONSISTENCY_TIMEFRAME_MISMATCH',
  STRATEGY_TEMPLATE_INVALID_DATA_REQUIREMENTS = 'STRATEGY_TEMPLATE_INVALID_DATA_REQUIREMENTS',
  STRATEGY_TEMPLATE_VALIDATION_FAILED = 'STRATEGY_TEMPLATE_VALIDATION_FAILED',
  STRATEGY_TEMPLATE_NAME_CONFLICT = 'STRATEGY_TEMPLATE_NAME_CONFLICT',

  // ===== Strategy Subscription 模块 (12100-12199) =====
  SUBSCRIPTION_ALREADY_EXISTS = 'SUBSCRIPTION_ALREADY_EXISTS',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  STRATEGY_NOT_AVAILABLE = 'STRATEGY_NOT_AVAILABLE',
  SUBSCRIPTION_INVALID_PARAMS = 'SUBSCRIPTION_INVALID_PARAMS',

  // ===== Strategy Instance 模块 (12200-12299) =====
  STRATEGY_INSTANCE_NOT_FOUND = 'STRATEGY_INSTANCE_NOT_FOUND',
  STRATEGY_INSTANCE_NAME_CONFLICT = 'STRATEGY_INSTANCE_NAME_CONFLICT',
  INVALID_INSTANCE_STATUS_TRANSITION = 'INVALID_INSTANCE_STATUS_TRANSITION',
  STRATEGY_INSTANCE_INVALID_MODE_TRANSITION = 'STRATEGY_INSTANCE_INVALID_MODE_TRANSITION',
  STRATEGY_INSTANCE_INVALID_INPUT = 'STRATEGY_INSTANCE_INVALID_INPUT',
  STRATEGY_INSTANCE_SCRIPT_FAILED = 'STRATEGY_INSTANCE_SCRIPT_FAILED',
  STRATEGY_INSTANCE_SUBSCRIPTION_REQUIRED = 'STRATEGY_INSTANCE_SUBSCRIPTION_REQUIRED',
  STRATEGY_INSTANCE_STATS_ERROR = 'STRATEGY_INSTANCE_STATS_ERROR',
  STRATEGY_INSTANCE_SIGNAL_DISABLED = 'STRATEGY_INSTANCE_SIGNAL_DISABLED',
  STRATEGY_INSTANCE_VIEW_ONLY = 'STRATEGY_INSTANCE_VIEW_ONLY',
  STRATEGY_INSTANCE_ARCHIVED = 'STRATEGY_INSTANCE_ARCHIVED',

  // ===== Data Sync 模块 =====
  DATA_SYNC_TASK_NOT_FOUND = 'DATA_SYNC_TASK_NOT_FOUND',
  DATA_SYNC_TASK_KEY_NOT_REGISTERED = 'DATA_SYNC_TASK_KEY_NOT_REGISTERED',
  DATA_SYNC_TASK_ALREADY_RUNNING = 'DATA_SYNC_TASK_ALREADY_RUNNING',
  DATA_SYNC_TASK_KEY_DUPLICATE = 'DATA_SYNC_TASK_KEY_DUPLICATE',
  DATA_SYNC_TASK_NOT_INTERRUPTIBLE = 'DATA_SYNC_TASK_NOT_INTERRUPTIBLE',
  DATA_SYNC_TASK_STATUS_CHANGED = 'DATA_SYNC_TASK_STATUS_CHANGED',
  DATA_SYNC_API_ERROR = 'DATA_SYNC_API_ERROR',
  DATA_SYNC_CONFIG_MISSING = 'DATA_SYNC_CONFIG_MISSING',
  DATA_SYNC_INVALID_RESPONSE = 'DATA_SYNC_INVALID_RESPONSE',
  DATA_SYNC_DATA_VALIDATION_FAILED = 'DATA_SYNC_DATA_VALIDATION_FAILED',
  DATA_SYNC_OPERATION_TIMEOUT = 'DATA_SYNC_OPERATION_TIMEOUT',

  // ===== Aggregated Liquidation 模块 =====
  AGGREGATED_LIQUIDATION_NOT_FOUND = 'AGGREGATED_LIQUIDATION_NOT_FOUND',

  // ===== Liquidation Heatmap 模块 =====
  LIQUIDATION_HEATMAP_NOT_FOUND = 'LIQUIDATION_HEATMAP_NOT_FOUND',

  // ===== Open Interest 模块 =====
  OPEN_INTEREST_NOT_FOUND = 'OPEN_INTEREST_NOT_FOUND',
  OPEN_INTEREST_INVALID_PARAMS = 'OPEN_INTEREST_INVALID_PARAMS',
  OPEN_INTEREST_RANGE_EXCEEDED = 'OPEN_INTEREST_RANGE_EXCEEDED',

  // ===== Validation =====
  INVALID_ETHEREUM_ADDRESS = 'INVALID_ETHEREUM_ADDRESS',

  // ===== Orderbook Config 模块 =====
  ORDERBOOK_CONFIG_PAIR_ID_MISMATCH = 'ORDERBOOK_CONFIG_PAIR_ID_MISMATCH',
  ORDERBOOK_CONFIG_PAIR_ALREADY_EXISTS = 'ORDERBOOK_CONFIG_PAIR_ALREADY_EXISTS',
  ORDERBOOK_CONFIG_DATA_NOT_AVAILABLE = 'ORDERBOOK_CONFIG_DATA_NOT_AVAILABLE',
  ORDERBOOK_CONFIG_DATA_EXPIRED = 'ORDERBOOK_CONFIG_DATA_EXPIRED',
  ORDERBOOK_CONFIG_DATA_INVALID = 'ORDERBOOK_CONFIG_DATA_INVALID',

  // ===== Trades Config 模块 =====
  TRADES_CONFIG_PAIR_ID_MISMATCH = 'TRADES_CONFIG_PAIR_ID_MISMATCH',
  TRADES_CONFIG_OKX_INSTID_UNRESOLVABLE = 'TRADES_CONFIG_OKX_INSTID_UNRESOLVABLE',
  TRADES_CONFIG_OKX_INSTID_CONFLICT = 'TRADES_CONFIG_OKX_INSTID_CONFLICT',
  TRADES_CONFIG_PAIR_ALREADY_EXISTS = 'TRADES_CONFIG_PAIR_ALREADY_EXISTS',

  // ===== 基础设施 =====
  POLYMARKET_CLIENT_ERROR = 'POLYMARKET_CLIENT_ERROR',
  MAIL_SERVICE_ERROR = 'MAIL_SERVICE_ERROR',
  REDIS_CONNECTION_ERROR = 'REDIS_CONNECTION_ERROR',
  CRYPTO_CONFIG_ERROR = 'CRYPTO_CONFIG_ERROR',
  KLINE_INVALID_INTERVAL = 'KLINE_INVALID_INTERVAL',
  KLINE_QUERY_TIMEOUT = 'KLINE_QUERY_TIMEOUT',
  WHALE_TRACKING_API_ERROR = 'WHALE_TRACKING_API_ERROR',
  WHALE_NOTIFICATION_DISPATCH_ERROR = 'WHALE_NOTIFICATION_DISPATCH_ERROR',
  AUTH_JWT_CONFIG_ERROR = 'AUTH_JWT_CONFIG_ERROR',
  AUTH_RATE_LIMIT_ERROR = 'AUTH_RATE_LIMIT_ERROR',
  PRISMA_CONNECTION_ERROR = 'PRISMA_CONNECTION_ERROR',
  CONFIG_VALIDATION_ERROR = 'CONFIG_VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  OPEN_INTEREST_SYNC_ERROR = 'OPEN_INTEREST_SYNC_ERROR',
  CRYPTO_STOCK_QUOTES_ERROR = 'CRYPTO_STOCK_QUOTES_ERROR',

  // ===== Strategy Signal 模块 =====
  STRATEGY_SIGNAL_STATE_NOT_FOUND = 'STRATEGY_SIGNAL_STATE_NOT_FOUND',
  STRATEGY_SIGNAL_GENERATION_ERROR = 'STRATEGY_SIGNAL_GENERATION_ERROR',
  STRATEGY_SIGNAL_CONFIG_ERROR = 'STRATEGY_SIGNAL_CONFIG_ERROR',

  // ===== Backtesting 模块 =====
  BACKTEST_INSTANCE_NOT_FOUND = 'BACKTEST_INSTANCE_NOT_FOUND',
  BACKTEST_TEMPLATE_NOT_FOUND = 'BACKTEST_TEMPLATE_NOT_FOUND',
  BACKTEST_JOB_CONFLICT = 'BACKTEST_JOB_CONFLICT',

  // ===== Market Data 模块 - 新增 =====
  MARKET_DATA_INGESTION_ERROR = 'MARKET_DATA_INGESTION_ERROR',

  // ===== AI / LLM 模块 (13000-13099) =====
  AI_PROVIDER_NOT_FOUND = 'AI_PROVIDER_NOT_FOUND',
  AI_NO_ACTIVE_KEY = 'AI_NO_ACTIVE_KEY',
  AI_PROVIDER_ERROR = 'AI_PROVIDER_ERROR',

  // ===== Mastra 模块 (13050-13099) =====
  MASTRA_PROVIDER_MISSING_CREDENTIAL = 'MASTRA_PROVIDER_MISSING_CREDENTIAL',
  MASTRA_UNSUPPORTED_PROVIDER = 'MASTRA_UNSUPPORTED_PROVIDER',
  MASTRA_GENERATION_FAILED = 'MASTRA_GENERATION_FAILED',

  // ===== LLM Strategy 模块 (13100-13199) =====
  LLM_STRATEGY_NOT_FOUND = 'LLM_STRATEGY_NOT_FOUND',
  LLM_STRATEGY_NAME_CONFLICT = 'LLM_STRATEGY_NAME_CONFLICT',
  LLM_STRATEGY_NOT_LIVE = 'LLM_STRATEGY_NOT_LIVE',
  LLM_STRATEGY_INSTANCE_NOT_FOUND = 'LLM_STRATEGY_INSTANCE_NOT_FOUND',
  LLM_STRATEGY_INSTANCE_NAME_CONFLICT = 'LLM_STRATEGY_INSTANCE_NAME_CONFLICT',
  LLM_STRATEGY_RUN_NOT_FOUND = 'LLM_STRATEGY_RUN_NOT_FOUND',
  LLM_STRATEGY_INSTANCE_FORBIDDEN = 'LLM_STRATEGY_INSTANCE_FORBIDDEN',
  LLM_STRATEGY_INSTANCE_INVALID_CONFIG = 'LLM_STRATEGY_INSTANCE_INVALID_CONFIG',

  // ===== LLM Subscription 模块 =====
  LLM_SUBSCRIPTION_INVALID_OPERATION = 'LLM_SUBSCRIPTION_INVALID_OPERATION',
  LLM_SUBSCRIPTION_ACCOUNT_FAILED = 'LLM_SUBSCRIPTION_ACCOUNT_FAILED',

  // ===== LLM Codegen 模块 =====
  LLM_CODEGEN_SESSION_NOT_FOUND = 'LLM_CODEGEN_SESSION_NOT_FOUND',
  LLM_CODEGEN_GENERATION_FAILED = 'LLM_CODEGEN_GENERATION_FAILED',
  READINESS_TIMEFRAME_MISMATCH = 'READINESS_TIMEFRAME_MISMATCH',

  // ===== Position 模块 - 新增 =====
  PORTFOLIO_POSITION_CLOSE_ERROR = 'PORTFOLIO_POSITION_CLOSE_ERROR',

  // ===== Account Strategy View 模块 =====
  ACCOUNT_STRATEGY_MISSING_IDENTITY = 'ACCOUNT_STRATEGY_MISSING_IDENTITY',
  ACCOUNT_STRATEGY_USER_ID_MISMATCH = 'ACCOUNT_STRATEGY_USER_ID_MISMATCH',
  ACCOUNT_STRATEGY_NOT_FOUND = 'ACCOUNT_STRATEGY_NOT_FOUND',
  ACCOUNT_STRATEGY_OWNER_ONLY = 'ACCOUNT_STRATEGY_OWNER_ONLY',
  ACCOUNT_STRATEGY_INVALID_ACTION = 'ACCOUNT_STRATEGY_INVALID_ACTION',

  // ===== Strategy Plaza 模块 =====
  STRATEGY_PLAZA_OKX_DEMO_API_KEY_REQUIRED = 'strategy_plaza.okx_demo_api_key_required',
  STRATEGY_PLAZA_OFFICIAL_SNAPSHOT_UNAVAILABLE = 'strategy_plaza.official_snapshot_unavailable',

  // ===== Exchange Accounts 模块 - 新增 =====
  EXCHANGE_ACCOUNT_MISSING_EMAIL = 'EXCHANGE_ACCOUNT_MISSING_EMAIL',
  EXCHANGE_ACCOUNT_USER_CONFLICT = 'EXCHANGE_ACCOUNT_USER_CONFLICT',
  EXCHANGE_ACCOUNT_EXCHANGE_UNAVAILABLE = 'EXCHANGE_ACCOUNT_EXCHANGE_UNAVAILABLE',
}
