export const LLM_RUN_REASONS = {
  OK: 'OK',
  NO_TOOL_CALL: 'NO_TOOL_CALL',
  TOOL_CALL_LIMIT_EXCEEDED: 'TOOL_CALL_LIMIT_EXCEEDED',
  INVALID_TOOL_ARGS: 'INVALID_TOOL_ARGS',
  SKIPPED_STATUS: 'SKIPPED_STATUS',
  SKIPPED_RATE_LIMIT: 'SKIPPED_RATE_LIMIT',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
} as const

export type LlmRunReason = (typeof LLM_RUN_REASONS)[keyof typeof LLM_RUN_REASONS]
