import type { CompiledScriptProjection } from '../types/compiled-script-projection'
import { createHash } from 'node:crypto'
import { canonicalSerialize } from '@ai/shared/script-engine/compiled-runtime'
import { Injectable } from '@nestjs/common'
import { FIXED_IMPORT_BLOCK, FIXED_STRATEGY_WRAPPER } from './compiled-script-emitter.service'

const HEADER_PATTERN = /^\/\* @generated by compiler\.v1 \*\/\n\/\* irHash: (?<irHash>sha256:[a-f0-9]+) \*\/\n\/\* specHash: (?<specHash>sha256:[a-f0-9]+) \*\/\n\/\* astDigest: (?<astDigest>sha256:[a-f0-9]+) \*\/\n\/\* structuralDigest: (?<structuralDigest>sha256:[a-f0-9]+) \*\/\n\n/u
const FIXED_IMPORT_BLOCK_COMPAT = buildPreRiskPredicateImportBlock()
const FIXED_STRATEGY_WRAPPER_COMPAT = buildPreRiskPredicateStrategyWrapper()

@Injectable()
export class CompiledScriptParserService {
  parse(script: string): CompiledScriptProjection {
    const headerMatch = HEADER_PATTERN.exec(script)
    if (!headerMatch?.groups) {
      throw new Error('codegen.compiled_script_invalid')
    }

    const afterHeader = script.slice(headerMatch[0].length)
    const expectedImportBlock = this.matchFixedBlock(afterHeader, [
      FIXED_IMPORT_BLOCK,
      FIXED_IMPORT_BLOCK_COMPAT,
    ])
    if (!expectedImportBlock) {
      throw new Error('codegen.compiled_script_invalid')
    }

    const afterImport = afterHeader.slice(expectedImportBlock.length + 2)
    const lines = afterImport.split('\n')
    const values = new Map<string, unknown>()

    values.set('COMPILED_MANIFEST', this.readRequiredConst(lines, 'COMPILED_MANIFEST'))
    values.set('EXECUTION_MODEL', this.readRequiredConst(lines, 'EXECUTION_MODEL'))
    values.set('DATA_REQUIREMENTS', this.readRequiredConst(lines, 'DATA_REQUIREMENTS'))
    values.set('RUNTIME_REQUIREMENTS', this.readOptionalConst(lines, 'RUNTIME_REQUIREMENTS'))
    values.set('EXPR_POOL', this.readRequiredConst(lines, 'EXPR_POOL'))
    values.set('GUARD_PROGRAMS', this.readRequiredConst(lines, 'GUARD_PROGRAMS'))
    values.set('RISK_PREDICATES', this.readOptionalConst(lines, 'RISK_PREDICATES'))
    values.set('DECISION_PROGRAMS', this.readRequiredConst(lines, 'DECISION_PROGRAMS'))
    values.set('ORDER_PROGRAMS', this.readRequiredConst(lines, 'ORDER_PROGRAMS'))
    values.set('ORCHESTRATION_PROGRAMS', this.readOptionalConst(lines, 'ORCHESTRATION_PROGRAMS'))
    values.set('TOPOLOGY', this.readRequiredConst(lines, 'TOPOLOGY'))

    const spacer = lines.shift()
    if (spacer !== '') {
      throw new Error('codegen.compiled_script_invalid')
    }

    if (!this.isCompatibleWrapper(lines.join('\n'))) {
      throw new Error('codegen.compiled_script_invalid')
    }

    const projection: CompiledScriptProjection = {
      compiledManifest: values.get('COMPILED_MANIFEST') as CompiledScriptProjection['compiledManifest'],
      executionModel: values.get('EXECUTION_MODEL') as CompiledScriptProjection['executionModel'],
      dataRequirements: values.get('DATA_REQUIREMENTS') as CompiledScriptProjection['dataRequirements'],
      ...this.optionalProjectionField('runtimeRequirements', values.get('RUNTIME_REQUIREMENTS')),
      exprPool: values.get('EXPR_POOL') as CompiledScriptProjection['exprPool'],
      guards: values.get('GUARD_PROGRAMS') as CompiledScriptProjection['guards'],
      ...this.optionalProjectionField('riskPredicates', values.get('RISK_PREDICATES')),
      decisionPrograms: values.get('DECISION_PROGRAMS') as CompiledScriptProjection['decisionPrograms'],
      orderPrograms: values.get('ORDER_PROGRAMS') as CompiledScriptProjection['orderPrograms'],
      ...this.optionalProjectionField('orchestrationPrograms', values.get('ORCHESTRATION_PROGRAMS')),
      topology: values.get('TOPOLOGY') as CompiledScriptProjection['topology'],
    }

    if (
      projection.compiledManifest.irHash !== headerMatch.groups.irHash
      || projection.compiledManifest.specHash !== headerMatch.groups.specHash
      || projection.compiledManifest.astDigest !== headerMatch.groups.astDigest
      || projection.compiledManifest.structuralDigest !== headerMatch.groups.structuralDigest
    ) {
      throw new Error('codegen.compiled_script_invalid')
    }

    const recomputedStructuralDigest = hashCanonicalJson({
      executionModel: projection.executionModel,
      dataRequirements: projection.dataRequirements,
      runtimeRequirements: projection.runtimeRequirements,
      exprPool: projection.exprPool,
      guards: projection.guards,
      riskPredicates: projection.riskPredicates,
      decisionPrograms: projection.decisionPrograms,
      orderPrograms: projection.orderPrograms,
      topology: projection.topology,
    })

    if (recomputedStructuralDigest !== projection.compiledManifest.structuralDigest) {
      throw new Error('codegen.compiled_script_invalid')
    }

    return projection
  }

  private optionalProjectionField<K extends 'runtimeRequirements' | 'riskPredicates' | 'orchestrationPrograms'>(
    key: K,
    value: unknown,
  ): Pick<CompiledScriptProjection, K> | Record<string, never> {
    return value === null
      ? {}
      : { [key]: value } as Pick<CompiledScriptProjection, K>
  }

  private matchFixedBlock(script: string, candidates: readonly string[]): string | null {
    for (const candidate of candidates) {
      if (script.startsWith(`${candidate}\n\n`)) {
        return candidate
      }
    }

    return null
  }

  private isCompatibleWrapper(wrapper: string): boolean {
    return wrapper === `${FIXED_STRATEGY_WRAPPER}\n`
      || wrapper === `${FIXED_STRATEGY_WRAPPER_COMPAT}\n`
  }

  private readRequiredConst(lines: string[], name: string): unknown {
    const line = lines.shift()
    if (!line) {
      throw new Error('codegen.compiled_script_invalid')
    }
    return this.parseConstLine(line, name)
  }

  private readOptionalConst(lines: string[], name: string): unknown {
    const line = lines[0]
    if (!line?.startsWith(`const ${name} = `)) {
      return null
    }

    lines.shift()
    return this.parseConstLine(line, name)
  }

  private parseConstLine(line: string, name: string): unknown {
    const prefix = `const ${name} = `
    const suffix = ' as const'

    if (!line.startsWith(prefix) || !line.endsWith(suffix)) {
      throw new Error('codegen.compiled_script_invalid')
    }

    const jsonPayload = line.slice(prefix.length, line.length - suffix.length)
    return JSON.parse(jsonPayload)
  }
}

function buildPreRiskPredicateImportBlock(): string {
  return FIXED_IMPORT_BLOCK
    .split('\n')
    .filter(line => line !== '  evaluateRiskPredicates,')
    .join('\n')
}

function buildPreRiskPredicateStrategyWrapper(): string {
  return FIXED_STRATEGY_WRAPPER.replace(
    [
      '    const baseGuardState = evaluateGuards(',
      '      ctx,',
      '      GUARD_PROGRAMS,',
      '      exprValues,',
      '      TOPOLOGY.guardOrder,',
      '    )',
      '',
      '    const guardState = evaluateRiskPredicates(',
      '      ctx,',
      '      RISK_PREDICATES,',
      '      baseGuardState,',
      '      TOPOLOGY.riskPredicateOrder,',
      '    )',
    ].join('\n'),
    [
      '    const guardState = evaluateGuards(',
      '      ctx,',
      '      GUARD_PROGRAMS,',
      '      exprValues,',
      '      TOPOLOGY.guardOrder,',
      '    )',
    ].join('\n'),
  )
}

function hashCanonicalJson(value: unknown): `sha256:${string}` {
  const digest = createHash('sha256').update(canonicalSerialize(value)).digest('hex')
  return `sha256:${digest}`
}
