import type { StrategyAstV1 } from '../types/canonical-strategy-ast'
import type { CompiledScriptExecutionEnvelope, CompiledScriptProjection, CompiledStrategyManifest } from '../types/compiled-script-projection'
import { createHash } from 'node:crypto'
import { canonicalSerialize } from '@ai/shared/script-engine/compiled-runtime'
import { Injectable } from '@nestjs/common'

export const FIXED_IMPORT_BLOCK = [
  "import type { StrategyAdapterV1 } from '@ai/shared'",
  'import {',
  '  evaluateExprPool,',
  '  evaluateGuards,',
  '  evaluateRiskPredicates,',
  '  runDecisionPrograms,',
  '  runOrderPrograms,',
  '  buildCompiledManifest,',
  "} from '@ai/shared/script-engine/compiled-runtime'",
].join('\n')

export const FIXED_STRATEGY_WRAPPER = [
  'const strategy: StrategyAdapterV1 = {',
  "  protocolVersion: 'v1',",
  '  onBar(ctx) {',
  '    const exprValues = evaluateExprPool(ctx, EXPR_POOL, TOPOLOGY.exprOrder, EXECUTION_MODEL)',
  '',
  '    const baseGuardState = evaluateGuards(',
  '      ctx,',
  '      GUARD_PROGRAMS,',
  '      exprValues,',
  '      TOPOLOGY.guardOrder,',
  '    )',
  '',
  '    const guardState = evaluateRiskPredicates(',
  '      ctx,',
  '      RISK_PREDICATES,',
  '      baseGuardState,',
  '      TOPOLOGY.riskPredicateOrder,',
  '    )',
  '',
  '    const decision = runDecisionPrograms(',
  '      ctx,',
  '      DECISION_PROGRAMS,',
  '      exprValues,',
  '      guardState,',
  '      TOPOLOGY.decisionOrder,',
  '    )',
  '',
  '    const orderState = runOrderPrograms(',
  '      ctx,',
  '      ORDER_PROGRAMS,',
  '      exprValues,',
  '      guardState,',
  '      TOPOLOGY.orderProgramOrder,',
  '      EXECUTION_MODEL,',
  '      ORCHESTRATION_PROGRAMS,',
  '    )',
  '',
  '    return buildCompiledManifest(',
  '      decision,',
  '      orderState,',
  '      guardState,',
  '      COMPILED_MANIFEST,',
  '    )',
  '  },',
  '}',
  '',
  'export default strategy',
].join('\n')

export interface EmitCompiledScriptInput {
  ast: StrategyAstV1
  executionEnvelope: CompiledScriptExecutionEnvelope
}

@Injectable()
export class CompiledScriptEmitterService {
  emit(input: EmitCompiledScriptInput): string {
    const projection = this.buildProjection(input)

    return [
      '/* @generated by compiler.v1 */',
      `/* irHash: ${projection.compiledManifest.irHash} */`,
      `/* specHash: ${projection.compiledManifest.specHash} */`,
      `/* astDigest: ${projection.compiledManifest.astDigest} */`,
      `/* structuralDigest: ${projection.compiledManifest.structuralDigest} */`,
      '',
      FIXED_IMPORT_BLOCK,
      '',
      this.emitConst('COMPILED_MANIFEST', projection.compiledManifest),
      this.emitConst('EXECUTION_MODEL', projection.executionModel),
      this.emitConst('DATA_REQUIREMENTS', projection.dataRequirements),
      this.emitConst('RUNTIME_REQUIREMENTS', projection.runtimeRequirements ?? null),
      this.emitConst('EXPR_POOL', projection.exprPool),
      this.emitConst('GUARD_PROGRAMS', projection.guards),
      this.emitConst('RISK_PREDICATES', projection.riskPredicates ?? null),
      this.emitConst('DECISION_PROGRAMS', projection.decisionPrograms),
      this.emitConst('ORDER_PROGRAMS', projection.orderPrograms),
      this.emitConst('ORCHESTRATION_PROGRAMS', projection.orchestrationPrograms ?? []),
      this.emitConst('TOPOLOGY', projection.topology),
      '',
      FIXED_STRATEGY_WRAPPER,
      '',
    ].join('\n')
  }

  buildProjection(input: EmitCompiledScriptInput): CompiledScriptProjection {
    const exprPool = this.projectByOrder(input.ast.exprPool, input.ast.topology.exprOrder)
    const guards = this.projectByOrder(input.ast.guards, input.ast.topology.guardOrder)
    const riskPredicates = this.projectOptionalByOrder(input.ast.riskPredicates, input.ast.topology.riskPredicateOrder)
    const decisionPrograms = this.projectByOrder(input.ast.decisionPrograms, input.ast.topology.decisionOrder)
    const orderPrograms = this.projectByOrder(input.ast.orderPrograms, input.ast.topology.orderProgramOrder)
    const executionModel = {
      ...input.ast.executionModel,
      ...input.executionEnvelope,
    }

    return {
      compiledManifest: this.buildCompiledManifest(input.ast, input.executionEnvelope),
      executionModel,
      dataRequirements: input.ast.dataRequirements,
      ...(input.ast.runtimeRequirements ? { runtimeRequirements: input.ast.runtimeRequirements } : {}),
      exprPool,
      guards,
      ...(riskPredicates ? { riskPredicates } : {}),
      decisionPrograms,
      orderPrograms,
      ...(input.ast.orchestrationPrograms ? { orchestrationPrograms: input.ast.orchestrationPrograms } : {}),
      topology: input.ast.topology,
    }
  }

  private buildCompiledManifest(
    ast: StrategyAstV1,
    executionEnvelope: CompiledScriptExecutionEnvelope,
  ): CompiledStrategyManifest {
    const astProjection = {
      astVersion: ast.astVersion,
      executionModel: ast.executionModel,
      dataRequirements: ast.dataRequirements,
      runtimeRequirements: ast.runtimeRequirements,
      exprPool: this.projectByOrder(ast.exprPool, ast.topology.exprOrder),
      guards: this.projectByOrder(ast.guards, ast.topology.guardOrder),
      riskPredicates: this.projectOptionalByOrder(ast.riskPredicates, ast.topology.riskPredicateOrder),
      decisionPrograms: this.projectByOrder(ast.decisionPrograms, ast.topology.decisionOrder),
      orderPrograms: this.projectByOrder(ast.orderPrograms, ast.topology.orderProgramOrder),
      ...(ast.orchestrationPrograms ? { orchestrationPrograms: ast.orchestrationPrograms } : {}),
      topology: ast.topology,
    }
    const structuralProjection = {
      executionModel: {
        ...ast.executionModel,
        ...executionEnvelope,
      },
      dataRequirements: ast.dataRequirements,
      runtimeRequirements: ast.runtimeRequirements,
      exprPool: this.projectByOrder(ast.exprPool, ast.topology.exprOrder),
      guards: this.projectByOrder(ast.guards, ast.topology.guardOrder),
      riskPredicates: this.projectOptionalByOrder(ast.riskPredicates, ast.topology.riskPredicateOrder),
      decisionPrograms: this.projectByOrder(ast.decisionPrograms, ast.topology.decisionOrder),
      orderPrograms: this.projectByOrder(ast.orderPrograms, ast.topology.orderProgramOrder),
      topology: ast.topology,
    }

    return {
      irVersion: ast.manifest.irVersion,
      astVersion: ast.astVersion,
      compileVersion: 'compiler.v1',
      irHash: ast.manifest.irHash,
      specHash: ast.manifest.specHash,
      astDigest: hashCanonicalJson(astProjection),
      structuralDigest: hashCanonicalJson(structuralProjection),
    }
  }

  private emitConst(name: string, value: unknown): string {
    return `const ${name} = ${canonicalSerialize(value)} as const`
  }

  private projectByOrder<T extends { id: string }>(items: T[], order: string[]): T[] {
    const itemIndex = new Map(items.map(item => [item.id, item]))

    return order
      .map(id => itemIndex.get(id))
      .filter((item): item is T => item !== undefined)
  }

  private projectOptionalByOrder<T extends { id: string }>(
    items: T[] | undefined,
    order: string[] | undefined,
  ): T[] | undefined {
    if (!items || !order) return undefined
    return this.projectByOrder(items, order)
  }
}

function hashCanonicalJson(value: unknown): `sha256:${string}` {
  const digest = createHash('sha256').update(canonicalSerialize(value)).digest('hex')
  return `sha256:${digest}`
}
