import type { CompiledScriptProjection } from '../types/compiled-script-projection'
import { canonicalSerialize } from '@ai/shared/script-engine/compiled-runtime'
import { createHash } from 'node:crypto'
import { Injectable } from '@nestjs/common'
import { FIXED_IMPORT_BLOCK, FIXED_STRATEGY_WRAPPER } from './compiled-script-emitter.service'

const HEADER_PATTERN = /^\/\* @generated by compiler\.v1 \*\/\n\/\* irHash: (?<irHash>sha256:[a-f0-9]+) \*\/\n\/\* specHash: (?<specHash>sha256:[a-f0-9]+) \*\/\n\/\* astDigest: (?<astDigest>sha256:[a-f0-9]+) \*\/\n\/\* structuralDigest: (?<structuralDigest>sha256:[a-f0-9]+) \*\/\n\n/u

const CONST_NAMES = [
  'COMPILED_MANIFEST',
  'EXECUTION_MODEL',
  'DATA_REQUIREMENTS',
  'EXPR_POOL',
  'GUARD_PROGRAMS',
  'DECISION_PROGRAMS',
  'ORDER_PROGRAMS',
  'TOPOLOGY',
] as const

@Injectable()
export class CompiledScriptParserService {
  parse(script: string): CompiledScriptProjection {
    const headerMatch = HEADER_PATTERN.exec(script)
    if (!headerMatch?.groups) {
      throw new Error('codegen.compiled_script_invalid')
    }

    const afterHeader = script.slice(headerMatch[0].length)
    const expectedImportBlock = `${FIXED_IMPORT_BLOCK}\n\n`
    if (!afterHeader.startsWith(expectedImportBlock)) {
      throw new Error('codegen.compiled_script_invalid')
    }

    const afterImport = afterHeader.slice(expectedImportBlock.length)
    const lines = afterImport.split('\n')
    const values = new Map<string, unknown>()

    for (const name of CONST_NAMES) {
      const line = lines.shift()
      const prefix = `const ${name} = `
      const suffix = ' as const'

      if (!line?.startsWith(prefix) || !line.endsWith(suffix)) {
        throw new Error('codegen.compiled_script_invalid')
      }

      const jsonPayload = line.slice(prefix.length, line.length - suffix.length)
      values.set(name, JSON.parse(jsonPayload))
    }

    const spacer = lines.shift()
    if (spacer !== '') {
      throw new Error('codegen.compiled_script_invalid')
    }

    if (lines.join('\n') !== `${FIXED_STRATEGY_WRAPPER}\n`) {
      throw new Error('codegen.compiled_script_invalid')
    }

    const projection: CompiledScriptProjection = {
      compiledManifest: values.get('COMPILED_MANIFEST') as CompiledScriptProjection['compiledManifest'],
      executionModel: values.get('EXECUTION_MODEL') as CompiledScriptProjection['executionModel'],
      dataRequirements: values.get('DATA_REQUIREMENTS') as CompiledScriptProjection['dataRequirements'],
      exprPool: values.get('EXPR_POOL') as CompiledScriptProjection['exprPool'],
      guards: values.get('GUARD_PROGRAMS') as CompiledScriptProjection['guards'],
      decisionPrograms: values.get('DECISION_PROGRAMS') as CompiledScriptProjection['decisionPrograms'],
      orderPrograms: values.get('ORDER_PROGRAMS') as CompiledScriptProjection['orderPrograms'],
      topology: values.get('TOPOLOGY') as CompiledScriptProjection['topology'],
    }

    if (
      projection.compiledManifest.irHash !== headerMatch.groups.irHash
      || projection.compiledManifest.specHash !== headerMatch.groups.specHash
      || projection.compiledManifest.astDigest !== headerMatch.groups.astDigest
      || projection.compiledManifest.structuralDigest !== headerMatch.groups.structuralDigest
    ) {
      throw new Error('codegen.compiled_script_invalid')
    }

    const recomputedStructuralDigest = hashCanonicalJson({
      executionModel: projection.executionModel,
      dataRequirements: projection.dataRequirements,
      exprPool: projection.exprPool,
      guards: projection.guards,
      decisionPrograms: projection.decisionPrograms,
      orderPrograms: projection.orderPrograms,
      topology: projection.topology,
    })

    if (recomputedStructuralDigest !== projection.compiledManifest.structuralDigest) {
      throw new Error('codegen.compiled_script_invalid')
    }

    return projection
  }
}

function hashCanonicalJson(value: unknown): `sha256:${string}` {
  const digest = createHash('sha256').update(canonicalSerialize(value)).digest('hex')
  return `sha256:${digest}`
}
