import type { MarketDataCatalogItem } from './catalog-types'

export const FALLBACK_MARKET_DATA_CATALOG: MarketDataCatalogItem[] = [
  // Charts
  {
    id: 'candlestick-chart',
    kind: 'dashboardWidget',
    labelKey: 'dashboard.widgets.candlestickChart',
    category: 'market_data',
    descriptionKey: 'dashboard.widgets.descriptions.candlestickChart',
    tags: ['Price', 'OHLC', 'TradingView'],
    group: 'featured',
    starred: true,
    ui: {
      icon: 'CandlestickChart',
      color: '#F7931A',
    },
  },
  {
    id: 'liquidation-map',
    kind: 'chartOverlay',
    labelKey: 'chart.indicators.liquidationMap',
    category: 'liquidation',
    descriptionKey: 'dashboard.widgets.descriptions.liquidationMap',
    tags: ['Heatmap', 'Liquidation', 'Realtime'],
    group: 'featured',
    starred: true,
    href: '/liquidation-map',
    ui: {
      icon: 'Map',
      color: '#F0B90B',
    },
  },
  {
    id: 'long-short-ratio',
    kind: 'chartSeries',
    labelKey: 'chart.indicators.longShortRatio',
    category: 'derivatives',
    descriptionKey: 'dashboard.widgets.descriptions.lsRatio',
    tags: ['Ratio', 'Sentiment', 'Positions'],
    group: 'featured',
    starred: true,
    href: '/long-short-ratio',
    ui: {
      icon: 'BarChart2',
      color: '#0ECB81',
    },
  },
  {
    id: 'aggregated-orderbook',
    kind: 'dashboardWidget',
    labelKey: 'chart.indicators.aggregatedOrderbook',
    category: 'derivatives',
    descriptionKey: 'dashboard.widgets.descriptions.aggOrderbook',
    tags: ['Depth', 'Liquidity', 'Heatmap'],
    group: 'featured',
    starred: true,
    href: '/aggregated-orderbook',
    ui: {
      icon: 'Layers',
      color: '#3b82f6',
    },
  },
  {
    id: 'aggregated-open-interest',
    kind: 'chartSeries',
    labelKey: 'chart.indicators.aggregatedOpenInterest',
    category: 'derivatives',
    descriptionKey: 'dashboard.widgets.descriptions.aggOI',
    tags: ['Open Interest', 'Market Depth', 'Trend'],
    group: 'featured',
    starred: true,
    href: '/aggregated-orderbook',
    ui: {
      icon: 'LineChart',
      color: '#8b5cf6',
    },
  },
  {
    id: 'aggregated-volume',
    kind: 'chartSeries',
    labelKey: 'chart.indicators.aggregatedVolume',
    category: 'derivatives',
    descriptionKey: 'dashboard.widgets.descriptions.aggVolume',
    tags: ['Volume', 'Activity', 'Turnover'],
    group: 'featured',
    starred: true,
    href: '/aggregated-orderbook',
    ui: {
      icon: 'Activity',
      color: '#ec4899',
    },
  },
  {
    id: 'liquidation-data',
    kind: 'chartSeries',
    labelKey: 'chart.indicators.liquidationData',
    category: 'liquidation',
    descriptionKey: 'dashboard.widgets.descriptions.liquidationData',
    tags: ['Rekt', 'Liquidations', 'Alerts'],
    group: 'featured',
    starred: true,
    href: '/liquidation-data',
    ui: {
      icon: 'Zap',
      color: '#ef4444',
    },
  },
  {
    id: 'prediction-market',
    kind: 'dashboardWidget',
    labelKey: 'nav.prediction_market',
    category: 'market_data',
    descriptionKey: 'dashboard.widgets.descriptions.predictionMarket',
    tags: ['Polymarket', 'Forecast', 'Events'],
    group: 'featured',
    ui: {
      icon: 'Vote',
      color: '#F5AC37',
    },
  },
  {
    id: 'public-companies',
    kind: 'dashboardWidget',
    labelKey: 'nav.public_companies',
    category: 'market_data',
    descriptionKey: 'dashboard.widgets.descriptions.publicCompanies',
    tags: ['Equities', 'Treasury', 'Stocks'],
    group: 'featured',
    ui: {
      icon: 'Building2',
      color: '#10B981',
    },
  },
  
  // Navigation Items (ensure IDs match Navbar.tsx dataNavOrder)
  {
    id: 'nav-liquidation-map',
    kind: 'nav',
    labelKey: 'nav.liquidation_map',
    href: '/liquidation-map',
    category: 'liquidation',
  },
  {
    id: 'nav-long-short-ratio',
    kind: 'nav',
    labelKey: 'nav.long_short_ratio',
    href: '/long-short-ratio',
    category: 'derivatives',
  },
  {
    id: 'nav-aggregated-orderbook',
    kind: 'nav',
    labelKey: 'nav.aggregated_orderbook',
    href: '/aggregated-orderbook',
    category: 'derivatives',
  },
  {
    id: 'nav-liquidation-data',
    kind: 'nav',
    labelKey: 'nav.liquidation_data',
    href: '/liquidation-data',
    category: 'liquidation',
  },
  {
    id: 'nav-prediction-market',
    kind: 'nav',
    labelKey: 'nav.prediction_market',
    href: '/prediction-market',
    category: 'market_data',
  },
  {
    id: 'nav-public-companies',
    kind: 'nav',
    labelKey: 'nav.public_companies',
    href: '/public-companies',
    category: 'market_data',
  },
]
