import type { OfficialStrategyPlazaTemplate } from '../types/official-strategy-plaza-template'

export const OFFICIAL_STRATEGY_PLAZA_TEMPLATES = [
  {
    id: 'ma-cross',
    name: 'MA 均线交叉',
    description: '短均线上穿长均线做多，跌回长均线下方退出。',
    logicDescription: '使用 20/60 均线判断趋势方向，适合趋势初期跟随。',
    tags: ['趋势跟随', '均线', 'OKX 模拟盘'],
    riskLevel: 'medium',
    scenario: '趋势行情',
    exchange: 'okx',
    environment: 'demo',
    status: 'live',
    displayOrder: 10,
    runConfig: {
      exchange: 'okx',
      marketType: 'perp',
      symbol: 'BTC-USDT-SWAP',
      timeframe: '15m',
      positionPct: 10,
      leverage: 2,
      publishedSnapshotId: 'official-plaza-ma-cross-v1-snapshot',
      deploymentExecutionConfig: { leverage: 2, priceSource: 'mark', orderType: 'market', timeInForce: 'ioc' },
    },
    editSeed: {
      initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 15m，创建一个 MA 20/60 均线交叉趋势跟随策略，仓位 10%，2 倍杠杆。',
      guideConfig: {
        symbolExample: 'BTC-USDT-SWAP',
        timeframeExample: '15m',
        entryRuleExample: 'MA20 上穿 MA60',
        exitRuleExample: 'MA20 下穿 MA60',
        riskRuleExample: 'OKX 模拟盘，仓位 10%，2 倍杠杆',
      },
    },
    displayMetrics: { label: 'official_sample_backtest', returnPct: null, winRatePct: null, maxDrawdownPct: null },
  },
  {
    id: 'bollinger-reversion',
    name: '布林带均值回归',
    description: '价格触及布林带外轨后等待回归，中轨附近止盈。',
    logicDescription: '使用 20 周期、2 倍标准差布林带识别偏离和回归。',
    tags: ['均值回归', '布林带', 'OKX 模拟盘'],
    riskLevel: 'medium',
    scenario: '震荡偏离后回归',
    exchange: 'okx',
    environment: 'demo',
    status: 'live',
    displayOrder: 20,
    runConfig: {
      exchange: 'okx',
      marketType: 'perp',
      symbol: 'ETH-USDT-SWAP',
      timeframe: '15m',
      positionPct: 8,
      leverage: 2,
      publishedSnapshotId: 'official-plaza-bollinger-reversion-v1-snapshot',
      deploymentExecutionConfig: { leverage: 2, priceSource: 'mark', orderType: 'market', timeInForce: 'ioc' },
    },
    editSeed: {
      initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 15m，创建布林带均值回归策略，触及外轨后回归中轨止盈，仓位 8%，2 倍杠杆。',
      guideConfig: {
        symbolExample: 'ETH-USDT-SWAP',
        timeframeExample: '15m',
        entryRuleExample: '价格触及布林带下轨后出现回归信号',
        exitRuleExample: '价格回归布林带中轨附近',
        riskRuleExample: 'OKX 模拟盘，仓位 8%，2 倍杠杆',
      },
    },
    displayMetrics: { label: 'official_sample_backtest', returnPct: null, winRatePct: null, maxDrawdownPct: null },
  },
  {
    id: 'grid-range',
    name: '网格区间',
    description: '在震荡区间内低买高卖，适合方向不明显的行情。',
    logicDescription: '使用固定区间和网格间距执行现货低买高卖。',
    tags: ['网格', '现货', 'OKX 模拟盘'],
    riskLevel: 'low',
    scenario: '区间震荡',
    exchange: 'okx',
    environment: 'demo',
    status: 'live',
    displayOrder: 30,
    runConfig: {
      exchange: 'okx',
      marketType: 'spot',
      symbol: 'BTC-USDT',
      timeframe: '15m',
      positionPct: 10,
      leverage: null,
      publishedSnapshotId: 'official-plaza-grid-range-v1-snapshot',
      deploymentExecutionConfig: { leverage: null, priceSource: 'last', orderType: 'market', timeInForce: 'ioc' },
    },
    editSeed: {
      initialMessage: '基于 OKX 模拟盘 BTC-USDT 现货 15m，创建网格区间策略，在震荡区间内低买高卖，单次仓位 10%。',
      guideConfig: {
        symbolExample: 'BTC-USDT',
        timeframeExample: '15m',
        entryRuleExample: '价格触及网格下沿买入',
        exitRuleExample: '价格触及上一个网格卖出',
        riskRuleExample: 'OKX 模拟盘现货，单次仓位 10%，不使用杠杆',
      },
    },
    displayMetrics: { label: 'official_sample_backtest', returnPct: null, winRatePct: null, maxDrawdownPct: null },
  },
  {
    id: 'rsi-reversal',
    name: 'RSI 超买超卖',
    description: 'RSI 低位买入，高位退出，适合短周期反转。',
    logicDescription: '使用 RSI 14，低于 30 视为超卖，高于 70 视为超买。',
    tags: ['RSI', '反转', 'OKX 模拟盘'],
    riskLevel: 'medium',
    scenario: '短周期反转',
    exchange: 'okx',
    environment: 'demo',
    status: 'live',
    displayOrder: 40,
    runConfig: {
      exchange: 'okx',
      marketType: 'spot',
      symbol: 'ETH-USDT',
      timeframe: '15m',
      positionPct: 8,
      leverage: null,
      publishedSnapshotId: 'official-plaza-rsi-reversal-v1-snapshot',
      deploymentExecutionConfig: { leverage: null, priceSource: 'last', orderType: 'market', timeInForce: 'ioc' },
    },
    editSeed: {
      initialMessage: '基于 OKX 模拟盘 ETH-USDT 现货 15m，创建 RSI 14 超买超卖策略，RSI 低于 30 买入，高于 70 卖出，仓位 8%。',
      guideConfig: {
        symbolExample: 'ETH-USDT',
        timeframeExample: '15m',
        entryRuleExample: 'RSI14 低于 30',
        exitRuleExample: 'RSI14 高于 70',
        riskRuleExample: 'OKX 模拟盘现货，仓位 8%，不使用杠杆',
      },
    },
    displayMetrics: { label: 'official_sample_backtest', returnPct: null, winRatePct: null, maxDrawdownPct: null },
  },
  {
    id: 'breakout-follow',
    name: '突破追踪',
    description: '价格突破近期区间后跟随趋势，跌回区间则退出。',
    logicDescription: '使用近期高点突破作为入场信号，适合波动扩张。',
    tags: ['突破', '趋势', 'OKX 模拟盘'],
    riskLevel: 'high',
    scenario: '波动扩张',
    exchange: 'okx',
    environment: 'demo',
    status: 'live',
    displayOrder: 50,
    runConfig: {
      exchange: 'okx',
      marketType: 'perp',
      symbol: 'BTC-USDT-SWAP',
      timeframe: '5m',
      positionPct: 8,
      leverage: 2,
      publishedSnapshotId: 'official-plaza-breakout-follow-v1-snapshot',
      deploymentExecutionConfig: { leverage: 2, priceSource: 'mark', orderType: 'market', timeInForce: 'ioc' },
    },
    editSeed: {
      initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 5m，创建突破追踪策略，突破近期高点跟随，跌回区间退出，仓位 8%，2 倍杠杆。',
      guideConfig: {
        symbolExample: 'BTC-USDT-SWAP',
        timeframeExample: '5m',
        entryRuleExample: '价格突破近期高点',
        exitRuleExample: '价格跌回突破区间',
        riskRuleExample: 'OKX 模拟盘，仓位 8%，2 倍杠杆',
      },
    },
    displayMetrics: { label: 'official_sample_backtest', returnPct: null, winRatePct: null, maxDrawdownPct: null },
  },
  {
    id: 'macd-cross',
    name: 'MACD 金叉死叉',
    description: 'MACD 金叉做多，死叉退出，适合趋势确认。',
    logicDescription: '使用 MACD 12/26/9 判断趋势动能变化。',
    tags: ['MACD', '动能', 'OKX 模拟盘'],
    riskLevel: 'medium',
    scenario: '趋势确认',
    exchange: 'okx',
    environment: 'demo',
    status: 'live',
    displayOrder: 60,
    runConfig: {
      exchange: 'okx',
      marketType: 'perp',
      symbol: 'ETH-USDT-SWAP',
      timeframe: '15m',
      positionPct: 8,
      leverage: 2,
      publishedSnapshotId: 'official-plaza-macd-cross-v1-snapshot',
      deploymentExecutionConfig: { leverage: 2, priceSource: 'mark', orderType: 'market', timeInForce: 'ioc' },
    },
    editSeed: {
      initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 15m，创建 MACD 12/26/9 金叉死叉策略，金叉做多，死叉退出，仓位 8%，2 倍杠杆。',
      guideConfig: {
        symbolExample: 'ETH-USDT-SWAP',
        timeframeExample: '15m',
        entryRuleExample: 'MACD DIF 上穿 DEA',
        exitRuleExample: 'MACD DIF 下穿 DEA',
        riskRuleExample: 'OKX 模拟盘，仓位 8%，2 倍杠杆',
      },
    },
    displayMetrics: { label: 'official_sample_backtest', returnPct: null, winRatePct: null, maxDrawdownPct: null },
  },
] satisfies readonly OfficialStrategyPlazaTemplate[]
