import type { OfficialStrategyPlazaCategory } from './official-strategy-plaza-category'
import type { OfficialStrategyPlazaTemplate, StrategyPlazaMarketType, StrategyPlazaTemplateId } from '../types/official-strategy-plaza-template'
import { OFFICIAL_STRATEGY_PLAZA_BACKTEST_EVIDENCE } from './official-strategy-plaza-backtest-evidence.constant'

const DEFAULT_RULES_ADMISSION = {
  maxDrawdownPctCeiling: 20,
  minWinRate: 0.52,
  minTradeCount: 20,
  minTotalReturnPct: 0.5,
} as const

interface TemplateSeed {
  id: StrategyPlazaTemplateId
  category: OfficialStrategyPlazaCategory
  name: string
  description: string
  logicDescription: string
  tags: string[]
  riskLevel: OfficialStrategyPlazaTemplate['riskLevel']
  scenario: string
  marketType: StrategyPlazaMarketType
  symbol: string
  timeframe: string
  positionPct: number
  leverage: number | null
  displayOrder: number
  initialMessage: string
  expectedAtomKeys: readonly string[]
  guideConfig: NonNullable<OfficialStrategyPlazaTemplate['editSeed']['guideConfig']>
  locales?: OfficialStrategyPlazaTemplate['editSeed']['locales']
}

function evidenceFor(templateId: OfficialStrategyPlazaTemplate['id']) {
  return OFFICIAL_STRATEGY_PLAZA_BACKTEST_EVIDENCE.templates.find(item => item.templateId === templateId)
}

function metricsFor(seed: TemplateSeed): OfficialStrategyPlazaTemplate['displayMetrics'] {
  const metrics = evidenceFor(seed.id)?.metrics
  return {
    label: 'official_sample_backtest',
    returnPct: metrics?.totalReturnPct ?? null,
    winRatePct: metrics ? Number((metrics.winRate * 100).toFixed(2)) : null,
    maxDrawdownPct: metrics?.maxDrawdownPct ?? null,
  }
}

function toTemplate(seed: TemplateSeed): OfficialStrategyPlazaTemplate {
  const priceSource = seed.marketType === 'spot' ? 'last' : 'mark'
  return {
    id: seed.id,
    category: seed.category,
    name: seed.name,
    description: seed.description,
    logicDescription: seed.logicDescription,
    tags: seed.tags,
    riskLevel: seed.riskLevel,
    scenario: seed.scenario,
    exchange: 'okx',
    environment: 'demo',
    status: 'live',
    displayOrder: seed.displayOrder,
    runConfig: {
      exchange: 'okx',
      marketType: seed.marketType,
      symbol: seed.symbol,
      timeframe: seed.timeframe,
      positionPct: seed.positionPct,
      leverage: seed.leverage,
      publishedSnapshotId: `official-plaza-${seed.id}-v1-snapshot`,
      deploymentExecutionConfig: { leverage: seed.leverage, priceSource, orderType: 'market', timeInForce: 'ioc' },
    },
    editSeed: {
      initialMessage: seed.initialMessage,
      guideConfig: seed.guideConfig,
      ...(seed.locales ? { locales: seed.locales } : {}),
    },
    expectedAtomKeys: seed.expectedAtomKeys,
    admission: DEFAULT_RULES_ADMISSION,
    displayMetrics: metricsFor(seed),
  }
}

const TEMPLATE_SEEDS: readonly TemplateSeed[] = [
  {
    id: 'ma-cross',
    category: '趋势',
    name: 'MA 均线交叉',
    description: '短均线上穿长均线做多，跌回长均线下方退出。',
    logicDescription: '使用优化后的 6/48 均线判断趋势方向，适合趋势初期跟随。',
    tags: ['趋势跟随', '均线', 'OKX 模拟盘'],
    riskLevel: 'medium',
    scenario: '趋势行情',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 35,
    leverage: 2,
    displayOrder: 10,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建 MA 6/48 均线交叉趋势跟随策略。规则：MA6 上穿 MA48 时做多开仓；MA6 下穿 MA48 时平多；风控：仓位 35%，2 倍杠杆，亏损 2% 止损，盈利 0.6% 止盈。',
    expectedAtomKeys: ['indicator.cross_over', 'indicator.cross_under', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct', 'risk.take_profit_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: 'MA6 上穿 MA48', exitRuleExample: 'MA6 下穿 MA48', riskRuleExample: '仓位 35%，2 倍杠杆' },
  },
  {
    id: 'macd-cross',
    category: '趋势',
    name: 'MACD 金叉趋势',
    description: 'MACD 金叉做多，死叉退出，适合趋势确认。',
    logicDescription: '使用 MACD 16/34/12 判断趋势动能变化。',
    tags: ['趋势', 'MACD', 'OKX 模拟盘'],
    riskLevel: 'medium',
    scenario: '趋势确认',
    marketType: 'perp',
    symbol: 'ETH-USDT-SWAP',
    timeframe: '15m',
    positionPct: 35,
    leverage: 2,
    displayOrder: 20,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 合约 15m，创建 MACD 16/34/12 趋势策略。规则：MACD DIF 上穿 DEA 时金叉做多、死叉平多；本策略只做多，不做空；风控：仓位 35%，2 倍杠杆，亏损 2% 止损，盈利 0.5% 止盈。',
    expectedAtomKeys: ['indicator.cross_over', 'indicator.cross_under', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct', 'risk.take_profit_pct'],
    guideConfig: { symbolExample: 'ETH-USDT-SWAP', timeframeExample: '15m', entryRuleExample: 'MACD DIF 上穿 DEA', exitRuleExample: 'MACD DIF 下穿 DEA 时平多', riskRuleExample: '仓位 35%，2 倍杠杆' },
    locales: {
      en: {
        initialMessage: 'Create a long-only MACD 16/34/12 trend strategy on OKX demo ETH-USDT-SWAP 15m. Rule: open long when MACD DIF crosses above DEA; close long when MACD DIF crosses below DEA; this strategy does not open short positions. Risk: 35% position, 2x leverage, 2% stop loss, 0.5% take profit.',
        guideConfig: { exitRuleExample: 'MACD DIF crosses below DEA to close long' },
      },
    },
  },
  {
    id: 'ema-trend-continuation',
    category: '趋势',
    name: 'EMA 趋势延续',
    description: '价格站上 EMA50 且 EMA20 上穿时跟随趋势。',
    logicDescription: '用 EMA50 方向过滤，EMA20/50 交叉触发。',
    tags: ['趋势', 'EMA', '延续'],
    riskLevel: 'medium',
    scenario: '趋势延续',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 25,
    leverage: 2,
    displayOrder: 30,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建 EMA 趋势延续策略。规则：价格高于 EMA50 且 EMA20 上穿 EMA50 时开多；价格跌破 EMA20 时平多；风控：仓位 25%，2 倍杠杆，亏损 2% 止损。',
    expectedAtomKeys: ['indicator.above', 'indicator.cross_over', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: '价格高于 EMA50 且 EMA20 上穿 EMA50', exitRuleExample: '价格跌破 EMA20', riskRuleExample: '仓位 25%，亏损 2% 止损' },
  },
  {
    id: 'ema-slope-trend',
    category: '趋势',
    name: 'EMA 斜率趋势',
    description: 'EMA20 斜率连续向上时做多。',
    logicDescription: '使用指标斜率确认趋势动能。',
    tags: ['趋势', '斜率', '动能'],
    riskLevel: 'medium',
    scenario: '动能趋势',
    marketType: 'perp',
    symbol: 'ETH-USDT-SWAP',
    timeframe: '15m',
    positionPct: 20,
    leverage: 2,
    displayOrder: 40,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 合约 15m，创建 EMA 斜率趋势策略。规则：EMA20 斜率连续 3 根向上且成交量确认放大后开多；价格跌破 EMA20 平多；风控：仓位 20%，2 倍杠杆，亏损 2% 止损。',
    expectedAtomKeys: ['indicator.slope', 'volume.confirmation', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'ETH-USDT-SWAP', timeframeExample: '15m', entryRuleExample: 'EMA20 斜率连续向上', exitRuleExample: '价格跌破 EMA20', riskRuleExample: '仓位 20%，亏损 2% 止损' },
  },
  {
    id: 'multi-timeframe-trend',
    category: '趋势',
    name: '多周期趋势确认',
    description: '15m 入场信号叠加 1h 趋势过滤。',
    logicDescription: '低周期交叉，高周期均线方向确认。',
    tags: ['趋势', '多周期', 'EMA'],
    riskLevel: 'medium',
    scenario: '多周期确认',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 20,
    leverage: 2,
    displayOrder: 50,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建多周期趋势策略。规则：15m EMA20 上穿 EMA50 开多，但 1h 价格必须在 MA50 上方才允许入场；15m 跌破 EMA20 平多；风控：仓位 20%，亏损 2% 止损。',
    expectedAtomKeys: ['indicator.cross_over', 'indicator.above', 'scope.timeframe', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m + 1h', entryRuleExample: '15m EMA 上穿且 1h 价格在 MA50 上方', exitRuleExample: '15m 跌破 EMA20', riskRuleExample: '仓位 20%，亏损 2% 止损' },
  },

  {
    id: 'breakout-follow',
    category: '突破',
    name: '突破追踪',
    description: '价格突破近期高点后跟随趋势。',
    logicDescription: '使用近期高点突破作为入场信号。',
    tags: ['突破', '趋势', 'OKX 模拟盘'],
    riskLevel: 'high',
    scenario: '波动扩张',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 25,
    leverage: 2,
    displayOrder: 110,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建突破追踪策略。规则：价格突破最近 24 根 K 线高点且突破缓冲 0.25% 时做多开仓；价格跌回最近 12 根 K 线低点时平多；风控：仓位 25%，2 倍杠杆，亏损 3% 止损，盈利 0.6% 止盈。',
    expectedAtomKeys: ['price.breakout_up', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct', 'risk.take_profit_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: '突破最近 24 根高点', exitRuleExample: '跌回最近 12 根低点', riskRuleExample: '仓位 25%，2 倍杠杆' },
  },
  {
    id: 'breakout-volume-confirm',
    category: '突破',
    name: '放量突破确认',
    description: '价格突破叠加成交量放大确认。',
    logicDescription: '突破高点且量能超过均量时入场。',
    tags: ['突破', '放量', '确认'],
    riskLevel: 'high',
    scenario: '量价突破',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 20,
    leverage: 2,
    displayOrder: 120,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建放量突破策略。规则：价格突破过去 20 根 K 线高点并且成交量超过 20 根均量 1.5 倍时开多；跌破 EMA20 平多；风控：仓位 20%，单笔最多亏 2%。',
    expectedAtomKeys: ['price.breakout_up', 'volume.threshold', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.max_loss_per_trade'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: '突破 20 根高点且放量', exitRuleExample: '跌破 EMA20', riskRuleExample: '单笔最多亏 2%' },
  },
  {
    id: 'breakout-pullback-hold',
    category: '突破',
    name: '突破回踩不破',
    description: '突破后等待回踩确认，降低假突破风险。',
    logicDescription: '记忆突破位，回踩不破再入场。',
    tags: ['突破', '回踩', '确认'],
    riskLevel: 'medium',
    scenario: '突破回踩',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 20,
    leverage: 2,
    displayOrder: 130,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建突破回踩策略。规则：价格突破 20 根高点后不立刻买，等回踩不破突破位再开多；跌破突破位下方止损；风控：仓位 20%，亏损 2% 止损。',
    expectedAtomKeys: ['price.breakout_up', 'pattern.pullback', 'price.previous_extrema_retest', 'action.open_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: '突破后回踩不破', exitRuleExample: '跌破突破位止损', riskRuleExample: '仓位 20%，亏损 2% 止损' },
  },
  {
    id: 'breakdown-short-follow',
    category: '突破',
    name: '跌破跟随做空',
    description: '价格跌破近期低点后跟随下行。',
    logicDescription: '向下突破低点触发空头趋势。',
    tags: ['突破', '做空', '跌破'],
    riskLevel: 'high',
    scenario: '下行突破',
    marketType: 'perp',
    symbol: 'ETH-USDT-SWAP',
    timeframe: '15m',
    positionPct: 20,
    leverage: 2,
    displayOrder: 140,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 合约 15m，创建跌破跟随做空策略。规则：价格跌破过去 20 根 K 线低点开空；价格重新站上 EMA20 平空；风控：仓位 20%，亏损 2% 止损。',
    expectedAtomKeys: ['price.breakout_down', 'indicator.above', 'action.open_short', 'action.close_short', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'ETH-USDT-SWAP', timeframeExample: '15m', entryRuleExample: '跌破 20 根低点', exitRuleExample: '重新站上 EMA20', riskRuleExample: '仓位 20%，亏损 2% 止损' },
  },
  {
    id: 'bollinger-breakout-stop',
    category: '突破',
    name: '布林突破止损',
    description: '突破布林带上轨后顺势跟随。',
    logicDescription: '布林上轨突破叠加固定止损。',
    tags: ['突破', '布林带', '止损'],
    riskLevel: 'medium',
    scenario: '布林突破',
    marketType: 'perp',
    symbol: 'ETH-USDT-SWAP',
    timeframe: '1h',
    positionPct: 15,
    leverage: 2,
    displayOrder: 150,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 合约 1h，创建布林突破策略。规则：价格向上突破布林带上轨时开多；价格回到布林带中轨时平多；风控：仓位 15%，亏损 2% 止损。',
    expectedAtomKeys: ['price.detect.indicator_boundary', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'ETH-USDT-SWAP', timeframeExample: '1h', entryRuleExample: '突破布林带上轨', exitRuleExample: '回到布林中轨', riskRuleExample: '仓位 15%，亏损 2% 止损' },
  },

  {
    id: 'bollinger-reversion',
    category: '反转',
    name: '布林带均值回归',
    description: '价格触及布林带外轨后等待回归。',
    logicDescription: '识别偏离后回归中轨。',
    tags: ['反转', '布林带', '均值回归'],
    riskLevel: 'medium',
    scenario: '震荡偏离后回归',
    marketType: 'perp',
    symbol: 'ETH-USDT-SWAP',
    timeframe: '15m',
    positionPct: 35,
    leverage: 2,
    displayOrder: 210,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 合约 15m，创建布林带均值回归策略。规则：价格触及布林带 30 周期 0.9 倍标准差下轨时做多开仓；价格回归布林带中轨时平多；风控：仓位 35%，2 倍杠杆，亏损 3% 止损，盈利 0.5% 止盈。',
    expectedAtomKeys: ['price.detect.indicator_boundary', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct', 'risk.take_profit_pct'],
    guideConfig: { symbolExample: 'ETH-USDT-SWAP', timeframeExample: '15m', entryRuleExample: '触及布林下轨', exitRuleExample: '回归布林中轨', riskRuleExample: '仓位 35%，2 倍杠杆' },
  },
  {
    id: 'rsi-reversal',
    category: '反转',
    name: 'RSI 超买超卖',
    description: 'RSI 低位买入，高位退出。',
    logicDescription: 'RSI 从超卖区向上修复视为反转。',
    tags: ['反转', 'RSI', '现货'],
    riskLevel: 'medium',
    scenario: '短周期反转',
    marketType: 'spot',
    symbol: 'ETH-USDT',
    timeframe: '15m',
    positionPct: 25,
    leverage: null,
    displayOrder: 220,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT 现货 15m，创建 RSI 反转策略。规则：RSI14 从 38 下方向上穿回 38 时买入；RSI14 高于 64 时卖出平仓；风控：仓位 25%，不使用杠杆，亏损 5% 止损，盈利 0.5% 止盈。',
    expectedAtomKeys: ['oscillator.rsi_lte', 'oscillator.rsi_gte', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct', 'risk.take_profit_pct'],
    guideConfig: { symbolExample: 'ETH-USDT', timeframeExample: '15m', entryRuleExample: 'RSI14 上穿 38', exitRuleExample: 'RSI14 高于 64', riskRuleExample: '仓位 25%，无杠杆' },
  },
  {
    id: 'rsi-cycle-reversion',
    category: '反转',
    name: 'RSI 多空循环',
    description: 'RSI 高位做空，低位退出。',
    logicDescription: '超买做空，超卖平空。',
    tags: ['反转', 'RSI', '做空'],
    riskLevel: 'medium',
    scenario: '高低位循环',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 15,
    leverage: 2,
    displayOrder: 230,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建 RSI 多空反转策略。规则：RSI14 高于 70 开空；RSI14 低于 30 平空；风控：仓位 15%，2 倍杠杆，亏损 2% 止损。',
    expectedAtomKeys: ['oscillator.rsi_gte', 'oscillator.rsi_lte', 'action.open_short', 'action.close_short', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: 'RSI14 高于 70 开空', exitRuleExample: 'RSI14 低于 30 平空', riskRuleExample: '仓位 15%，亏损 2% 止损' },
  },
  {
    id: 'indicator-boundary-reversion',
    category: '反转',
    name: '指标边界反转',
    description: '触及指标下边界后固定金额入场。',
    logicDescription: '边界偏离叠加 ATR 风险。',
    tags: ['反转', '边界', 'ATR'],
    riskLevel: 'medium',
    scenario: '指标边界',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 10,
    leverage: 5,
    displayOrder: 240,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建指标边界反转策略。规则：价格触及指标下边界时开多；价格回到指标中轨时平多；每次固定 100 USDT，使用 5 倍杠杆，并用 ATR14 的 2 倍止损。',
    expectedAtomKeys: ['price.detect.indicator_boundary', 'action.open_long', 'action.close_long', 'position.fixed_notional', 'position.leverage', 'risk.atr_stop'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: '触及指标下边界', exitRuleExample: '回到指标中轨', riskRuleExample: '固定 100 USDT，5 倍杠杆，ATR 止损' },
  },

  {
    id: 'grid-range',
    category: '网格',
    name: '区间低买高卖',
    description: '在震荡区间内低买高卖。',
    logicDescription: '按最近区间上下沿执行现货交易。',
    tags: ['区间', '低买高卖', 'OKX 模拟盘'],
    riskLevel: 'low',
    scenario: '区间震荡',
    marketType: 'spot',
    symbol: 'BTC-USDT',
    timeframe: '15m',
    positionPct: 25,
    leverage: null,
    displayOrder: 310,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT 现货 15m，创建区间低买高卖策略。规则：价格位于最近 36 根 K 线区间下 20% 时买入；价格回到区间上 55% 或盈利达到 0.45% 时卖出平仓；风控：单次仓位 25%，不使用杠杆，亏损 3% 止损。',
    expectedAtomKeys: ['pattern.range', 'price.range_position_lte', 'price.range_position_gte', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT', timeframeExample: '15m', entryRuleExample: '区间下 20% 买入', exitRuleExample: '区间上 55% 卖出', riskRuleExample: '单次仓位 25%，无杠杆' },
  },
  {
    id: 'fixed-grid-gated',
    category: '网格',
    name: '固定区间网格',
    description: '固定区间内挂多档网格。',
    logicDescription: '趋势上涨时启用固定网格程序。',
    tags: ['网格', '固定区间', '程序'],
    riskLevel: 'medium',
    scenario: '固定区间',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 320,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建固定区间网格策略。规则：在 65000-80000 区间挂 10 档网格，5% 步长，趋势上涨时启用；价格跌破区间下沿停止并平仓；风控：每格 10% 仓位，亏损 3% 止损。',
    expectedAtomKeys: ['program.fixed_grid_gated', 'pattern.range', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: '趋势上涨时启用 65000-80000 网格', exitRuleExample: '跌破区间下沿停止', riskRuleExample: '每格 10%，亏损 3% 止损' },
  },
  {
    id: 'trend-filtered-grid',
    category: '网格',
    name: '趋势过滤网格',
    description: '只在高周期趋势向上时运行区间网格。',
    logicDescription: '多周期趋势过滤降低逆势网格风险。',
    tags: ['网格', '趋势过滤', '多周期'],
    riskLevel: 'medium',
    scenario: '顺势网格',
    marketType: 'spot',
    symbol: 'ETH-USDT',
    timeframe: '15m',
    positionPct: 15,
    leverage: null,
    displayOrder: 330,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT 现货 15m，创建趋势过滤网格策略。规则：价格在震荡区间内且 1h 价格高于 MA50 时才买入；价格回到区间上沿卖出；风控：单次仓位 15%，亏损 3% 止损。',
    expectedAtomKeys: ['pattern.range', 'indicator.above', 'scope.timeframe', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'ETH-USDT', timeframeExample: '15m + 1h', entryRuleExample: '区间内且 1h 价格高于 MA50', exitRuleExample: '区间上沿卖出', riskRuleExample: '单次仓位 15%' },
  },
  {
    id: 'grid-breakout-stop',
    category: '网格',
    name: '突破停止网格',
    description: '区间突破后停止网格并撤出。',
    logicDescription: '网格只在区间内运行，突破边界时退出。',
    tags: ['网格', '突破停止', '风控'],
    riskLevel: 'low',
    scenario: '边界风控',
    marketType: 'spot',
    symbol: 'BTC-USDT',
    timeframe: '1m',
    positionPct: 10,
    leverage: null,
    displayOrder: 340,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT 现货 1m，创建突破停止网格策略。规则：价格在 65600-69600 区间内采用双向网格，每格 10 USDT；当价格突破上下边界时立即停止并撤销未成交订单；风控：总预算 1000 USDT。',
    expectedAtomKeys: ['program.fixed_grid_gated', 'position.budget_cap', 'pattern.range'],
    guideConfig: { symbolExample: 'BTC-USDT', timeframeExample: '1m', entryRuleExample: '65600-69600 区间双向网格', exitRuleExample: '突破边界停止撤单', riskRuleExample: '总预算 1000 USDT' },
  },

  {
    id: 'drawdown-dca-budget',
    category: 'DCA',
    name: '回撤预算 DCA',
    description: '价格回撤时分批补仓并限制总预算。',
    logicDescription: '按回撤幅度触发 DCA，预算上限控制风险。',
    tags: ['DCA', '预算', '回撤'],
    riskLevel: 'medium',
    scenario: '回撤补仓',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '1h',
    positionPct: 10,
    leverage: 2,
    displayOrder: 410,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 1h，创建回撤 DCA 策略。规则：价格每回撤 3% 补仓，最多 3 次，每次 100 USDT，总预算最多 1000 USDT；跌破本轮均价 8% 时全部退出。',
    expectedAtomKeys: ['position.dca_schedule', 'position.budget_cap', 'action.close_long'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '1h', entryRuleExample: '每回撤 3% 补仓', exitRuleExample: '跌破均价 8% 退出', riskRuleExample: '最多 3 次，总预算 1000 USDT' },
  },
  {
    id: 'timed-dca-budget',
    category: 'DCA',
    name: '定时预算 DCA',
    description: '按时间窗口分批买入并限制预算。',
    logicDescription: '周期性执行 DCA，适合分散入场。',
    tags: ['DCA', '定时', '预算'],
    riskLevel: 'low',
    scenario: '分批买入',
    marketType: 'spot',
    symbol: 'BTC-USDT',
    timeframe: '1h',
    positionPct: 10,
    leverage: null,
    displayOrder: 420,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT 现货 1h，创建定时 DCA 策略。规则：策略启动后每 24 小时买入一次，每次 100 USDT，最多执行 10 次，总预算 1000 USDT；价格跌破 30 日均线 8% 时暂停。',
    expectedAtomKeys: ['program.dca', 'position.budget_cap', 'strategy.time_window'],
    guideConfig: { symbolExample: 'BTC-USDT', timeframeExample: '1h', entryRuleExample: '每 24 小时买入一次', exitRuleExample: '跌破 30 日均线 8% 暂停', riskRuleExample: '总预算 1000 USDT' },
  },
  {
    id: 'dca-program-start',
    category: 'DCA',
    name: '启动即运行 DCA',
    description: '策略启动后按回撤执行 DCA 程序。',
    logicDescription: '程序化 DCA 管理补仓次数。',
    tags: ['DCA', '程序', '回撤'],
    riskLevel: 'medium',
    scenario: '自动补仓',
    marketType: 'perp',
    symbol: 'ETH-USDT-SWAP',
    timeframe: '1h',
    positionPct: 10,
    leverage: 2,
    displayOrder: 430,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 合约 1h，创建 DCA 程序策略。规则：策略启动后启用 DCA 程序，每回撤 3% 买入一次，最多执行 5 次；跌破本轮均价 8% 时全部退出；风控：总预算 1500 USDT。',
    expectedAtomKeys: ['program.dca', 'position.dca_schedule', 'position.budget_cap'],
    guideConfig: { symbolExample: 'ETH-USDT-SWAP', timeframeExample: '1h', entryRuleExample: '启动后启用 DCA 程序', exitRuleExample: '跌破均价 8% 退出', riskRuleExample: '总预算 1500 USDT' },
  },

  {
    id: 'orderbook-imbalance-long',
    category: '盘口',
    name: '盘口买盘失衡',
    description: '买盘深度占优时确认多头入场。',
    logicDescription: 'orderbook imbalance 作为入场确认源。',
    tags: ['盘口', 'orderbook', '深度'],
    riskLevel: 'high',
    scenario: '盘口确认',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '1m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 510,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 1m，创建盘口买盘失衡确认策略。规则：EMA20 上穿 EMA50 开多，但必须 OKX orderbook imbalance 大于 60% 才允许开仓；跌破 EMA20 时平多；风控：仓位 10%，2 倍杠杆，亏损 1% 止损。',
    expectedAtomKeys: ['indicator.cross_over', 'orderbook.imbalance', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '1m', entryRuleExample: 'EMA 上穿且 orderbook imbalance 大于 60%', exitRuleExample: '跌破 EMA20', riskRuleExample: '仓位 10%，亏损 1% 止损' },
  },
  {
    id: 'orderbook-spread-post-only',
    category: '盘口',
    name: '价差 Post-only',
    description: '窄价差和深度比确认后只挂 post-only 限价单。',
    logicDescription: '盘口价差和深度比共同控制执行质量。',
    tags: ['盘口', '价差', 'post-only'],
    riskLevel: 'high',
    scenario: '盘口执行',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '1m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 520,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 1m，创建盘口价差 post-only 策略。规则：盘口价差小于 0.03% 且买一卖一深度比超过 2 倍时，只用 post-only 限价单开多；跌破 EMA20 平多；风控：仓位 10%，亏损 1% 止损。',
    expectedAtomKeys: ['orderbook.spread_condition', 'orderbook.depth_ratio', 'execution.post_only', 'action.open_long', 'action.close_long', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '1m', entryRuleExample: '价差小于 0.03% 且深度比超过 2 倍', exitRuleExample: '跌破 EMA20', riskRuleExample: 'post-only，亏损 1% 止损' },
  },
  {
    id: 'orderbook-depth-ratio-confirm',
    category: '盘口',
    name: '盘口深度比确认',
    description: '买盘深度显著强于卖盘时确认趋势。',
    logicDescription: '深度比和 EMA 过滤组合。',
    tags: ['盘口', '深度比', 'EMA'],
    riskLevel: 'medium',
    scenario: '深度确认',
    marketType: 'perp',
    symbol: 'ETH-USDT-SWAP',
    timeframe: '1m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 530,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 合约 1m，创建盘口深度比确认策略。规则：价格高于 EMA50 且买盘深度是卖盘 1.5 倍以上时开多；价格跌破 EMA50 平多；风控：仓位 10%，亏损 1.2% 止损。',
    expectedAtomKeys: ['indicator.above', 'orderbook.depth_ratio', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'ETH-USDT-SWAP', timeframeExample: '1m', entryRuleExample: '价格高于 EMA50 且买盘深度 1.5 倍', exitRuleExample: '跌破 EMA50', riskRuleExample: '仓位 10%，亏损 1.2% 止损' },
  },

  {
    id: 'funding-rate-mean-reversion',
    category: '衍生品事件',
    name: '资金费率反转',
    description: '资金费率偏高时叠加 RSI 做空。',
    logicDescription: 'funding rate 事件流和 RSI 超买共同触发。',
    tags: ['资金费率', '反转', '衍生品'],
    riskLevel: 'high',
    scenario: '资金费率偏离',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 610,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建资金费率反转策略。规则：资金费率大于 0.01% 且 RSI14 高于 70 时开空；RSI14 低于 40 时平空；风控：仓位 10%，2 倍杠杆，亏损 1.5% 止损。',
    expectedAtomKeys: ['fundingRate.condition', 'oscillator.rsi_gte', 'oscillator.rsi_lte', 'action.open_short', 'action.close_short', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: '资金费率 > 0.01% 且 RSI 高于 70', exitRuleExample: 'RSI 低于 40', riskRuleExample: '仓位 10%，亏损 1.5% 止损' },
  },
  {
    id: 'open-interest-breakout',
    category: '衍生品事件',
    name: '持仓量突破确认',
    description: '未平仓量增长确认价格突破。',
    logicDescription: 'OI 增长和价格突破形成共振。',
    tags: ['OI', '突破', '衍生品'],
    riskLevel: 'high',
    scenario: 'OI 共振',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 620,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建持仓量突破确认策略。规则：未平仓量 1 小时增加超过 5% 且价格突破过去 20 根 K 线高点时开多；跌破 EMA20 时平多；风控：仓位 10%，亏损 2% 止损。',
    expectedAtomKeys: ['openInterest.condition', 'price.breakout_up', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: 'OI 增加 5% 且突破高点', exitRuleExample: '跌破 EMA20', riskRuleExample: '仓位 10%，亏损 2% 止损' },
  },
  {
    id: 'liquidation-cascade-short',
    category: '衍生品事件',
    name: '清算瀑布做空',
    description: '多头大额清算后顺势开空。',
    logicDescription: 'liquidation event stream 触发短线空头。',
    tags: ['清算', '做空', '衍生品'],
    riskLevel: 'high',
    scenario: '清算事件',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 630,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建清算瀑布开空策略。规则：多头清算超过 100 万 USDT 后开空；价格重新站上 EMA20 平空；风控：仓位 10%，亏损 2% 止损。',
    expectedAtomKeys: ['liquidation.condition', 'action.open_short', 'action.close_short', 'indicator.above', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: '多头清算超过 100 万 USDT', exitRuleExample: '重新站上 EMA20', riskRuleExample: '仓位 10%，亏损 2% 止损' },
  },
  {
    id: 'funding-oi-confirmation',
    category: '衍生品事件',
    name: 'Funding + OI 确认',
    description: '资金费率与持仓量共同确认趋势。',
    logicDescription: 'funding 和 open interest 事件流组合。',
    tags: ['资金费率', 'OI', '趋势'],
    riskLevel: 'medium',
    scenario: '衍生品共振',
    marketType: 'perp',
    symbol: 'ETH-USDT-SWAP',
    timeframe: '15m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 640,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 合约 15m，创建资金费率和持仓量确认策略。规则：资金费率为正且未平仓量增加超过 3%，同时 EMA20 上穿 EMA50 时开多；EMA20 下穿 EMA50 时平多；风控：仓位 10%，亏损 2% 止损。',
    expectedAtomKeys: ['fundingRate.condition', 'openInterest.condition', 'indicator.cross_over', 'indicator.cross_under', 'action.open_long', 'action.close_long', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'ETH-USDT-SWAP', timeframeExample: '15m', entryRuleExample: 'funding 为正、OI 增加且 EMA 上穿', exitRuleExample: 'EMA 下穿', riskRuleExample: '仓位 10%，亏损 2% 止损' },
  },

  {
    id: 'drawdown-guard-trend',
    category: '风控稳健',
    name: '回撤保护趋势',
    description: '账户回撤超过阈值后停止开仓。',
    logicDescription: '趋势入场叠加组合回撤风控。',
    tags: ['风控', '回撤', '趋势'],
    riskLevel: 'low',
    scenario: '回撤保护',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 710,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建回撤保护趋势策略。规则：EMA20 上穿 EMA50 开多；最大回撤超过 8% 停止开仓；跌破 EMA20 平多；风控：单笔仓位 10%，亏损 2% 止损。',
    expectedAtomKeys: ['indicator.cross_over', 'risk.max_drawdown_pct', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: 'EMA20 上穿 EMA50', exitRuleExample: '跌破 EMA20', riskRuleExample: '回撤超过 8% 停止开仓' },
  },
  {
    id: 'exposure-cap-trend',
    category: '风控稳健',
    name: '敞口上限趋势',
    description: '限制单策略最大敞口。',
    logicDescription: '趋势信号叠加敞口上限。',
    tags: ['风控', '敞口', '趋势'],
    riskLevel: 'low',
    scenario: '敞口限制',
    marketType: 'perp',
    symbol: 'ETH-USDT-SWAP',
    timeframe: '15m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 720,
    initialMessage: '基于 OKX 模拟盘 ETH-USDT-SWAP 合约 15m，创建敞口上限趋势策略。规则：EMA20 上穿 EMA50 开多；最大敞口不超过账户 30%；EMA20 下穿 EMA50 平多；风控：单笔仓位 10%，亏损 2% 止损。',
    expectedAtomKeys: ['indicator.cross_over', 'indicator.cross_under', 'position.max_exposure_pct', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.stop_loss_pct'],
    guideConfig: { symbolExample: 'ETH-USDT-SWAP', timeframeExample: '15m', entryRuleExample: 'EMA20 上穿 EMA50', exitRuleExample: 'EMA20 下穿 EMA50', riskRuleExample: '最大敞口 30%' },
  },
  {
    id: 'cooldown-after-stop',
    category: '风控稳健',
    name: '止损后冷却',
    description: '止损后等待冷却窗口再开仓。',
    logicDescription: '冷却规则减少连续止损。',
    tags: ['风控', '冷却', '止损'],
    riskLevel: 'low',
    scenario: '连续亏损防护',
    marketType: 'perp',
    symbol: 'BTC-USDT-SWAP',
    timeframe: '15m',
    positionPct: 10,
    leverage: 2,
    displayOrder: 730,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT-SWAP 合约 15m，创建止损后冷却策略。规则：MA20 上穿 MA50 开多；亏损 3% 止损；止损后冷却 5 根 K 线再开仓；跌破 EMA20 平多；风控：单笔仓位 10%。',
    expectedAtomKeys: ['indicator.cross_over', 'risk.stop_loss_pct', 'risk.cooldown', 'action.open_long', 'action.close_long', 'position.sizing'],
    guideConfig: { symbolExample: 'BTC-USDT-SWAP', timeframeExample: '15m', entryRuleExample: 'MA20 上穿 MA50', exitRuleExample: '跌破 EMA20', riskRuleExample: '止损后冷却 5 根 K' },
  },
  {
    id: 'low-drawdown-regime-gate',
    category: '风控稳健',
    name: '低回撤行情过滤',
    description: '只在价格位于长期均线上方时做多。',
    logicDescription: 'regime gate 控制策略启停。',
    tags: ['风控', '行情过滤', '低回撤'],
    riskLevel: 'low',
    scenario: '行情过滤',
    marketType: 'spot',
    symbol: 'BTC-USDT',
    timeframe: '15m',
    positionPct: 10,
    leverage: null,
    displayOrder: 740,
    initialMessage: '基于 OKX 模拟盘 BTC-USDT 现货 15m，创建低回撤行情过滤策略。规则：价格高于 EMA50 才允许做多，EMA20 上穿 EMA50 时买入；跌破 EMA20 卖出；风控：单笔仓位 10%，最大回撤超过 6% 停止开仓。',
    expectedAtomKeys: ['gate.regime', 'indicator.above', 'indicator.cross_over', 'action.open_long', 'action.close_long', 'position.sizing', 'risk.max_drawdown_pct'],
    guideConfig: { symbolExample: 'BTC-USDT', timeframeExample: '15m', entryRuleExample: '价格高于 EMA50 且 EMA20 上穿', exitRuleExample: '跌破 EMA20', riskRuleExample: '最大回撤 6% 停止开仓' },
  },
] as const

export const OFFICIAL_STRATEGY_PLAZA_TEMPLATES = TEMPLATE_SEEDS.map(toTemplate) satisfies readonly OfficialStrategyPlazaTemplate[]
