import type { OfficialStrategyPlazaTemplate } from '../types/official-strategy-plaza-template'
import { createHash } from 'node:crypto'
import {
  buildOfficialTemplateBacktestConfigDefaults,
  buildOfficialTemplateDataRequirements,
  buildOfficialTemplateDeploymentExecutionConstraints,
  buildOfficialTemplateDeploymentExecutionDefaults,
  buildOfficialTemplateParamsSnapshot,
  buildOfficialTemplateStrategyConfig,
} from './official-strategy-plaza-snapshot-content'

export const OFFICIAL_STRATEGY_PLAZA_USER_ID = 'official-strategy-plaza'
export const OFFICIAL_STRATEGY_PLAZA_LLM_MODEL = 'official-strategy-plaza'

function sha256Json(value: unknown): string {
  return createHash('sha256').update(JSON.stringify(value)).digest('hex')
}

function buildOfficialStrategyScript(template: OfficialStrategyPlazaTemplate): string {
  const params = buildOfficialTemplateParamsSnapshot(template)
  return [
    '// Official Strategy Plaza public beta template.',
    'type OfficialBar = { time?: number, open: number, high: number, low: number, close: number, volume?: number }',
    'type OfficialSignal = { enter: boolean, exit: boolean }',
    'type OfficialMacdPoint = { dif: number, dea: number }',
    'type OfficialParams = { positionPct?: number, parameterSearchId?: string, optimizedParams?: Record<string, number | undefined> }',
    `const TEMPLATE_ID: string = ${JSON.stringify(template.id)}`,
    `const PARAMS = ${JSON.stringify(params)} as OfficialParams`,
    '',
    'function closes(bars: OfficialBar[]): number[] { return bars.map(bar => Number(bar.close)) }',
    'function sma(values: number[], period: number): number | null {',
    '  if (!Array.isArray(values) || values.length < period || period <= 0) return null',
    '  const slice = values.slice(values.length - period)',
    '  return slice.reduce((sum, value) => sum + Number(value), 0) / period',
    '}',
    'function previousSma(values: number[], period: number): number | null { return sma(values.slice(0, -1), period) }',
    'function std(values: number[]): number {',
    '  if (values.length === 0) return 0',
    '  const avg = values.reduce((sum, value) => sum + Number(value), 0) / values.length',
    '  return Math.sqrt(values.reduce((sum, value) => sum + (Number(value) - avg) ** 2, 0) / values.length)',
    '}',
    'function highestHigh(bars: OfficialBar[], period: number): number | null {',
    '  if (!Array.isArray(bars) || bars.length <= period || period <= 0) return null',
    '  return Math.max(...bars.slice(-period - 1, -1).map(bar => Number(bar.high)))',
    '}',
    'function lowestLow(bars: OfficialBar[], period: number): number | null {',
    '  if (!Array.isArray(bars) || bars.length <= period || period <= 0) return null',
    '  return Math.min(...bars.slice(-period - 1, -1).map(bar => Number(bar.low)))',
    '}',
    'function rsi(values: number[], period: number): number | null {',
    '  if (!Array.isArray(values) || values.length <= period || period <= 0) return null',
    '  let gains = 0',
    '  let losses = 0',
    '  for (let index = values.length - period; index < values.length; index += 1) {',
    '    const change = Number(values[index]) - Number(values[index - 1])',
    '    if (change >= 0) gains += change',
    '    else losses += Math.abs(change)',
    '  }',
    '  if (losses === 0) return 100',
    '  const rs = gains / losses',
    '  return 100 - (100 / (1 + rs))',
    '}',
    'function emaSeries(values: number[], period: number): Array<number | null> {',
    '  const result: Array<number | null> = Array.from({ length: values.length }, () => null)',
    '  if (!Array.isArray(values) || values.length < period || period <= 0) return result',
    '  let previous = values.slice(0, period).reduce((sum, value) => sum + Number(value), 0) / period',
    '  const multiplier = 2 / (period + 1)',
    '  result[period - 1] = previous',
    '  for (let index = period; index < values.length; index += 1) {',
    '    previous = (Number(values[index]) - previous) * multiplier + previous',
    '    result[index] = previous',
    '  }',
    '  return result',
    '}',
    'function macd(values: number[], fastPeriod: number, slowPeriod: number, signalPeriod: number): Array<OfficialMacdPoint | null> {',
    '  const fast = emaSeries(values, fastPeriod)',
    '  const slow = emaSeries(values, slowPeriod)',
    '  const output: Array<OfficialMacdPoint | null> = Array.from({ length: values.length }, () => null)',
    '  const seed: number[] = []',
    '  let dea: number | null = null',
    '  const multiplier = 2 / (signalPeriod + 1)',
    '  for (let index = 0; index < values.length; index += 1) {',
    '    const fastValue = fast[index]',
    '    const slowValue = slow[index]',
    '    if (fastValue == null || slowValue == null) continue',
    '    const dif = fastValue - slowValue',
    '    if (dea == null) {',
    '      seed.push(dif)',
    '      if (seed.length < signalPeriod) continue',
    '      dea = seed.reduce((sum, value) => sum + value, 0) / seed.length',
    '    } else {',
    '      dea = (dif - dea) * multiplier + dea',
    '    }',
    '    output[index] = { dif, dea }',
    '  }',
    '  return output',
    '}',
    'function riskForEntry(referencePrice: number): StrategyDecisionV1["risk"] | undefined {',
    '  const optimized = PARAMS.optimizedParams || {}',
    '  const stopLossPct = Number(optimized.stopLossPct || 0)',
    '  const takeProfitPct = Number(optimized.takeProfitPct || 0)',
    '  if (!Number.isFinite(referencePrice) || referencePrice <= 0) return undefined',
    '  const risk: { stopLoss?: number, takeProfit?: number } = {}',
    '  if (Number.isFinite(stopLossPct) && stopLossPct > 0) risk.stopLoss = Number((referencePrice * (1 - stopLossPct / 100)).toFixed(8))',
    '  if (Number.isFinite(takeProfitPct) && takeProfitPct > 0) risk.takeProfit = Number((referencePrice * (1 + takeProfitPct / 100)).toFixed(8))',
    '  return Object.keys(risk).length > 0 ? risk : undefined',
    '}',
    'function decision(action: StrategyDecisionV1["action"], reason: string, referencePrice: number): StrategyDecisionV1 {',
    '  const output: StrategyDecisionV1 = { action, size: { mode: "RATIO", value: action === "CLOSE_LONG" ? 1 : Number(PARAMS.positionPct || 0) / 100 }, confidence: 90, reason, meta: { templateId: TEMPLATE_ID, parameterSearchId: PARAMS.parameterSearchId } }',
    '  if (action === "OPEN_LONG") output.risk = riskForEntry(referencePrice)',
    '  return output',
    '}',
    'function evaluate(ctx: StrategyExecutionContextV1): OfficialSignal {',
    '  const bars = (Array.isArray(ctx.bars) ? ctx.bars : []) as OfficialBar[]',
    '  const values = closes(bars)',
    '  const optimized = PARAMS.optimizedParams || {}',
    '  const last = bars[bars.length - 1]',
    '  if (!last) return { enter: false, exit: false }',
    '  const close = Number(last.close)',
    '  switch (TEMPLATE_ID) {',
    '    case "ma-cross": {',
    '      const fast = Number(optimized.fastPeriod || 6)',
    '      const slow = Number(optimized.slowPeriod || 48)',
    '      const currentFast = sma(values, fast)',
    '      const currentSlow = sma(values, slow)',
    '      const lastFast = previousSma(values, fast)',
    '      const lastSlow = previousSma(values, slow)',
    '      return { enter: currentFast != null && currentSlow != null && lastFast != null && lastSlow != null && currentFast > currentSlow && lastFast <= lastSlow, exit: currentFast != null && currentSlow != null && currentFast < currentSlow }',
    '    }',
    '    case "bollinger-reversion": {',
    '      const period = Number(optimized.period || 30)',
    '      const deviation = Number(optimized.deviation || 0.9)',
    '      if (values.length < period) return { enter: false, exit: false }',
    '      const window = values.slice(-period)',
    '      const middle = sma(values, period)',
    '      if (middle == null) return { enter: false, exit: false }',
    '      const lower = middle - std(window) * deviation',
    '      return { enter: close < lower, exit: close > middle }',
    '    }',
    '    case "grid-range": {',
    '      const lookback = Number(optimized.lookback || 36)',
    '      const low = lowestLow(bars, lookback)',
    '      const high = highestHigh(bars, lookback)',
    '      if (low == null || high == null || high <= low) return { enter: false, exit: false }',
    '      const range = high - low',
    '      return { enter: close <= low + range * Number(optimized.lowerBand || 0.2), exit: close >= low + range * Number(optimized.upperBand || 0.55) }',
    '    }',
    '    case "rsi-reversal": {',
    '      const period = Number(optimized.period || 14)',
    '      const current = rsi(values, period)',
    '      const previous = rsi(values.slice(0, -1), period)',
    '      const oversold = Number(optimized.oversold || 38)',
    '      return { enter: previous != null && current != null && previous <= oversold && current > oversold, exit: current != null && current >= Number(optimized.exitLevel || 64) }',
    '    }',
    '    case "breakout-follow": {',
    '      const lookback = Number(optimized.lookback || 24)',
    '      const high = highestHigh(bars, lookback)',
    '      const low = lowestLow(bars, Math.max(2, Math.floor(lookback / 2)))',
    '      return { enter: high != null && close >= high * (1 + Number(optimized.breakoutBufferPct || 0.25) / 100), exit: low != null && close < low }',
    '    }',
    '    case "macd-cross": {',
    '      const points = macd(values, Number(optimized.fastPeriod || 16), Number(optimized.slowPeriod || 34), Number(optimized.signalPeriod || 12))',
    '      const current = points[points.length - 1]',
    '      const previous = points[points.length - 2]',
    '      return { enter: previous != null && current != null && previous.dif <= previous.dea && current.dif > current.dea, exit: previous != null && current != null && previous.dif >= previous.dea && current.dif < current.dea }',
    '    }',
    '    default:',
    '      return { enter: false, exit: false }',
    '  }',
    '}',
    'const strategy: StrategyAdapterV1 = {',
    '  protocolVersion: "v1",',
    '  onBar(ctx: StrategyExecutionContextV1) {',
    '    const signal = evaluate(ctx)',
    '    const bars = (Array.isArray(ctx.bars) ? ctx.bars : []) as OfficialBar[]',
    '    const last = bars[bars.length - 1]',
    '    const referencePrice = Number(last && last.close)',
    '    if (signal.exit) return decision("CLOSE_LONG", `official.${TEMPLATE_ID}.exit`, referencePrice)',
    '    if (signal.enter) return decision("OPEN_LONG", `official.${TEMPLATE_ID}.entry`, referencePrice)',
    '    return { action: "NOOP", reason: `official.${TEMPLATE_ID}.noop`, meta: { templateId: TEMPLATE_ID } }',
    '  },',
    '}',
    'strategy',
    '',
  ].join('\n')
}

function buildOfficialStrategySpec(template: OfficialStrategyPlazaTemplate) {
  return {
    version: 1,
    source: 'strategy-plaza-official-template',
    templateId: template.id,
    name: template.name,
    logicDescription: template.logicDescription,
    runConfig: {
      exchange: template.runConfig.exchange,
      marketType: template.runConfig.marketType,
      symbol: template.runConfig.symbol,
      timeframe: template.runConfig.timeframe,
      positionPct: template.runConfig.positionPct,
      leverage: template.runConfig.leverage,
    },
  }
}

function buildOfficialStrategyAstSnapshot() {
  return {
    runtimeExecutionSemantics: [],
  }
}

export function buildOfficialStrategySnapshotContent(template: OfficialStrategyPlazaTemplate) {
  const scriptSnapshot = buildOfficialStrategyScript(template)
  const scriptHash = sha256Json(scriptSnapshot)
  const specSnapshot = buildOfficialStrategySpec(template)
  const astSnapshot = buildOfficialStrategyAstSnapshot()
  const semanticGraph = {
    nodes: [{ id: 'entry-primary', type: 'decision', label: template.name }],
    edges: [],
  }
  const compiledManifest = {
    source: 'strategy-plaza-official-template',
    templateId: template.id,
    artifactVersion: 1,
  }
  const compiledIr = {
    source: 'strategy-plaza-official-template',
    templateId: template.id,
    market: {
      venue: template.runConfig.exchange,
      symbol: template.runConfig.symbol,
      instrumentType: template.runConfig.marketType,
      timeframe: template.runConfig.timeframe,
    },
  }
  const runtimeContent = {
    paramsSnapshot: buildOfficialTemplateParamsSnapshot(template),
    strategyConfig: buildOfficialTemplateStrategyConfig(template),
    backtestConfigDefaults: buildOfficialTemplateBacktestConfigDefaults(template),
    deploymentExecutionDefaults: buildOfficialTemplateDeploymentExecutionDefaults(template),
    deploymentExecutionConstraints: buildOfficialTemplateDeploymentExecutionConstraints(template),
    dataRequirements: buildOfficialTemplateDataRequirements(template),
    lockedParams: buildOfficialTemplateParamsSnapshot(template),
  }

  return {
    snapshotHash: sha256Json({ scriptHash, specSnapshot, runtimeContent }),
    scriptHash,
    specHash: sha256Json(specSnapshot),
    irHash: sha256Json(compiledIr),
    astDigest: sha256Json(astSnapshot),
    structuralDigest: sha256Json({ semanticGraph, astSnapshot }),
    scriptSnapshot,
    specSnapshot,
    semanticGraph,
    compiledIr,
    irSnapshot: compiledIr,
    astSnapshot,
    compiledManifest,
    consistencyReport: { status: 'PASSED', source: 'strategy-plaza-official-template' },
    ...runtimeContent,
    executionEnvelope: { runtime: 'signal-generator', source: 'strategy-plaza-official-template' },
    executionPolicy: { signalTiming: 'BAR_CLOSE', fillTiming: 'NEXT_BAR_OPEN', allowPartialFill: false },
    userIntentSummary: { templateId: template.id, name: template.name },
    strategySummary: { name: template.name, description: template.description },
    scriptSummary: { source: 'strategy-plaza-official-template', logic: template.logicDescription },
    snapshotVersion: 3,
  }
}
