export const STAGE4_ATOM_FAMILIES = [
  'predicate',
  'action',
  'risk',
  'position',
  'program',
  'orchestration',
] as const

export type Stage4AtomFamily = typeof STAGE4_ATOM_FAMILIES[number]

export type Stage4RulePath =
  | 'rules[].condition'
  | 'rules[].effects.actions'
  | 'rules[].effects.risks'
  | 'rules[].effects.positions'
  | 'rules[].effects.programs'
  | 'rules[].effects.orchestration'

export type Stage4AtomStatus =
  | 'planned'
  | 'dialogue_ready'
  | 'rules_ready'
  | 'readiness_ready'
  | 'display_ready'
  | 'canonical_ready'
  | 'ir_ready'
  | 'runtime_ready'
  | 'backtest_ready'
  | 'deploy_ready'
  | 'corpus_pass'

export type Stage4RequiredDataSource =
  | 'ohlcv'
  | 'orderbook'
  | 'funding'
  | 'open_interest'
  | 'liquidation'
  | 'webhook'
  | 'none'

export type Stage4PrBatch =
  | 'pr2-predicate'
  | 'pr3-risk-position'
  | 'pr4-action-program'
  | 'pr5-orchestration-data'
  | 'pr6-corpus-acceptance'

export interface Stage4AtomCoverageRow {
  readonly atomKey: string
  readonly family: Stage4AtomFamily
  readonly rulePath: Stage4RulePath
  readonly coveredAtomKeys: readonly string[]
  readonly paramsSchema: readonly string[]
  readonly requiredSlots: readonly string[]
  readonly utteranceExamples: readonly string[]
  readonly displayShape: string
  readonly canonicalShape: string
  readonly irShape: string
  readonly runtimeRequirement: string
  readonly requiredDataSources: readonly Stage4RequiredDataSource[]
  readonly deployPayloadImpact: readonly string[]
  readonly corpusCases: readonly string[]
  readonly status: Stage4AtomStatus
  readonly unsupportedReason: string | null
  readonly prBatch: Stage4PrBatch
  readonly reachesBacktest: boolean
  readonly reachesDeployPayload: boolean
}

export const STAGE4_DEPLOY_READY_STATUSES = ['deploy_ready', 'corpus_pass'] as const satisfies readonly Stage4AtomStatus[]

export const STAGE4_ATOM_COVERAGE_MATRIX = [
  {
    atomKey: 'predicate.foundation.indicator_boundary',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['price.detect.indicator_boundary'],
    paramsSchema: ['indicator', 'boundary', 'direction'],
    requiredSlots: ['indicator', 'boundary'],
    utteranceExamples: [],
    displayShape: 'indicator boundary predicate',
    canonicalShape: 'CanonicalConditionAtom',
    irShape: 'predicate:indicator_boundary',
    runtimeRequirement: 'ohlcv bars and indicator series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes'],
    corpusCases: [],
    status: 'dialogue_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'action.open_long',
    family: 'action',
    rulePath: 'rules[].effects.actions',
    coveredAtomKeys: ['action.open_long'],
    paramsSchema: ['side', 'orderType', 'sizing'],
    requiredSlots: ['side'],
    utteranceExamples: ['EMA20 上穿 EMA50 开多，单笔 10% 仓位。', 'RSI14 低于 30 时开多。', 'Open long when EMA20 crosses above EMA50.'],
    displayShape: 'action open long effect with rules source path',
    canonicalShape: 'CanonicalRuleAction:OPEN_LONG with source path',
    irShape: 'ruleBlocks.actions:OPEN_LONG with source path',
    runtimeRequirement: 'script/runtime evaluator opens long position from rules action source path',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['ruleBlocks.actions.sourcePath', 'deployPayload.execution.actions.sourcePath'],
    corpusCases: ['pr4-trend-open-close'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr4-action-program',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'action.open_short',
    family: 'action',
    rulePath: 'rules[].effects.actions',
    coveredAtomKeys: ['action.open_short'],
    paramsSchema: ['side', 'orderType', 'sizing'],
    requiredSlots: ['side'],
    utteranceExamples: ['EMA20 下穿 EMA50 开空，单笔 10% 仓位。', '价格跌破 MA50 后开空。', 'Open short when EMA20 crosses below EMA50.'],
    displayShape: 'action open short effect with rules source path',
    canonicalShape: 'CanonicalRuleAction:OPEN_SHORT with source path',
    irShape: 'ruleBlocks.actions:OPEN_SHORT with source path',
    runtimeRequirement: 'script/runtime evaluator opens short position from rules action source path',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['ruleBlocks.actions.sourcePath', 'deployPayload.execution.actions.sourcePath'],
    corpusCases: ['pr4-trend-open-close'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr4-action-program',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'action.close_long',
    family: 'action',
    rulePath: 'rules[].effects.actions',
    coveredAtomKeys: ['action.close_long'],
    paramsSchema: ['side', 'orderType'],
    requiredSlots: ['side'],
    utteranceExamples: ['RSI14 高于 70 平多。', 'EMA20 下穿 EMA50 时平多。', 'Close long when price falls below EMA20.'],
    displayShape: 'action close long effect with rules source path',
    canonicalShape: 'CanonicalRuleAction:CLOSE_LONG with source path',
    irShape: 'ruleBlocks.actions:CLOSE_LONG with source path',
    runtimeRequirement: 'script/runtime evaluator closes long position from rules action source path',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['ruleBlocks.actions.sourcePath', 'deployPayload.execution.actions.sourcePath'],
    corpusCases: ['pr4-trend-open-close'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr4-action-program',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'action.close_short',
    family: 'action',
    rulePath: 'rules[].effects.actions',
    coveredAtomKeys: ['action.close_short'],
    paramsSchema: ['side', 'orderType'],
    requiredSlots: ['side'],
    utteranceExamples: ['RSI14 低于 30 平空。', 'EMA20 上穿 EMA50 时平空。', 'Close short when price rises above EMA20.'],
    displayShape: 'action close short effect with rules source path',
    canonicalShape: 'CanonicalRuleAction:CLOSE_SHORT with source path',
    irShape: 'ruleBlocks.actions:CLOSE_SHORT with source path',
    runtimeRequirement: 'script/runtime evaluator closes short position from rules action source path',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['ruleBlocks.actions.sourcePath', 'deployPayload.execution.actions.sourcePath'],
    corpusCases: ['pr4-trend-open-close'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr4-action-program',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'action.add_position',
    family: 'action',
    rulePath: 'rules[].effects.actions',
    coveredAtomKeys: ['action.add_position'],
    paramsSchema: ['side', 'addMode', 'addRatio', 'sizing'],
    requiredSlots: ['addMode'],
    utteranceExamples: ['盈利 2% 后加仓 10%。', '信号再次确认后加仓。', 'Add to the position after 2% profit.'],
    displayShape: 'action add position effect with rules source path',
    canonicalShape: 'CanonicalRuleAction:ADD_LONG|ADD_SHORT with source path',
    irShape: 'ruleBlocks.actions:ADD_LONG|ADD_SHORT with source path',
    runtimeRequirement: 'script/runtime evaluator adds position from rules action source path',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['ruleBlocks.actions.sourcePath', 'deployPayload.execution.actions.sourcePath'],
    corpusCases: ['pr4-add-position'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr4-action-program',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'action.reduce_position',
    family: 'action',
    rulePath: 'rules[].effects.actions',
    coveredAtomKeys: ['action.reduce_position'],
    paramsSchema: ['side', 'reducePct', 'orderType'],
    requiredSlots: ['reducePct'],
    utteranceExamples: ['盈利 5% 减仓一半。', 'Reduce 50% when profit reaches 5%.', '价格跌破 EMA20 后减仓 30%。'],
    displayShape: 'reduce action effect with rules source path',
    canonicalShape: 'unsupported reduce action canonical source path missing for generic action atom',
    irShape: 'unsupported generic reduce action source path missing',
    runtimeRequirement: 'runtime evaluator only supports reduce through partial take profit paths today',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['unsupported:deployPayload.execution.reduceAction.sourcePath'],
    corpusCases: ['pr4-reduce-unsupported'],
    status: 'planned',
    unsupportedReason: 'generic_reduce_action_deploy_binding_missing',
    prBatch: 'pr4-action-program',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'action.reverse_position',
    family: 'action',
    rulePath: 'rules[].effects.actions',
    coveredAtomKeys: ['action.reverse_position'],
    paramsSchema: ['fromSide', 'toSide', 'sizing'],
    requiredSlots: ['toSide'],
    utteranceExamples: ['EMA20 下穿 EMA50 时从多头反手做空。', '突破失败后平空并反手做多。', 'Reverse from long to short on EMA cross down.'],
    displayShape: 'action reverse position effect with rules source path',
    canonicalShape: 'CanonicalRuleAction:CLOSE_* + OPEN_* with source path',
    irShape: 'ruleBlocks.actions:CLOSE_* + OPEN_* with source path',
    runtimeRequirement: 'script/runtime evaluator reverses position from rules action source path',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['ruleBlocks.actions.sourcePath', 'deployPayload.execution.actions.sourcePath'],
    corpusCases: ['pr4-reverse-position'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr4-action-program',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'action.conditional_order',
    family: 'action',
    rulePath: 'rules[].effects.actions',
    coveredAtomKeys: ['action.conditional_order'],
    paramsSchema: ['triggerCondition', 'side', 'orderType'],
    requiredSlots: ['triggerCondition'],
    utteranceExamples: ['突破 70000 后下条件单开多。', 'Only place the order if BTC breaks 70000.', '价格回踩 EMA20 后触发买入条件单。'],
    displayShape: 'conditional order action effect with rules source path',
    canonicalShape: 'unsupported conditional order canonical source path missing',
    irShape: 'unsupported conditional order source path missing',
    runtimeRequirement: 'conditional order runtime binding missing',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['unsupported:deployPayload.execution.conditionalOrder.sourcePath'],
    corpusCases: ['pr4-conditional-order-unsupported'],
    status: 'planned',
    unsupportedReason: 'conditional_order_runtime_binding_missing',
    prBatch: 'pr4-action-program',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'action.limit_order',
    family: 'action',
    rulePath: 'rules[].effects.actions',
    coveredAtomKeys: ['action.limit_order'],
    paramsSchema: ['limitPrice', 'side', 'timeInForce'],
    requiredSlots: ['limitPrice'],
    utteranceExamples: ['BTC 到 65000 限价买入。', 'Place a limit buy at 65000.', '反弹到 70000 限价平多。'],
    displayShape: 'limit order action effect with rules source path',
    canonicalShape: 'unsupported limit order canonical source path missing',
    irShape: 'unsupported limit order source path missing',
    runtimeRequirement: 'limit order deploy payload binding missing',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['unsupported:deployPayload.execution.limitOrder.sourcePath'],
    corpusCases: ['pr4-limit-order-unsupported'],
    status: 'planned',
    unsupportedReason: 'limit_order_deploy_payload_binding_missing',
    prBatch: 'pr4-action-program',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'risk.foundation.atr_stop',
    family: 'risk',
    rulePath: 'rules[].effects.risks',
    coveredAtomKeys: ['risk.atr_stop'],
    paramsSchema: ['multiple', 'period'],
    requiredSlots: ['multiple'],
    utteranceExamples: [],
    displayShape: 'ATR stop risk effect',
    canonicalShape: 'risk guard',
    irShape: 'guard:atr_stop',
    runtimeRequirement: 'atr series and position state',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['riskPolicy.guards'],
    corpusCases: [],
    status: 'dialogue_ready',
    unsupportedReason: 'ir_compile_missing_branch',
    prBatch: 'pr3-risk-position',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'position.foundation.fixed_notional',
    family: 'position',
    rulePath: 'rules[].effects.positions',
    coveredAtomKeys: ['position.sizing'],
    paramsSchema: ['notional'],
    requiredSlots: ['notional'],
    utteranceExamples: [],
    displayShape: 'fixed notional position effect',
    canonicalShape: 'position sizing policy',
    irShape: 'position:fixed_notional',
    runtimeRequirement: 'account equity and symbol price',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['sizingPolicy'],
    corpusCases: [],
    status: 'dialogue_ready',
    unsupportedReason: 'deploy_payload_missing_binding',
    prBatch: 'pr3-risk-position',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'program.fixed_grid_gated',
    family: 'program',
    rulePath: 'rules[].effects.programs',
    coveredAtomKeys: ['program.fixed_grid_gated'],
    paramsSchema: ['lower', 'upper', 'gridCount', 'perOrderBudget'],
    requiredSlots: ['lower', 'upper', 'gridCount'],
    utteranceExamples: ['BTC 在 60000 到 70000 之间做 20 格网格，每格 100 USDT。', 'Run a fixed grid between 60000 and 70000 with 20 levels.', '震荡区间内开启固定网格。'],
    displayShape: 'fixed grid program effect with rules source path',
    canonicalShape: 'CanonicalOrchestrationProgram:fixed_grid_gated with source path',
    irShape: 'orchestrationPrograms:fixed_grid_gated with source path',
    runtimeRequirement: 'fixed grid runtime evaluator lifecycle binds source path through order program payload',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['deployPayload.orderPrograms.sourcePath', 'ir.orchestrationPrograms.sourcePath'],
    corpusCases: ['stage4-program-fixed-grid-gated'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr4-action-program',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'program.twap',
    family: 'program',
    rulePath: 'rules[].effects.programs',
    coveredAtomKeys: ['program.twap'],
    paramsSchema: ['totalSize', 'sliceCount', 'duration'],
    requiredSlots: ['totalSize', 'sliceCount', 'duration'],
    utteranceExamples: ['把 1000 USDT 分 10 次在 1 小时内 TWAP 买入 BTC。', 'TWAP buy 1000 USDT over one hour.', '一小时内分批均匀卖出 2 BTC。'],
    displayShape: 'TWAP program effect with rules source path',
    canonicalShape: 'unsupported TWAP program canonical source path missing',
    irShape: 'unsupported TWAP program source path missing',
    runtimeRequirement: 'TWAP runtime evaluator binding missing',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['unsupported:deployPayload.programs.twap.sourcePath'],
    corpusCases: ['pr4-twap-unsupported'],
    status: 'planned',
    unsupportedReason: 'program_twap_runtime_binding_missing',
    prBatch: 'pr4-action-program',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'program.dca',
    family: 'program',
    rulePath: 'rules[].effects.programs',
    coveredAtomKeys: ['program.dca'],
    paramsSchema: ['drawdownPct', 'maxCount', 'perOrderSizing'],
    requiredSlots: ['drawdownPct', 'maxCount'],
    utteranceExamples: ['BTC 每下跌 3% 做一次 DCA program，最多 3 次。', 'Run a DCA program every 3% drawdown.', '回撤后按程序定投，最多三轮。'],
    displayShape: 'DCA program effect with rules source path',
    canonicalShape: 'unsupported independent DCA program canonical source path missing; position.dca_schedule remains supported under positions',
    irShape: 'unsupported independent DCA program source path missing',
    runtimeRequirement: 'DCA program lifecycle deploy binding missing; existing DCA support remains position.dca_schedule',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['unsupported:deployPayload.programs.dca.sourcePath'],
    corpusCases: ['pr4-dca-program-unsupported'],
    status: 'planned',
    unsupportedReason: 'program_dca_lifecycle_deploy_binding_missing',
    prBatch: 'pr4-action-program',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'program.martingale',
    family: 'program',
    rulePath: 'rules[].effects.programs',
    coveredAtomKeys: ['program.martingale'],
    paramsSchema: ['multiplier', 'maxLayers', 'lossTrigger'],
    requiredSlots: ['multiplier', 'maxLayers'],
    utteranceExamples: ['亏损后按 2 倍 martingale 加码，最多 3 层。', 'Use martingale sizing after losses, max three layers.', '每次亏损后翻倍补单。'],
    displayShape: 'martingale program effect with rules source path',
    canonicalShape: 'unsupported martingale program canonical source path missing',
    irShape: 'unsupported martingale program source path missing',
    runtimeRequirement: 'martingale runtime evaluator binding missing',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['unsupported:deployPayload.programs.martingale.sourcePath'],
    corpusCases: ['pr4-martingale-unsupported'],
    status: 'planned',
    unsupportedReason: 'program_martingale_runtime_binding_missing',
    prBatch: 'pr4-action-program',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'program.rebalance',
    family: 'program',
    rulePath: 'rules[].effects.programs',
    coveredAtomKeys: ['program.rebalance'],
    paramsSchema: ['targets', 'interval', 'threshold'],
    requiredSlots: ['targets', 'interval'],
    utteranceExamples: ['BTC 和 ETH 每天再平衡到 50% 50%。', 'Rebalance BTC and ETH to equal weights daily.', '组合偏离 5% 后再平衡。'],
    displayShape: 'rebalance program effect with rules source path',
    canonicalShape: 'unsupported rebalance program canonical source path missing',
    irShape: 'unsupported rebalance program source path missing',
    runtimeRequirement: 'rebalance runtime evaluator binding missing',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['unsupported:deployPayload.programs.rebalance.sourcePath'],
    corpusCases: ['pr4-rebalance-unsupported'],
    status: 'planned',
    unsupportedReason: 'program_rebalance_runtime_binding_missing',
    prBatch: 'pr4-action-program',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'program.iceberg',
    family: 'program',
    rulePath: 'rules[].effects.programs',
    coveredAtomKeys: ['program.iceberg'],
    paramsSchema: ['totalSize', 'visibleSize', 'side'],
    requiredSlots: ['totalSize', 'visibleSize'],
    utteranceExamples: ['用 iceberg 订单把 10 BTC 拆成每次 0.5 BTC 卖出。', 'Sell 10 BTC with iceberg clips of 0.5 BTC.', '大单隐藏拆分执行。'],
    displayShape: 'iceberg program effect with rules source path',
    canonicalShape: 'unsupported iceberg program canonical source path missing',
    irShape: 'unsupported iceberg program source path missing',
    runtimeRequirement: 'iceberg runtime evaluator binding missing',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['unsupported:deployPayload.programs.iceberg.sourcePath'],
    corpusCases: ['pr4-iceberg-unsupported'],
    status: 'planned',
    unsupportedReason: 'program_iceberg_runtime_binding_missing',
    prBatch: 'pr4-action-program',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'orchestration.multi_timeframe',
    family: 'orchestration',
    rulePath: 'rules[].effects.orchestration',
    coveredAtomKeys: ['scope.timeframe'],
    paramsSchema: ['primaryTimeframe', 'requiredTimeframes', 'alignmentPolicy'],
    requiredSlots: ['primaryTimeframe', 'requiredTimeframes'],
    utteranceExamples: ['BTC 15m 入场，1h MA50 上方才允许开多。', 'Use 15m entries with 1h trend confirmation.', '15m EMA20 上穿，4h 趋势向上才交易。'],
    displayShape: 'multi-timeframe orchestration scope with rules source path',
    canonicalShape: 'CanonicalOrchestrationScope:timeframe with source path',
    irShape: 'IrOrchestrationScope:timeframe with source path',
    runtimeRequirement: 'runtime requires aligned OHLCV bars for primary and confirmation timeframes',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['deployPayload.orchestrationScopes.sourcePath', 'dataRequirements.requiredTimeframes'],
    corpusCases: ['stage4-multi-timeframe-trend-confirmation'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr5-orchestration-data',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'orchestration.multi_symbol',
    family: 'orchestration',
    rulePath: 'rules[].effects.orchestration',
    coveredAtomKeys: ['scope.symbol'],
    paramsSchema: ['symbols', 'primarySymbol'],
    requiredSlots: ['symbols'],
    utteranceExamples: ['BTCUSDT 和 ETHUSDT 共用 EMA20 上穿规则。', 'Run the same rule on BTCUSDT and ETHUSDT.', 'BTC 和 ETH 多标的共享止损和仓位。'],
    displayShape: 'multi-symbol orchestration scope with rules source path',
    canonicalShape: 'CanonicalOrchestrationScope:symbol with source path',
    irShape: 'IrOrchestrationScope:symbol with source path',
    runtimeRequirement: 'runtime requires symbol fanout and deploy payload symbol binding',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['deployPayload.orchestrationScopes.sourcePath', 'dataRequirements.requiredSymbols'],
    corpusCases: ['stage4-multi-symbol-shared-risk'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr5-orchestration-data',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'orchestration.multi_leg',
    family: 'orchestration',
    rulePath: 'rules[].effects.orchestration',
    coveredAtomKeys: ['scope.leg'],
    paramsSchema: ['legId', 'direction', 'instrumentRef', 'legSizing'],
    requiredSlots: ['legId', 'direction', 'instrumentRef'],
    utteranceExamples: ['BTC 多腿做多，ETH 对冲腿做空。', 'Create a long BTC leg and a short ETH hedge leg.', '双腿策略按固定比例同步触发。'],
    displayShape: 'multi-leg orchestration scope with rules source path',
    canonicalShape: 'CanonicalOrchestrationScope:leg with source path',
    irShape: 'IrOrchestrationScope:leg with source path',
    runtimeRequirement: 'runtime requires leg fanout, paired sizing, and deploy payload leg binding',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['unsupported:deployPayload.orchestrationLegScopes.sourcePath'],
    corpusCases: ['stage4-multi-leg-unsupported'],
    status: 'canonical_ready',
    unsupportedReason: 'deploy_payload_missing_binding',
    prBatch: 'pr5-orchestration-data',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'orchestration.portfolio_risk',
    family: 'orchestration',
    rulePath: 'rules[].effects.orchestration',
    coveredAtomKeys: ['portfolioRisk.drawdown_block', 'portfolioRisk.symbol_exposure_cap', 'portfolioRisk.substrategy_exposure_cap'],
    paramsSchema: ['thresholdPct', 'notionalCapPct', 'effectWhenTriggered', 'scopeRef'],
    requiredSlots: ['thresholdPct'],
    utteranceExamples: ['组合回撤超过 8% 停止开仓。', 'Stop new entries when portfolio drawdown exceeds 8%.', '单标的敞口不超过账户 30%。'],
    displayShape: 'portfolio risk orchestration guard with rules source path',
    canonicalShape: 'CanonicalOrchestrationPortfolioRisk with source path',
    irShape: 'IrOrchestrationPortfolioRisk with source path',
    runtimeRequirement: 'runtime requires portfolio equity and exposure state',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['deployPayload.portfolioRisk.sourcePath', 'ir.portfolioRisk.sourcePath'],
    corpusCases: ['stage4-portfolio-risk-drawdown-exposure'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr5-orchestration-data',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'orchestration.regime_gate',
    family: 'orchestration',
    rulePath: 'rules[].effects.orchestration',
    coveredAtomKeys: ['gate.regime'],
    paramsSchema: ['activeWhen', 'target', 'effect'],
    requiredSlots: ['activeWhen'],
    utteranceExamples: ['价格高于 EMA50 才允许做多。', 'Only enter when the regime gate is bullish.', '趋势向上时才启用入场规则。'],
    displayShape: 'regime gate orchestration effect with rules source path',
    canonicalShape: 'CanonicalOrchestrationGate:regime with source path',
    irShape: 'IrOrchestrationGate:regime with source path',
    runtimeRequirement: 'runtime requires gate state evaluation and deploy payload binding',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['deployPayload.orchestrationGates.sourcePath', 'ir.orchestrationGates.sourcePath'],
    corpusCases: ['stage4-regime-gate-trend-filter'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr5-orchestration-data',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'orchestration.data_source_binding',
    family: 'orchestration',
    rulePath: 'rules[].effects.orchestration',
    coveredAtomKeys: ['scope.dataSource', 'orderbook.imbalance', 'fundingRate.condition', 'openInterest.condition', 'liquidation.condition', 'external.signal'],
    paramsSchema: ['role', 'feedId', 'schemaRef'],
    requiredSlots: ['role', 'feedId', 'schemaRef'],
    utteranceExamples: ['用 Binance orderbook 做确认数据源。', 'Funding rate feed is the confirmation source.', 'TradingView webhook 是事件源。'],
    displayShape: 'data-source binding orchestration scope with rules source path',
    canonicalShape: 'CanonicalOrchestrationScope:dataSource with source path',
    irShape: 'IrOrchestrationScope:dataSource with source path',
    runtimeRequirement: 'runtime data feed and deploy payload binding required before executable use',
    requiredDataSources: ['orderbook', 'funding', 'open_interest', 'liquidation', 'webhook'],
    deployPayloadImpact: ['deployPayload.dataRequirements.sourcePath', 'ir.orchestrationScopes.sourcePath'],
    corpusCases: ['stage4-orderbook-data-source-binding', 'stage4-funding-data-source-binding', 'stage4-open-interest-data-source-binding', 'stage4-liquidation-data-source-binding', 'stage4-webhook-event-source-binding'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr5-orchestration-data',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'indicator.cross',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['indicator.cross_over', 'indicator.cross_under'],
    paramsSchema: ['indicator', 'fastPeriod', 'slowPeriod', 'period', 'threshold', 'timeframe'],
    requiredSlots: ['indicator'],
    utteranceExamples: ['EMA7 上穿 EMA21 做多，固定仓位 10%。', 'MACD DIF 下穿 DEA 平多。', 'RSI14 重新上穿 35 后开多。'],
    displayShape: 'indicator cross predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:indicator.cross_over|indicator.cross_under',
    irShape: 'predicate:CROSS_OVER|CROSS_UNDER',
    runtimeRequirement: 'ohlcv bars and indicator series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-indicator-cross'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'indicator.threshold',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['indicator.above', 'indicator.below', 'oscillator.rsi_gte', 'oscillator.rsi_lte'],
    paramsSchema: ['indicator', 'period', 'threshold', 'operator', 'timeframe'],
    requiredSlots: ['indicator', 'threshold'],
    utteranceExamples: ['RSI14 高于 70 时平多。', '价格站上 EMA20 时开多。', 'MA50 下方只允许做空。'],
    displayShape: 'indicator threshold predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:indicator.above|indicator.below|oscillator.rsi_*',
    irShape: 'predicate:indicator_compare|rsi_threshold',
    runtimeRequirement: 'ohlcv bars and indicator series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-indicator-threshold'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'indicator.slope',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['indicator.slope'],
    paramsSchema: ['indicator', 'period', 'direction', 'timeframe'],
    requiredSlots: ['indicator', 'direction'],
    utteranceExamples: ['EMA20 斜率向上时开多，单笔 10%。', 'MA50 开始向下倾斜时平多。', 'Enter long when EMA20 slope turns up, position 10%.'],
    displayShape: 'indicator slope predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:indicator.slope',
    irShape: 'predicate:indicator_slope',
    runtimeRequirement: 'ohlcv bars and indicator series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-indicator-slope'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'pattern.breakout',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['price.breakout_up', 'price.breakout_down', 'price.rolling_extrema_breakout'],
    paramsSchema: ['direction', 'lookback', 'timeframe'],
    requiredSlots: ['direction', 'lookback'],
    utteranceExamples: ['突破 24 小时高点后开多。', '跌破昨日低点后平多。', 'Break above the 20 bar high to enter long.'],
    displayShape: 'price breakout predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:price.breakout_up|price.breakout_down',
    irShape: 'predicate:breakout',
    runtimeRequirement: 'ohlcv bars and rolling extrema',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-pattern-breakout'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'pattern.pullback',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['pattern.pullback', 'price.previous_extrema_retest'],
    paramsSchema: ['anchor', 'behavior', 'withinBars'],
    requiredSlots: ['anchor', 'behavior'],
    utteranceExamples: ['突破后回踩不破再买。', 'Pullback holds the breakout level then enter long.', '回踩 MA20 站稳后开多。'],
    displayShape: 'pullback predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:pattern.pullback',
    irShape: 'predicate:pullback_hold',
    runtimeRequirement: 'ohlcv bars and remembered breakout level',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-pattern-pullback'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'pattern.range',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['pattern.range', 'price.range_position_lte', 'price.range_position_gte'],
    paramsSchema: ['lowerRole', 'upperRole', 'mode'],
    requiredSlots: ['lowerRole', 'upperRole'],
    utteranceExamples: ['价格在震荡区间内只做网格。', 'Range-bound between support and resistance.', '价格回到区间下沿附近开多。'],
    displayShape: 'range predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:pattern.range',
    irShape: 'predicate:range_state',
    runtimeRequirement: 'ohlcv bars and range bounds',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-pattern-range'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'volume.spike',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['volume.threshold'],
    paramsSchema: ['mode', 'multiplier', 'refWindow', 'metric'],
    requiredSlots: ['multiplier', 'refWindow'],
    utteranceExamples: ['成交量超过 20 根均量 1.5 倍时买入。', 'volume is above 2x the 20 bar average.', '放量超过均量后开多。'],
    displayShape: 'volume spike predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:volume.threshold',
    irShape: 'predicate:volume_relative_average',
    runtimeRequirement: 'ohlcv volume bars and average volume series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-volume-spike'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'volume.confirmation',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['volume.confirmation'],
    paramsSchema: ['mode', 'multiplier', 'refWindow'],
    requiredSlots: ['mode'],
    utteranceExamples: ['突破后需要放量确认再开多。', 'Confirm breakout with volume above 1.5x average.', '回踩后量能确认再买入。'],
    displayShape: 'volume confirmation predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:volume.confirmation',
    irShape: 'predicate:volume_confirmation',
    runtimeRequirement: 'ohlcv volume bars and average volume series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-volume-confirmation'],
    status: 'planned',
    unsupportedReason: 'ir_compile_missing_branch',
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'time.session',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['strategy.time_window'],
    paramsSchema: ['timezone', 'windows'],
    requiredSlots: ['windows'],
    utteranceExamples: ['只在北京时间 9:30 到 15:00 开仓。', 'Trade only during the London session.', '美股开盘后一小时内允许入场。'],
    displayShape: 'session time predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:strategy.time_window',
    irShape: 'predicate:time_window',
    runtimeRequirement: 'bar timestamp and timezone',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-time-session'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'time.cooldownWindow',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['time.cooldown_window'],
    paramsSchema: ['durationBars', 'durationMs', 'scope'],
    requiredSlots: ['durationBars'],
    utteranceExamples: ['每次交易后冷却 5 根 K 线再开仓。', 'Wait 30 minutes after an exit before re-entering.', '止损后 10 根 K 内不再入场。'],
    displayShape: 'cooldown window predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:time.cooldown_window',
    irShape: 'predicate:cooldown_window',
    runtimeRequirement: 'runtime trade timestamp state',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['runtimeRequirements.stateKeys', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-time-cooldown-window'],
    status: 'planned',
    unsupportedReason: 'runtime_missing_data',
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'event.externalSignal',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['external.signal'],
    paramsSchema: ['provider', 'signalId', 'secret'],
    requiredSlots: ['provider', 'signalId'],
    utteranceExamples: ['收到 TradingView webhook 信号后开多。', 'Enter when external signal whale_buy arrives.', '第三方信号触发时平仓。'],
    displayShape: 'external event predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:external.signal',
    irShape: 'predicate:externalSignal',
    runtimeRequirement: 'event inbox and signal id binding',
    requiredDataSources: ['webhook'],
    deployPayloadImpact: ['dataRequirements.eventSources', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-event-external-signal'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'orderbook.imbalance',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['orderbook.imbalance'],
    paramsSchema: ['side', 'ratio', 'depthPct'],
    requiredSlots: ['side', 'ratio'],
    utteranceExamples: ['买盘深度是卖盘 1.5 倍时开多。', 'Orderbook bid imbalance above 60 percent enters long.', '盘口买卖失衡偏多时只做多。'],
    displayShape: 'orderbook imbalance predicate shell with rules source path',
    canonicalShape: 'CanonicalConditionAtom:orderbook.imbalance',
    irShape: 'predicate:orderbook_imbalance',
    runtimeRequirement: 'orderbook runtime data source binding',
    requiredDataSources: ['orderbook'],
    deployPayloadImpact: ['dataRequirements.orderbook', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-orderbook-imbalance'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'fundingRate.condition',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['fundingRate.condition'],
    paramsSchema: ['operator', 'valuePct'],
    requiredSlots: ['operator', 'valuePct'],
    utteranceExamples: ['资金费率大于 0.01% 时不开多。', 'Enter short when funding rate is positive and high.', 'Funding below negative 0.02 percent then open long.'],
    displayShape: 'funding rate predicate shell with rules source path',
    canonicalShape: 'CanonicalConditionAtom:fundingRate.condition',
    irShape: 'predicate:funding_rate_condition',
    runtimeRequirement: 'funding rate runtime data source binding',
    requiredDataSources: ['funding'],
    deployPayloadImpact: ['dataRequirements.funding', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-funding-rate-condition'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'openInterest.condition',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['openInterest.condition'],
    paramsSchema: ['direction', 'changePct', 'window'],
    requiredSlots: ['direction', 'changePct'],
    utteranceExamples: ['持仓量 1 小时增加 5% 且价格突破时开多。', 'Open interest rising more than 5 percent confirms entry.', 'OI 快速下降时不要开仓。'],
    displayShape: 'open interest predicate shell with rules source path',
    canonicalShape: 'CanonicalConditionAtom:openInterest.condition',
    irShape: 'predicate:open_interest_condition',
    runtimeRequirement: 'open interest runtime data source binding',
    requiredDataSources: ['open_interest'],
    deployPayloadImpact: ['dataRequirements.openInterest', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-open-interest-condition'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'liquidation.condition',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['liquidation.condition'],
    paramsSchema: ['side', 'notionalUsd', 'window'],
    requiredSlots: ['side', 'notionalUsd'],
    utteranceExamples: ['多头清算超过 100 万 USDT 后开空。', 'Short liquidation spike above 1m confirms long entry.', '出现大额清算瀑布时暂停入场。'],
    displayShape: 'liquidation predicate shell with rules source path',
    canonicalShape: 'CanonicalConditionAtom:liquidation.condition',
    irShape: 'predicate:liquidation_condition',
    runtimeRequirement: 'liquidation runtime data source binding',
    requiredDataSources: ['liquidation'],
    deployPayloadImpact: ['dataRequirements.liquidation', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-liquidation-condition'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'risk.stop_loss_pct',
    family: 'risk',
    rulePath: 'rules[].effects.risks',
    coveredAtomKeys: ['risk.stop_loss_pct'],
    paramsSchema: ['valuePct', 'basis', 'scope'],
    requiredSlots: ['valuePct'],
    utteranceExamples: ['亏损 3% 止损。', 'Stop loss at 4 percent loss.', '入场后跌 2.5% 强制平仓。'],
    displayShape: 'fixed stop loss risk effect with source path',
    canonicalShape: 'risk guard STOP_LOSS_PCT',
    irShape: 'guard:STOP_LOSS_PCT',
    runtimeRequirement: 'position entry price and current price',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['riskPolicy.guards', 'ir.guards.sourcePath'],
    corpusCases: ['pr3-trend-fixed-stop'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'risk.trailing_stop_pct',
    family: 'risk',
    rulePath: 'rules[].effects.risks',
    coveredAtomKeys: ['risk.trailing_stop_pct'],
    paramsSchema: ['valuePct', 'basis', 'activationPct', 'scope'],
    requiredSlots: ['valuePct'],
    utteranceExamples: ['开多后用 3% 移动止损。', 'Use a 4 percent trailing stop after entry.', '突破后做多，trailing stop 2.5%。'],
    displayShape: 'trailing stop risk effect with source path',
    canonicalShape: 'risk guard TRAILING_STOP_PCT',
    irShape: 'guard:TRAILING_STOP_PCT',
    runtimeRequirement: 'position entry price, trailing anchor, and current price',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['riskPolicy.guards', 'ir.guards.sourcePath'],
    corpusCases: ['pr3-trend-trailing-stop'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'risk.partial_take_profit',
    family: 'risk',
    rulePath: 'rules[].effects.risks',
    coveredAtomKeys: ['risk.partial_take_profit'],
    paramsSchema: ['tiers', 'trigger', 'reduceRatio'],
    requiredSlots: ['tiers'],
    utteranceExamples: ['盈利 5% 平一半，盈利 10% 平剩余。', 'Take half profit at 5 percent and the rest at 10 percent.', '分两档止盈：5% 平 50%，10% 全平。'],
    displayShape: 'partial take profit risk effect with source path',
    canonicalShape: 'risk partial take profit rule blocks',
    irShape: 'ruleBlock:PARTIAL_TAKE_PROFIT',
    runtimeRequirement: 'position state and partial take profit memory',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['riskPolicy.partialTakeProfit', 'ir.ruleBlocks.sourcePath'],
    corpusCases: ['pr3-mean-reversion-partial-take-profit'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'risk.max_drawdown_pct',
    family: 'risk',
    rulePath: 'rules[].effects.risks',
    coveredAtomKeys: ['risk.max_drawdown_pct'],
    paramsSchema: ['valuePct', 'scope', 'action'],
    requiredSlots: ['valuePct'],
    utteranceExamples: ['最大回撤超过 8% 就停止开仓。', 'Pause entries when drawdown exceeds 10 percent.', '账户回撤 6% 后强制降风险。'],
    displayShape: 'maximum drawdown risk effect with source path',
    canonicalShape: 'risk drawdown guard',
    irShape: 'guard:MAX_DRAWDOWN_PCT',
    runtimeRequirement: 'equity curve and drawdown state',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['riskPolicy.drawdown', 'ir.guards.sourcePath'],
    corpusCases: ['pr3-trend-max-drawdown'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'risk.cooldown',
    family: 'risk',
    rulePath: 'rules[].effects.risks',
    coveredAtomKeys: ['risk.cooldown'],
    paramsSchema: ['durationBars', 'durationMs', 'afterEvent', 'scope'],
    requiredSlots: ['durationBars'],
    utteranceExamples: ['止损后冷却 5 根 K 线再开仓。', 'Wait 30 minutes after an exit before re-entering.', '每次交易后暂停 10 根 K 线。'],
    displayShape: 'cooldown risk effect with source path',
    canonicalShape: 'risk cooldown guard',
    irShape: 'guard:COOLDOWN',
    runtimeRequirement: 'last trade event state and bar clock',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['riskPolicy.cooldown', 'ir.guards.sourcePath'],
    corpusCases: ['pr3-trend-cooldown'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'risk.max_loss_per_trade',
    family: 'risk',
    rulePath: 'rules[].effects.risks',
    coveredAtomKeys: ['risk.max_loss_per_trade'],
    paramsSchema: ['valuePct', 'valueQuote', 'scope'],
    requiredSlots: ['valuePct'],
    utteranceExamples: ['单笔最多亏 2%。', 'Limit each trade loss to 100 USDT.', '每次交易亏损不能超过账户 1%。'],
    displayShape: 'per-trade loss cap risk effect with source path',
    canonicalShape: 'risk per trade loss cap',
    irShape: 'guard:MAX_LOSS_PER_TRADE',
    runtimeRequirement: 'position entry price, equity, and current loss state',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['riskPolicy.perTradeLossCap', 'ir.guards.sourcePath'],
    corpusCases: ['pr3-trend-max-loss-per-trade'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'position.sizing',
    family: 'position',
    rulePath: 'rules[].effects.positions',
    coveredAtomKeys: ['position.sizing'],
    paramsSchema: ['mode', 'value', 'asset', 'basis'],
    requiredSlots: ['value'],
    utteranceExamples: ['每次固定买入 100 USDT。', 'Use 10 percent of equity per trade.', '单笔仓位用账户 15%。'],
    displayShape: 'position sizing effect with source path',
    canonicalShape: 'position sizing policy',
    irShape: 'position:SIZING',
    runtimeRequirement: 'account equity and symbol price',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['sizingPolicy', 'ir.positions.sourcePath'],
    corpusCases: ['pr3-trend-position-sizing'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'position.pyramiding_limit',
    family: 'position',
    rulePath: 'rules[].effects.positions',
    coveredAtomKeys: ['position.pyramiding_limit'],
    paramsSchema: ['maxAdds', 'stepSizing', 'triggerMode'],
    requiredSlots: ['maxAdds'],
    utteranceExamples: ['盈利后最多加仓 2 次。', 'Allow pyramiding up to three adds.', '趋势延续时最多金字塔加仓 3 次。'],
    displayShape: 'pyramiding position effect with source path',
    canonicalShape: 'position pyramiding constraint',
    irShape: 'position:PYRAMIDING_LIMIT',
    runtimeRequirement: 'position lifecycle state and add count',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['positionPolicy.pyramiding', 'ir.positions.sourcePath'],
    corpusCases: ['pr3-add-position-pyramiding'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'position.dca_schedule',
    family: 'position',
    rulePath: 'rules[].effects.positions',
    coveredAtomKeys: ['position.dca_schedule'],
    paramsSchema: ['maxCount', 'capitalCap', 'perOrderSizing', 'triggerMode', 'exitRule'],
    requiredSlots: ['maxCount', 'perOrderSizing', 'triggerMode'],
    utteranceExamples: ['每跌 3% 补仓一次，最多 3 次。', 'DCA 100 USDT every day up to 5 times.', '回撤时分批补仓，总共最多 4 次。'],
    displayShape: 'DCA position effect with source path',
    canonicalShape: 'position DCA schedule',
    irShape: 'position:DCA_SCHEDULE',
    runtimeRequirement: 'semantic runtime state for DCA count and spent quote',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['positionPolicy.dca', 'ir.positions.sourcePath'],
    corpusCases: ['pr3-dca-schedule'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'position.budget_cap',
    family: 'position',
    rulePath: 'rules[].effects.positions',
    coveredAtomKeys: ['position.budget_cap'],
    paramsSchema: ['valueQuote', 'asset', 'scope'],
    requiredSlots: ['valueQuote'],
    utteranceExamples: ['总预算最多 1000 USDT。', 'Do not spend more than 500 USDT on this strategy.', '这个 DCA 策略预算上限 2000U。'],
    displayShape: 'budget cap position effect with source path',
    canonicalShape: 'position budget cap',
    irShape: 'position:BUDGET_CAP',
    runtimeRequirement: 'spent capital state and quote currency accounting',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['positionPolicy.budgetCap', 'ir.positions.sourcePath'],
    corpusCases: ['pr3-dca-budget-cap'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'position.leverage',
    family: 'position',
    rulePath: 'rules[].effects.positions',
    coveredAtomKeys: ['position.leverage'],
    paramsSchema: ['value', 'mode', 'scope'],
    requiredSlots: ['value'],
    utteranceExamples: ['使用 2 倍杠杆。', 'Run this strategy with 3x leverage.', '合约仓位杠杆固定 5 倍。'],
    displayShape: 'leverage position effect with source path',
    canonicalShape: 'position leverage policy',
    irShape: 'position:LEVERAGE',
    runtimeRequirement: 'perp market type and leverage-capable account',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['positionPolicy.leverage', 'backtest.leverage', 'ir.positions.sourcePath'],
    corpusCases: ['pr3-leverage'],
    status: 'canonical_ready',
    unsupportedReason: 'deploy_payload_missing_binding',
    prBatch: 'pr3-risk-position',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'position.max_exposure_pct',
    family: 'position',
    rulePath: 'rules[].effects.positions',
    coveredAtomKeys: ['position.max_exposure_pct'],
    paramsSchema: ['valuePct', 'scope', 'action'],
    requiredSlots: ['valuePct'],
    utteranceExamples: ['最大敞口不超过账户 30%。', 'Cap exposure at 25 percent of equity.', '单策略仓位敞口最多 20%。'],
    displayShape: 'exposure cap position effect with source path',
    canonicalShape: 'position exposure cap',
    irShape: 'position:MAX_EXPOSURE_PCT',
    runtimeRequirement: 'account equity and current exposure state',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['positionPolicy.exposureCap', 'ir.positions.sourcePath'],
    corpusCases: ['pr3-exposure-cap'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
] as const satisfies readonly Stage4AtomCoverageRow[]

export function isStage4DeployReadyAtom(row: Stage4AtomCoverageRow): boolean {
  const deployReadyStatuses: readonly Stage4AtomStatus[] = STAGE4_DEPLOY_READY_STATUSES

  return deployReadyStatuses.includes(row.status)
    && row.reachesBacktest
    && row.reachesDeployPayload
}
