export const STAGE4_ATOM_FAMILIES = [
  'predicate',
  'action',
  'risk',
  'position',
  'program',
  'orchestration',
] as const

export type Stage4AtomFamily = typeof STAGE4_ATOM_FAMILIES[number]

export type Stage4RulePath =
  | 'rules[].condition'
  | 'rules[].effects.actions'
  | 'rules[].effects.risks'
  | 'rules[].effects.positions'
  | 'rules[].effects.programs'
  | 'rules[].effects.orchestration'

export type Stage4AtomStatus =
  | 'planned'
  | 'dialogue_ready'
  | 'rules_ready'
  | 'readiness_ready'
  | 'display_ready'
  | 'canonical_ready'
  | 'ir_ready'
  | 'runtime_ready'
  | 'backtest_ready'
  | 'deploy_ready'
  | 'corpus_pass'

export type Stage4RequiredDataSource =
  | 'ohlcv'
  | 'orderbook'
  | 'funding'
  | 'open_interest'
  | 'liquidation'
  | 'webhook'
  | 'none'

export type Stage4PrBatch =
  | 'pr2-predicate'
  | 'pr3-risk-position'
  | 'pr4-action-program'
  | 'pr5-orchestration-data'
  | 'pr6-corpus-acceptance'

export interface Stage4AtomCoverageRow {
  readonly atomKey: string
  readonly family: Stage4AtomFamily
  readonly rulePath: Stage4RulePath
  readonly coveredAtomKeys: readonly string[]
  readonly paramsSchema: readonly string[]
  readonly requiredSlots: readonly string[]
  readonly utteranceExamples: readonly string[]
  readonly displayShape: string
  readonly canonicalShape: string
  readonly irShape: string
  readonly runtimeRequirement: string
  readonly requiredDataSources: readonly Stage4RequiredDataSource[]
  readonly deployPayloadImpact: readonly string[]
  readonly corpusCases: readonly string[]
  readonly status: Stage4AtomStatus
  readonly unsupportedReason: string | null
  readonly prBatch: Stage4PrBatch
  readonly reachesBacktest: boolean
  readonly reachesDeployPayload: boolean
}

export const STAGE4_DEPLOY_READY_STATUSES = ['deploy_ready', 'corpus_pass'] as const satisfies readonly Stage4AtomStatus[]

export const STAGE4_ATOM_COVERAGE_MATRIX = [
  {
    atomKey: 'predicate.foundation.indicator_boundary',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['price.detect.indicator_boundary'],
    paramsSchema: ['indicator', 'boundary', 'direction'],
    requiredSlots: ['indicator', 'boundary'],
    utteranceExamples: [],
    displayShape: 'indicator boundary predicate',
    canonicalShape: 'CanonicalConditionAtom',
    irShape: 'predicate:indicator_boundary',
    runtimeRequirement: 'ohlcv bars and indicator series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes'],
    corpusCases: [],
    status: 'planned',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'action.foundation.open_position',
    family: 'action',
    rulePath: 'rules[].effects.actions',
    coveredAtomKeys: ['action.open_long', 'action.open_short'],
    paramsSchema: ['side', 'orderType'],
    requiredSlots: ['side'],
    utteranceExamples: [],
    displayShape: 'open position action effect',
    canonicalShape: 'canonical rule action',
    irShape: 'action:open_position',
    runtimeRequirement: 'order lifecycle action support',
    requiredDataSources: ['none'],
    deployPayloadImpact: ['execution.actions'],
    corpusCases: [],
    status: 'planned',
    unsupportedReason: null,
    prBatch: 'pr4-action-program',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'risk.foundation.atr_stop',
    family: 'risk',
    rulePath: 'rules[].effects.risks',
    coveredAtomKeys: ['risk.atr_stop'],
    paramsSchema: ['multiple', 'period'],
    requiredSlots: ['multiple'],
    utteranceExamples: [],
    displayShape: 'ATR stop risk effect',
    canonicalShape: 'risk guard',
    irShape: 'guard:atr_stop',
    runtimeRequirement: 'atr series and position state',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['riskPolicy.guards'],
    corpusCases: [],
    status: 'planned',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'position.foundation.fixed_notional',
    family: 'position',
    rulePath: 'rules[].effects.positions',
    coveredAtomKeys: ['position.sizing'],
    paramsSchema: ['notional'],
    requiredSlots: ['notional'],
    utteranceExamples: [],
    displayShape: 'fixed notional position effect',
    canonicalShape: 'position sizing policy',
    irShape: 'position:fixed_notional',
    runtimeRequirement: 'account equity and symbol price',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['sizingPolicy'],
    corpusCases: [],
    status: 'planned',
    unsupportedReason: null,
    prBatch: 'pr3-risk-position',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'program.foundation.fixed_grid',
    family: 'program',
    rulePath: 'rules[].effects.programs',
    coveredAtomKeys: ['program.fixed_grid_gated'],
    paramsSchema: ['lower', 'upper', 'gridCount'],
    requiredSlots: ['lower', 'upper', 'gridCount'],
    utteranceExamples: [],
    displayShape: 'fixed grid program effect',
    canonicalShape: 'order program',
    irShape: 'program:fixed_grid',
    runtimeRequirement: 'order program lifecycle state',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['orderPrograms'],
    corpusCases: [],
    status: 'planned',
    unsupportedReason: null,
    prBatch: 'pr4-action-program',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'orchestration.foundation.scope_timeframe',
    family: 'orchestration',
    rulePath: 'rules[].effects.orchestration',
    coveredAtomKeys: ['scope.timeframe'],
    paramsSchema: ['timeframe'],
    requiredSlots: ['timeframe'],
    utteranceExamples: [],
    displayShape: 'timeframe scope orchestration effect',
    canonicalShape: 'scope binding',
    irShape: 'scope:timeframe',
    runtimeRequirement: 'multi-timeframe runtime context',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['scopeBindings.timeframes'],
    corpusCases: [],
    status: 'planned',
    unsupportedReason: null,
    prBatch: 'pr5-orchestration-data',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'indicator.cross',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['indicator.cross_over', 'indicator.cross_under'],
    paramsSchema: ['indicator', 'fastPeriod', 'slowPeriod', 'period', 'threshold', 'timeframe'],
    requiredSlots: ['indicator'],
    utteranceExamples: ['EMA7 上穿 EMA21 做多，固定仓位 10%。', 'MACD DIF 下穿 DEA 平多。', 'RSI14 重新上穿 35 后开多。'],
    displayShape: 'indicator cross predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:indicator.cross_over|indicator.cross_under',
    irShape: 'predicate:CROSS_OVER|CROSS_UNDER',
    runtimeRequirement: 'ohlcv bars and indicator series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-indicator-cross'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'indicator.threshold',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['indicator.above', 'indicator.below', 'oscillator.rsi_gte', 'oscillator.rsi_lte'],
    paramsSchema: ['indicator', 'period', 'threshold', 'operator', 'timeframe'],
    requiredSlots: ['indicator', 'threshold'],
    utteranceExamples: ['RSI14 高于 70 时平多。', '价格站上 EMA20 时开多。', 'MA50 下方只允许做空。'],
    displayShape: 'indicator threshold predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:indicator.above|indicator.below|oscillator.rsi_*',
    irShape: 'predicate:indicator_compare|rsi_threshold',
    runtimeRequirement: 'ohlcv bars and indicator series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-indicator-threshold'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'indicator.slope',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['indicator.slope'],
    paramsSchema: ['indicator', 'period', 'direction', 'timeframe'],
    requiredSlots: ['indicator', 'direction'],
    utteranceExamples: ['EMA20 斜率向上时开多，单笔 10%。', 'MA50 开始向下倾斜时平多。', 'Enter long when EMA20 slope turns up, position 10%.'],
    displayShape: 'indicator slope predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:indicator.slope',
    irShape: 'predicate:indicator_slope',
    runtimeRequirement: 'ohlcv bars and indicator series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-indicator-slope'],
    status: 'planned',
    unsupportedReason: 'ir_compile_missing_branch',
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'pattern.breakout',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['price.breakout_up', 'price.breakout_down', 'price.rolling_extrema_breakout'],
    paramsSchema: ['direction', 'lookback', 'timeframe'],
    requiredSlots: ['direction', 'lookback'],
    utteranceExamples: ['突破 24 小时高点后开多。', '跌破昨日低点后平多。', 'Break above the 20 bar high to enter long.'],
    displayShape: 'price breakout predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:price.breakout_up|price.breakout_down',
    irShape: 'predicate:breakout',
    runtimeRequirement: 'ohlcv bars and rolling extrema',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-pattern-breakout'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'pattern.pullback',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['pattern.pullback', 'price.previous_extrema_retest'],
    paramsSchema: ['anchor', 'behavior', 'withinBars'],
    requiredSlots: ['anchor', 'behavior'],
    utteranceExamples: ['突破后回踩不破再买。', 'Pullback holds the breakout level then enter long.', '回踩 MA20 站稳后开多。'],
    displayShape: 'pullback predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:pattern.pullback',
    irShape: 'predicate:pullback_hold',
    runtimeRequirement: 'ohlcv bars and remembered breakout level',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-pattern-pullback'],
    status: 'planned',
    unsupportedReason: 'ir_compile_missing_branch',
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'pattern.range',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['pattern.range', 'price.range_position_lte', 'price.range_position_gte'],
    paramsSchema: ['lowerRole', 'upperRole', 'mode'],
    requiredSlots: ['lowerRole', 'upperRole'],
    utteranceExamples: ['价格在震荡区间内只做网格。', 'Range-bound between support and resistance.', '价格回到区间下沿附近开多。'],
    displayShape: 'range predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:pattern.range',
    irShape: 'predicate:range_state',
    runtimeRequirement: 'ohlcv bars and range bounds',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-pattern-range'],
    status: 'planned',
    unsupportedReason: 'ir_compile_missing_branch',
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'volume.spike',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['volume.threshold'],
    paramsSchema: ['mode', 'multiplier', 'refWindow', 'metric'],
    requiredSlots: ['multiplier', 'refWindow'],
    utteranceExamples: ['成交量超过 20 根均量 1.5 倍时买入。', 'volume is above 2x the 20 bar average.', '放量超过均量后开多。'],
    displayShape: 'volume spike predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:volume.threshold',
    irShape: 'predicate:volume_relative_average',
    runtimeRequirement: 'ohlcv volume bars and average volume series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-volume-spike'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'volume.confirmation',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['volume.confirmation'],
    paramsSchema: ['mode', 'multiplier', 'refWindow'],
    requiredSlots: ['mode'],
    utteranceExamples: ['突破后需要放量确认再开多。', 'Confirm breakout with volume above 1.5x average.', '回踩后量能确认再买入。'],
    displayShape: 'volume confirmation predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:volume.confirmation',
    irShape: 'predicate:volume_confirmation',
    runtimeRequirement: 'ohlcv volume bars and average volume series',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-volume-confirmation'],
    status: 'planned',
    unsupportedReason: 'ir_compile_missing_branch',
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'time.session',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['strategy.time_window'],
    paramsSchema: ['timezone', 'windows'],
    requiredSlots: ['windows'],
    utteranceExamples: ['只在北京时间 9:30 到 15:00 开仓。', 'Trade only during the London session.', '美股开盘后一小时内允许入场。'],
    displayShape: 'session time predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:strategy.time_window',
    irShape: 'predicate:time_window',
    runtimeRequirement: 'bar timestamp and timezone',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['dataRequirements.requiredTimeframes', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-time-session'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'time.cooldownWindow',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['time.cooldown_window'],
    paramsSchema: ['durationBars', 'durationMs', 'scope'],
    requiredSlots: ['durationBars'],
    utteranceExamples: ['每次交易后冷却 5 根 K 线再开仓。', 'Wait 30 minutes after an exit before re-entering.', '止损后 10 根 K 内不再入场。'],
    displayShape: 'cooldown window predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:time.cooldown_window',
    irShape: 'predicate:cooldown_window',
    runtimeRequirement: 'runtime trade timestamp state',
    requiredDataSources: ['ohlcv'],
    deployPayloadImpact: ['runtimeRequirements.stateKeys', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-time-cooldown-window'],
    status: 'planned',
    unsupportedReason: 'runtime_missing_data',
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'event.externalSignal',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['external.signal'],
    paramsSchema: ['provider', 'signalId', 'secret'],
    requiredSlots: ['provider', 'signalId'],
    utteranceExamples: ['收到 TradingView webhook 信号后开多。', 'Enter when external signal whale_buy arrives.', '第三方信号触发时平仓。'],
    displayShape: 'external event predicate with rules source path',
    canonicalShape: 'CanonicalConditionAtom:external.signal',
    irShape: 'predicate:externalSignal',
    runtimeRequirement: 'event inbox and signal id binding',
    requiredDataSources: ['webhook'],
    deployPayloadImpact: ['dataRequirements.eventSources', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-event-external-signal'],
    status: 'deploy_ready',
    unsupportedReason: null,
    prBatch: 'pr2-predicate',
    reachesBacktest: true,
    reachesDeployPayload: true,
  },
  {
    atomKey: 'orderbook.imbalance',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['orderbook.imbalance'],
    paramsSchema: ['side', 'ratio', 'depthPct'],
    requiredSlots: ['side', 'ratio'],
    utteranceExamples: ['买盘深度是卖盘 1.5 倍时开多。', 'Orderbook bid imbalance above 60 percent enters long.', '盘口买卖失衡偏多时只做多。'],
    displayShape: 'orderbook imbalance predicate shell with rules source path',
    canonicalShape: 'CanonicalConditionAtom:orderbook.imbalance',
    irShape: 'predicate:orderbook_imbalance',
    runtimeRequirement: 'orderbook runtime data source binding',
    requiredDataSources: ['orderbook'],
    deployPayloadImpact: ['dataRequirements.orderbook', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-orderbook-imbalance'],
    status: 'dialogue_ready',
    unsupportedReason: 'data_source_missing',
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'fundingRate.condition',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['fundingRate.condition'],
    paramsSchema: ['operator', 'valuePct'],
    requiredSlots: ['operator', 'valuePct'],
    utteranceExamples: ['资金费率大于 0.01% 时不开多。', 'Enter short when funding rate is positive and high.', 'Funding below negative 0.02 percent then open long.'],
    displayShape: 'funding rate predicate shell with rules source path',
    canonicalShape: 'CanonicalConditionAtom:fundingRate.condition',
    irShape: 'predicate:funding_rate_condition',
    runtimeRequirement: 'funding rate runtime data source binding',
    requiredDataSources: ['funding'],
    deployPayloadImpact: ['dataRequirements.funding', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-funding-rate-condition'],
    status: 'dialogue_ready',
    unsupportedReason: 'data_source_missing',
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'openInterest.condition',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['openInterest.condition'],
    paramsSchema: ['direction', 'changePct', 'window'],
    requiredSlots: ['direction', 'changePct'],
    utteranceExamples: ['持仓量 1 小时增加 5% 且价格突破时开多。', 'Open interest rising more than 5 percent confirms entry.', 'OI 快速下降时不要开仓。'],
    displayShape: 'open interest predicate shell with rules source path',
    canonicalShape: 'CanonicalConditionAtom:openInterest.condition',
    irShape: 'predicate:open_interest_condition',
    runtimeRequirement: 'open interest runtime data source binding',
    requiredDataSources: ['open_interest'],
    deployPayloadImpact: ['dataRequirements.openInterest', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-open-interest-condition'],
    status: 'dialogue_ready',
    unsupportedReason: 'data_source_missing',
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
  {
    atomKey: 'liquidation.condition',
    family: 'predicate',
    rulePath: 'rules[].condition',
    coveredAtomKeys: ['liquidation.condition'],
    paramsSchema: ['side', 'notionalUsd', 'window'],
    requiredSlots: ['side', 'notionalUsd'],
    utteranceExamples: ['多头清算超过 100 万 USDT 后开空。', 'Short liquidation spike above 1m confirms long entry.', '出现大额清算瀑布时暂停入场。'],
    displayShape: 'liquidation predicate shell with rules source path',
    canonicalShape: 'CanonicalConditionAtom:liquidation.condition',
    irShape: 'predicate:liquidation_condition',
    runtimeRequirement: 'liquidation runtime data source binding',
    requiredDataSources: ['liquidation'],
    deployPayloadImpact: ['dataRequirements.liquidation', 'ir.predicates.sourcePath'],
    corpusCases: ['pr2-liquidation-condition'],
    status: 'dialogue_ready',
    unsupportedReason: 'data_source_missing',
    prBatch: 'pr2-predicate',
    reachesBacktest: false,
    reachesDeployPayload: false,
  },
] as const satisfies readonly Stage4AtomCoverageRow[]

export function isStage4DeployReadyAtom(row: Stage4AtomCoverageRow): boolean {
  const deployReadyStatuses: readonly Stage4AtomStatus[] = STAGE4_DEPLOY_READY_STATUSES

  return deployReadyStatuses.includes(row.status)
    && row.reachesBacktest
    && row.reachesDeployPayload
}
