import { STAGING30_RULES_ONLY_CASES } from '../staging30-rules-only-mainflow-cases'
import {
  buildStaging30EvidenceSummary,
  extractStaging30HashesFromResponse,
} from '../staging30-rules-only-mainflow-report'

describe('staging30 rules-only mainflow report', () => {
  it('contains exactly 30 new-session staging cases', () => {
    expect(STAGING30_RULES_ONLY_CASES).toHaveLength(30)
    expect(new Set(STAGING30_RULES_ONLY_CASES.map(item => item.id)).size).toBe(30)
    expect(STAGING30_RULES_ONLY_CASES.every(item => item.prompt.trim().length > 0)).toBe(true)
  })

  it('fails a case when flat fallback is observed', () => {
    const summary = buildStaging30EvidenceSummary([{
      caseId: 's01',
      status: 'failed',
      hashes: null,
      usedFlatFallback: true,
      steps: [],
      failureReason: 'flat fallback observed',
    }])

    expect(summary.passed).toBe(false)
    expect(summary.failedCaseIds).toEqual(['s01'])
    expect(summary.failures[0]).toContain('flat fallback observed')
  })

  it('requires all hash-chain fields for a passing case', () => {
    const summary = buildStaging30EvidenceSummary([{
      caseId: 's01',
      status: 'passed',
      hashes: {
        rulesHash: 'sha256:a',
        canonicalSpecHash: 'sha256:b',
        irHash: 'sha256:c',
        astHash: 'sha256:d',
        scriptHash: 'sha256:e',
        runtimeEvaluatorVersion: '',
      },
      usedFlatFallback: false,
      steps: ['session', 'confirmGenerate', 'publish'],
      failureReason: null,
    }])

    expect(summary.passed).toBe(false)
    expect(summary.failedCaseIds).toEqual(['s01'])
    expect(summary.failures[0]).toContain('hashes incomplete')
  })

  it('does not accept astDigest as staging astHash evidence', () => {
    const summary = buildStaging30EvidenceSummary([{
      caseId: 's01',
      status: 'passed',
      hashes: {
        rulesHash: 'sha256:a',
        canonicalSpecHash: 'sha256:b',
        irHash: 'sha256:c',
        astHash: '',
        scriptHash: 'sha256:e',
        runtimeEvaluatorVersion: 'compiler.v1',
      },
      usedFlatFallback: false,
      steps: ['session', 'confirmGenerate', 'publish'],
      failureReason: null,
    }])

    expect(summary.passed).toBe(false)
    expect(summary.failures[0]).toContain('hashes incomplete')
  })

  it('extracts hash-chain evidence from public specDesc and runtime version from script header', () => {
    expect(extractStaging30HashesFromResponse({
      scriptCode: '/* @generated by compiler.v1 */\n/* irHash: sha256:c */',
      specDesc: {
        rulesOnlyHashChain: {
          hashes: {
            rulesHash: 'sha256:a',
            canonicalSpecHash: 'sha256:b',
            irHash: 'sha256:c',
            astHash: 'sha256:d',
            scriptHash: 'sha256:e',
          },
        },
      },
    })).toEqual({
      rulesHash: 'sha256:a',
      canonicalSpecHash: 'sha256:b',
      irHash: 'sha256:c',
      astHash: 'sha256:d',
      scriptHash: 'sha256:e',
      runtimeEvaluatorVersion: 'compiler.v1',
    })
  })

  it('does not invent runtime version when script header is absent', () => {
    expect(extractStaging30HashesFromResponse({
      specDesc: {
        rulesOnlyHashChain: {
          hashes: {
            rulesHash: 'sha256:a',
            canonicalSpecHash: 'sha256:b',
            irHash: 'sha256:c',
            astHash: 'sha256:d',
            scriptHash: 'sha256:e',
          },
        },
      },
    })).toBeNull()
  })
})
